### ISSUE TITLE
[Bug]: Listbox selected value not working for dynamically passed values

### ISSUE THREAD

**Issue by snax4a** [tailwindlabs/headlessui#618] opened 2021-06-14 10:20 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.2.0

### What browser are you using?

Microsoft Edge dev

### Reproduction repository

https://codesandbox.io/embed/tailwind-css-and-react-forked-hkusj?fontsize=14&hidenavigation=1&theme=dark

### Describe your issue

Hi,
Im having problem with Listbox component when I pass value as an object instead array index its not displaying selected checkbox in the listbox options

```
const people = [
  { name: "Wade Cooper" },
  { name: "Arlene Mccoy" },
  { name: "Devon Webb" },
  { name: "Tom Cook" },
  { name: "Tanya Fox" },
  { name: "Hellen Schmidt" }
];
```

`<Listbox value={people[0]}  />` // this works
`<Listbox value={{ name: "Wade Cooper" }  /> `// this not

Im trying to set listbox value as object loaded from API, this object exists in people array so i thought it would work but its not working.

Here is codesandbox example:
https://codesandbox.io/embed/tailwind-css-and-react-forked-hkusj?fontsize=14&hidenavigation=1&theme=dark

**Comment by RobinMalfait** [comment] 2021-06-14 10:32
Hey! Thank you for your bug report!
Much appreciated! 🙏

That's because `{ name: "Wade Cooper" } !== { name: "Wade Cooper" }`, you have to make sure that you are using the same reference to the object. Alternatively, you can use the `name` or an `id` as the value (assuming those are primitive values).

Going to close this because it is a duplicate of #585

**Closed by RobinMalfait** 2021-06-14 10:32 UTC

**Comment by ihatem** [comment] 2021-07-08 20:43
I also noticed that if you declare the `people` variable inside the React function, the `Listbox.Option` will not detect the selected value.

**Comment by RobinMalfait** [comment] 2021-07-08 21:03
@ihatem that's because when the component re-renders fresh objects are created and then you end up in this situation: https://github.com/tailwindlabs/headlessui/issues/618#issuecomment-860579578

**Comment by RodrigoTomeES** [comment] 2023-08-13 08:38
Hi, I had the same problem and I think the API should be support this to facilitie this use case. I think that Lisbox could be accept a prop to enabled a comparator function by ID or expose the comparator function. In this way we won't change nothing between static values and dynamic only pass the comparator function.

What do you think?

@RobinMalfait

**Comment by RobinMalfait** [comment] 2023-08-13 08:41
@RodrigoTomeES hey! Checkout the docs on the `by` prop. It allows you to pass a field to use for comparison or a function to compare 2 objects: https://headlessui.com/react/listbox#binding-objects-as-values

**Comment by RodrigoTomeES** [comment] 2023-08-13 08:52
Ey, thanks! I didn't see it 🚀🙈

**Comment by ruffjaxson** [comment] 2024-08-07 06:20
Agree with @boy51 ... this was very unintuitive... but I guess I should have read the docs more carefully...?
