### ISSUE TITLE
Using `null` as the value of a combobox option no longer works in @headlessui/vue v1.7.17

### ISSUE THREAD

**Issue by henribru** [tailwindlabs/headlessui#2963] opened 2024-02-02 16:01 UTC
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.17

**What browser are you using?**

Firefox 122

**Reproduction URL**
https://codesandbox.io/p/devbox/quiet-fog-qlqjp8?file=%2Fpackage.json%3A27%2C28

**Describe your issue**

Using `null` as the value of a combobox option no longer works in v1.7.17. As soon as you hover over the combobox option with value `null`, you'll see an error in the console. The same code works fine in v1.7.16.

**Comment by Barbapapazes** [comment] 2024-02-03 17:09
Got a similar regression https://github.com/unjs/website/issues/285. I must pin this dep.

**Comment by reinink** [comment] 2024-02-07 20:32
Hey folks! Thanks for reporting this issue. We've just merged in a fix (#2973) for this and will get a new release tagged before the end of the day 👍

**Closed by reinink** 2024-02-07 20:32 UTC

**Comment by thecrypticace** [comment] 2024-02-07 22:03
`@headlessui/vue@1.7.19` is out with the fix!

**Comment by fernandolangaro** [comment] 2024-07-28 23:45
The from this issue error is not fixed in the Vue @insiders version. Could you please check on this?

I use the Vue @insiders version because it's the only version that addresses this problem: https://github.com/tailwindlabs/headlessui/discussions/1205

I've tried the latest version, 1.7.22, but although the bug from this issue is fixed, the options still won't open when clicked.

So, in the current scenario, I must choose between two bugs to stick with 🫠

**Comment by fernandolangaro** [comment] 2024-07-28 23:54
> Hey folks! Thanks for reporting this issue. We've just merged in a fix (#2973) for this and will get a new release tagged before the end of the day 👍

This issue is not fixed in the Vue https://github.com/insiders version. Could you please check on this?

I use the Vue https://github.com/insiders version because it's the only version that addresses this problem: https://github.com/tailwindlabs/headlessui/discussions/1205

That had this PR: https://github.com/tailwindlabs/headlessui/pull/2686

I've tried the latest version, 1.7.22, but although the bug from this issue is fixed, the options still won't open when clicked.

So, in the current scenario, I must choose between two bugs to stick with 🫠
