### ISSUE TITLE
Popover.js: Attempted import error: 'createContext' is not exported from 'react' (imported as 'Q').

### ISSUE THREAD

**Issue by webbertakken** [tailwindlabs/headlessui#3009] opened 2024-02-24 21:10 UTC
I was trying the https://tailwindui.com/templates/spotlight template to save some time. I copy pasted the configuration and dependencies from the template into a brand new nextjs project, with the same versions.

However I'm getting the following error when the template is using Popover.

```
./node_modules/@headlessui/react/dist/components/popover/popover.js
Attempted import error: 'createContext' is not exported from 'react' (imported as 'Q').
```

The moment I stop using this import, the error goes away: `import { Popover, Transition } from '@headlessui/react'` 

This issue seems to have been observed by a few more people before me. 

References: 
- https://github.com/tailwindlabs/headlessui/issues/2844
- https://stackoverflow.com/questions/73153159/components-importing-headlessui-throwing-errors-when-built-and-then-used-in-anot

What I've tried:
- Change browserlist to various different settings without avail.
- Try different configurations for Nextjs
- Upgrade / downgrade packages

Minimum reproducible example:
- https://github.com/webbertakken/deneuro.me/pull/3

Any ideas?

**Comment by yannic-wtfoxtrot** [comment] 2024-03-05 10:59
I got a similar error when importing components in next js server components that need client features (such as `useContext`). Is the component you are using this in a client component? If not, try using the `"use client"` directive at the top of the file.

**Comment by gamanc** [comment] 2024-03-06 08:17
> try using the `"use client"` directive at the top of the file.

 This saved my day, thank you!

**Comment by RobinMalfait** [comment] 2024-03-12 14:38
Hey!

This typically happens when you accidentally load multiple versions of React on the same page. This can be hard to debug if you don't really have control over which React versions are being used.

Reading the conversation, it looks like you figured out what the issue is, so I'm going to close this issue for now.

One small thing to mention: in the v2 alpha we made sure to add `"use client"` to all the components that require hooks that can only be used in client components. So hopefully in the future you shouldn't have to write `"use client"` anymore.

**Closed by RobinMalfait** 2024-03-12 14:38 UTC
