### ISSUE TITLE
Clicking combobox option with "immediate" prevents list from being open again

### ISSUE THREAD

**Issue by michaelgmcd** [tailwindlabs/headlessui#2840] opened 2023-11-16 19:56 UTC
Hello, love the combobox work, but my team ran into an issue with the "immediate" property.

Use case:
- `immediate` prop set to true on combobox
- User focuses the input and selects an item
- Combobox list is closed, but still focused (due to [this line](https://github.com/tailwindlabs/headlessui/blob/bfacb648dc5f45129eab53bc815bcee3001f0c9f/packages/%40headlessui-react/src/components/combobox/combobox.tsx#L1475C8-L1475C8))
- User clicks the combobox again, but the list does not open

Because it is in a focused state already, [the handleFocus callback](https://github.com/tailwindlabs/headlessui/blob/bfacb648dc5f45129eab53bc815bcee3001f0c9f/packages/%40headlessui-vue/src/components/combobox/combobox.ts#L1246) is not called, meaning the list doesn't reopen.

As a workaround, we've set a ref and blur the input manually after a selection.

**Comment by thecrypticace** [comment] 2023-12-07 16:49
Hey, so this behavior is not a bug.

In the combobox when selecting an item:
- Via the keyboard: the input stays focused at all times — so search ability is not impacted
- Via click/tap: the input briefly blurs because of how browsers handle click events so we re-focus it so you can continue searching, deleting from the input, etc…

This focusing behavior matches that of the [native HTML datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) — if you want to blur it after selecting you must do it yourself or just rely on your users to hit the `Tab` key.

And neither of these behaviors are affected by the `immediate` prop.  Now, the purpose of the `immediate` prop is to open the list when the combobox was _just_ focused by the user and wasn't already open. It's not intended to cause it to re-open after a selection otherwise you'd have a hard time closing it after re-selecting and might be nearly impossible to close it on mobile by tapping items but we also don't want to blur the input because the user still needs to be able to search.

I will note that clicks/taps *do* blur on mobile because constantly re-opening the virtual keyboard could get rather annoying to deal with. In an ideal world, we could detect if a hardware keyboard is in use and we'd still refocus the input but there's not yet a reliable, cross-browser signal on whether or not the virtual keyboard will actually show. One has been proposed but neither Safari nor Firefox implement it yet.

In your case I would go with the ref approach you've implemented given the way you intend for the combobox to work in your project.

**Closed by thecrypticace** 2023-12-07 16:49 UTC
