### ISSUE TITLE
Nested Dialog adds inert prop to every sibling of  #headless-ui-portal-root

### ISSUE THREAD

**Issue by masteryder** [tailwindlabs/headlessui#2413] opened 2023-04-03 16:08 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

 v1.7.13

**What browser are you using?**
Google Chrome - Version 106.0.5249.119 (Official Build) (arm64)

**Reproduction URL**

I don't have one for now

**Describe your issue**

When opening a Dialog nested inside another Dialog, all HTML elements that are next to headlessui-portal-root (children of body in my case) get the "inert" attribute added to them. This causes a lot trouble and causes some parts of my application to become unresponsive.

<img width="1092" alt="Screenshot 2023-04-03 at 18 05 21" src="https://user-images.githubusercontent.com/9080160/229565916-5bcef771-fb7a-4f21-aa94-8fcc51e4c353.png">

As you can see in this screenshot, the prop is present in every sibling

**Comment by RobinMalfait** [comment] 2023-04-03 18:05
Hey, thank you for this bug report! 🙏

This is 100% on purpose and is part of the accessibility features the Dialog component gives you. You can think of a dialog as a completely separate page that just happens to be rendered on the current one. This allows you to work in the current dialog without incorrectly touching other parts of the UI.

We add a bunch of features like that:
- Scroll locking, so that you don't accidentally scroll the page in the background
- Tab/focus locking so that you can tab around in the dialog and when you hit the end of the dialog you get redirected to the beginning
- Mark everything as inert

More info on the `inert` attribute itself: 
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert
> With the inert attribute, all of the element's flat tree descendants (such as modal [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog)s) that don't otherwise escape inertness are ignored.
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
> When implementing modal dialogs, everything other than the <dialog> and its contents should be rendered [inert](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) using the inert attribute. When using <dialog> along with the HTMLDialogElement.showModal() method, this behavior is provided by the browser.

So the more important question is, what does:
> This causes a lot trouble and causes some parts of my application to become unresponsive.

Mean in your case? Do you have any concrete examples?

Happy to help you if I understand your use case!

**Comment by masteryder** [comment] 2023-04-03 18:36
Thank you for your answer. 

Sorry I wasn't very clear, I can give you a concrete example. It is true that I can interact with simple components directly inside the nested Dialog. Inputs, buttons, etc.  However, in my case I sometimes have components in the nested Dialog that also use Portals to display their content. For example, a dropdown or a custom select. In those cases the inert prop will make the interaction with those components impossible.

I tried manually removing the "inert" prop from the container that serves as a portal to those components directly in the browser, and that restores the interaction.

Removing the portals or making them an optional prop from said components also would work but I feel that would cause issues in the long run.

Do you see a different solution?

**Comment by RobinMalfait** [comment] 2023-04-04 14:02
Hmm I see what you mean. We don't have control over other components sadly, but whenever another library uses a Portal, it is typically portalled to the root as a child of the `body`. We allow those containers, so if this is the case than it should work as-is.

If you control the Portal then you can do a few things:
- Make sure that the Portal is rendered inside the `Dialog.Panel`
- Or make sure that the Portal is rendered in the `body`
- Or you can import the `Portal` from Headless UI

If you don't control the Portal, then you can:
- Check where it is rendered. If it is in the `body` or `Dialog.Panel` then it should work
- Check if there is an option to change the location of the portal

If those things don't help you, then I would recommend to create a minimal reproduction repo so that we can take a look.

Hope this helps!

**Comment by jpizzle34** [comment] 2023-04-23 16:52
Hi all,

I am having a related issue after upgrading from v1.7.7 to v1.7.14 and just wanted to shed some light on it. The result was that my Dialogs were no longer able to be focused (they have form inputs on them). Here is my particular use case:
- Next.js app using a custom font with the `next/font` optimization component (and tailwindcss)
- Next.js Shared Layout
- Overriding the default `<div id='headlessui-root-portal' ... </div>` by defining my own as high as possible in the DOM tree. I did this as a workaround so that my font would be applied to text content inside the Dialog without it being refetched on every component mount (there was an external issue in production where the next.js optimized font was being refetched on every page navigation and when the dialog was re-mounted).

Here's a minimal reproduction:

**Working (by removing my custom headlessui-root-portal div and adding a font classname to every Dialog component)**
https://github.com/jpizzle34/debug--headlessui-dialog-cannot-focus
https://thriving-douhua-0f5d14.netlify.app

**Broken**
https://github.com/jpizzle34/debug--headlessui-dialog-cannot-focus/tree/not-working
https://not-working--thriving-douhua-0f5d14.netlify.app/

**Comment by RobinMalfait** [comment] 2023-04-25 19:12
Hey! Going to close this issue for now, if this is still an issue then I would recommend to open a new issue with a minimal reproduction repo or a CodeSandbox link attached.

---

@jpizzle34 I would recommend to not set your `headlessui-portal-root` because that means that it could end up in a place that we never tested and we can't guarantee the correct behaviour. 

For your font issue, I would recommend to set the required font (variables) on the `body` instead. That way the `Dialog` component can also use the imported fonts without you requiring to inject your own `headlessui-portal-root`. Checkout this comment with more information on how you can do that: https://github.com/tailwindlabs/headlessui/issues/2189#issuecomment-1385379554

**Closed by RobinMalfait** 2023-04-25 19:12 UTC
