### ISSUE TITLE
[Bug]: Popover doesn't close on first click in Safari / Firefox / Chrome

### ISSUE THREAD

**Issue by sherakama** [tailwindlabs/headlessui#650] opened 2021-06-30 05:01 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.3.0

### What browser are you using?

Safari (OSX), FireFox (OSX), Chrome (OSX)

### Reproduction repository

https://headlessui.dev/react/popover

### Describe your issue

On Safari, Firefox, and Chrome, you'll have to click twice to close the popover on the first page load. No issues with using keyboard controls to open/close, or clicking outside to close.

Video: https://share.getcloudapp.com/mXur2lq4

**Comment by yvonnetangsu** [comment] 2021-06-30 05:33
I experienced the same thing in my own project. Also, in Safari and Firefox, after I click to open a popover panel, if I repeat the "click and hold" motion on the popover button, then I can never close the panel. Please see below video.

https://share.getcloudapp.com/nOuPb0K9

**Comment by yvonnetangsu** [comment] 2021-07-07 22:01
Just noticed that I can reproduce this in Chrome also using the demo on the HeadlessUI site:
https://share.getcloudapp.com/wbu6BLG9

Using: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by sherakama** [comment] 2021-07-07 22:44
Can confirm this is also happening for me.

**Comment by marcobusemann** [comment] 2022-03-04 08:57
Did you find a workaround for this?

**Comment by sherakama** [comment] 2022-03-04 17:28
Unfortunately, we did not. We ended up abandoning the component and went in a different direction.

**Comment by RobinMalfait** [comment] 2022-03-10 23:46
Hey! Thank you for your bug report!
Much appreciated! 🙏

Would love to solve this issue but I can't reproduce it, can somebody share a reproduction CodeSandbox or a minimal reproduction repo if you have this issue? Thanks!

The Headless UI docs themselves are a bit of a tricky example, because it happens there for another reason. Those examples are executed in an iframe and we want to restore the focus when the iframe steals the focus.

**Comment by sherakama** [comment] 2022-03-12 00:05
> The Headless UI docs themselves are a bit of a tricky example, because it happens there for another reason. Those examples are executed in an iframe and we want to restore the focus when the iframe steals the focus.

I can still reproduce it on the documentation website at: https://headlessui.dev/react/popover

But if I go directly to the iframe source I no longer see the error: https://headlessui.dev/examples/react-popover-hero

Perhaps you can elaborate on what you are doing on the iframe focus so that others that read this ticket can benefit from avoiding the same mistake. 

> Would love to solve this issue but I can't reproduce it, can somebody share a reproduction CodeSandbox or a minimal reproduction repo if you have this issue? Thanks!

Unfortunately, we no longer have any working examples.

**Comment by marcobusemann** [comment] 2022-03-14 09:00
Have created a small example here: https://codesandbox.io/s/headless-ui-popover-double-tab-issue-mobile-m6fq2x
With that link I can reproduce it on my iPhone SE 2020. 
The important part in this example is the `tabIndex={-1}` on the div-element that wraps everything. We are using Gatsby which has this on his root element.

**Comment by syahzuan** [comment] 2022-07-07 10:07
Experiencing the same problem where I can only open or close Popover with double click on Firefox. It was initially OK; I was working on the page so there was a lot of refreshes and changing responsive design sizes, and out of a sudden the Popover stopped working on single clicks. Refresh or hard refresh don't solve it.
If I open a private/incognito window also on Firefox, single clicks work fine again.

**Comment by faessler** [comment] 2022-07-14 11:20
@sherakama [RobinMalfait](https://github.com/RobinMalfait) seems to be fixed with the latest version?

**Comment by sherakama** [comment] 2022-08-03 00:06
I am unable to reproduce today.

**Comment by RobinMalfait** [comment] 2022-08-08 08:35
Hey all!

I also can't reproduce this anymore so going to close this one. If you are experiencing more issues, please create a new issue with a reproduction repository / CodeSandboxed attached so that we can take a look.

@marcobusemann looks like your issue is a different issue, but bumping `@headlessui/react` to the latest version also fixes that. https://codesandbox.io/s/headless-ui-popover-double-tab-issue-mobile-forked-ccf8hn

**Closed by RobinMalfait** 2022-08-08 08:35 UTC
Labels: Needs more info
