### ISSUE TITLE
[BUG]  Auto close popover when switching windows.

### ISSUE THREAD

**Issue by BernardoLima-dev** [tailwindlabs/headlessui#1475] opened 2022-05-19 13:34 UTC
**What package within Headless UI are you using?**

 @headlessui/react 

**What version of that package are you using?**

 v1.6.1

**What browser are you using?**

Chrome(but test in Mozilla Firefox, Microsoft Edge)

**Reproduction URL**

...

**Describe your issue**

When opening the popover with the items inside, it may close when changing tabs, or clicking on the url, something outside the page. that is, in my case, I'm using this lib for a feedback feature, so if a person is writing their problem in the feedback, they change tabs to search for something, and go back to try to write the feedback again, it closes automatically.

**Comment by RobinMalfait** [comment] 2022-05-19 14:04
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

---

Fwiw, I can't reproduce this behaviour on our demo playground: https://headlessui-react-72mwo0eec-tailwindlabs.vercel.app/popover/popover

**Closed as completed by RobinMalfait** 2022-05-19 14:04 UTC
