### ISSUE TITLE
[Bug]: Dialog complains of missing open prop even with a TransitionRoot show prop being present.

### ISSUE THREAD

**Issue by leggettc18** [tailwindlabs/headlessui#521] opened 2021-05-13 23:16 UTC
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/leggettc18/devmarks-frontend-web/tree/tailwind

### Describe your issue

The Documentation states that I can safely remove the `open` prop from the Dialog when I have a `show` prop on a TransitionRoot right above it.

> To animate the opening/closing of your dialog, use the provided TransitionRoot component from Headless UI (rather than Vue's build-in <transition> component). You can then add the isOpen prop to the TransitionRoot's show prop, and safely remove the open prop from the Dialog component.

However, when I do this, the modal does not work, and my browser complains about the open prop being missing. I've fixed this temporarily by adding an `:open="true"` to the dialog, but this doesn't feel correct, or at least the documentation should be changed to reflect it if it is.

```typescript
<TransitionRoot appear :show="dialogVisible" as="template">
      <Dialog
        as="div"
        :open="true"
        class="fixed inset-0 z-10 overflow-y-auto"
        @close="closeDialog()"
      >
...
```

**Comment by RobinMalfait** [comment] 2021-05-13 23:27
Hey! Thank you for your question!
Much appreciated! 🙏

This is a new feature introduced in Headless UI version 1.2.0 (https://github.com/tailwindlabs/headlessui/releases)
I see that you mention that you use version 1.2.0, however your reproduction repo does not:

- https://github.com/leggettc18/devmarks-frontend-web/blob/tailwind/package.json#L13
- https://github.com/leggettc18/devmarks-frontend-web/blob/tailwind/yarn.lock#L1398 

Can you try and bump them (`yarn add @headlessui/vue@latest`)?

**Comment by leggettc18** [comment] 2021-05-13 23:38
Oh wow, I had run `yarn info @headlessui/vue version`, but I guess that just checks the latest version rather than running against my local environment. Thanks that fixed it. Although I do still get the following warning:

```
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Invalid prop: type check failed for prop "open". Expected Boolean, got String with value "DC8F892D-2EBD-447C-A4C8-A03058436FF4". 
  at <Dialog as="div" class="fixed inset-0 z-10 overflow-y-auto" onClose=fn  ... > 
  at <Anonymous unmount=true as="template" enter=""  ... > 
  at <TransitionRoot appear="" show=false as="template" > 
  at <Bookmarks onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <App>
```

Not sure if that's expected or not, not a huge deal.

**Comment by RobinMalfait** [comment] 2021-05-14 10:25
Glad it worked out!

You can safely ignore that warning, we will improve it but it is not actually an issue.
A bit more info why this is happening: I wanted to validate that an `open` prop was passed in certain scenarios. However when you have something like `{ props: { open: Boolean, default: null } }`, then it will still resolve to `open === false`. So to prevent this I defaulted to a "symbol" (in this case a hardcoded uuid), just to prevent the automatic value conversion.

Going to close this issue, since your main issue seems to be resolved.

**Closed by RobinMalfait** 2021-05-14 10:25 UTC

**Comment by leggettc18** [comment] 2021-05-14 22:27
OK that's fine, just wanted to make sure that wasn't on my end. Thanks for the help.
