### ISSUE TITLE
Error with Popovers – Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by wottpal** [tailwindlabs/headlessui#2115] opened 2022-12-21 07:09 UTC
Hey there, I'm using latest tailwindcss & headlessui. I've just implemented the first responsive header example of TailwindUI (https://tailwindui.com/components/marketing/elements/headers). It also works just fine, but whenever I open the responsive mobile menu popover and then enlarge the screen (so that it gets hidden), it throws the following error:

```
TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
```

<img width="736" alt="Screenshot 2022-12-21 at 08 09 04" src="https://user-images.githubusercontent.com/3930150/208842659-91b48b71-9aec-4e48-b6cf-d65d132cf510.png">

**Comment by RobinMalfait** [comment] 2023-01-04 15:45
Hey! Thank you for your bug report!
Much appreciated! 🙏

I can't seem to reproduce this. Can you create a minimal reproduction repo and attach it to the issue so that we can take a look?

**Comment by paustint** [comment] 2023-01-18 00:15
I have been hitting this issue once in a while as well - I had a bout 17 rollbar uncaught exceptions in the past few days from users and I am having a hard time reproducing it.

I notice it comes up when I am working with playwright and writing e2e tests and make code changes but have not hit it myself otherwise, I just now noticed that it is impacting production users.

I will keep trying to reproduce it and report back if I find something.
I am on version
`"@headlessui/react": "^1.7.4",`

**Comment by paustint** [comment] 2023-01-19 01:41
I am able to reproduce.
I found a random stackblitz in this repo where I opened it and immediately experiences the issue: https://codesandbox.io/s/busy-rgb-r7boos?file=/src/App.tsx

Here is a video showing the reproduction: https://jam.dev/c/fb7d982b-4f93-4c36-8cbe-cd5f01331886

The error stacktrace in my code base led to this:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/5461649/213335579-f7dc523c-4c9e-44e4-9f39-cb206dbe708d.png">

**Comment by paustint** [comment] 2023-01-19 01:53
Looks like I should have just tried upgrading, after looking through release notes I found a PR that looked promising and sure enough it appears to have fixed the problem.

https://github.com/tailwindlabs/headlessui/pull/2019

**Comment by RobinMalfait** [comment] 2023-01-20 13:06
Thanks for providing a reproduction @paustint, and I'm happy that bumping to the latest version fixes the issue.

Going to close this issue for now since I think it is fixed with the linked PR. If you @wottpal, (or anyone else) still runs into this issue please make sure to:
- Bump to the latest version
- Open a new issue with a minimal reproduction repo attached so that we can take a look

**Closed by RobinMalfait** 2023-01-20 13:06 UTC
Labels: Needs more info

**Comment by paustint** [comment] 2023-01-22 16:05
@RobinMalfait - Looks like I am still hitting this issue in some cases, I will try to get a repro example if I can and open a new issue.
