### ISSUE TITLE
[Bug]: Modal closes automatically with Next.JS

### ISSUE THREAD

**Issue by TheAsda** [tailwindlabs/headlessui#479] opened 2021-05-04 22:20 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.1.1

### What browser are you using?

Chrome 90

### Reproduction repository

https://codesandbox.io/s/headless-ui-next-issue-l17wk?file=/pages/page2.js

### Describe your issue

Basic setup: there are two pages, each page has a modal. So modals should be independent from pages. But if you open and close modal on `page1`  then switch to `page2` and click on `Open dialog` button, `onClose` is called for whatever reason right after modal opens. You can see this in console.
Firstly, i thought that `initialFocus` that is pointing to cancel button is pressed on open. But that's not the case here. `closeModal` is called from `onClose` prop.

**Comment by dungkaka** [comment] 2021-05-07 02:39
Same problem! Even inside onClose, I do not change state of modal, modal is still not show.

**Comment by andrewli-ca** [comment] 2021-05-07 20:25
Somewhat related issue where I'm trying to render a `Dialog` on one page(ie. page1) and another `Dialog` on another page(ie. page2).

Opening the `Dialog` works fine on page1. However, when navigating from page 1 to page2, the `Dialog` fails to open on this page. It seems the cause of this problem is the `headlessui-portal-root` element is missing from the DOM which is why the `Dialog` cannot open.

When navigating back from page2 to page1, the `headlessui-portal-root` element shows up again.

I'm not sure why this is happening, would love to have an explanation.

Here's a GIF of the issue using @TheAsda 's sandbox:

![headlessui-portal](https://user-images.githubusercontent.com/9060674/117504017-abc76b80-af36-11eb-81ef-1a148153d1c4.gif)

**Comment by TheAsda** [comment] 2021-05-18 21:17
> Did someone find a workaround to this?

For now I did not manage to find a way fix this.

**Comment by mtergel** [comment] 2021-05-22 07:02
I downgraded my next version to "10.1.2". And it worked.

**Comment by evangeline** [comment] 2021-06-10 07:44
I have noticed this in CRA as well, when I am using `<Portal>` from headless ui to render other kinds of components like Listbox.

**Comment by exponent42** [comment] 2021-08-07 13:31
Experiencing the same issue with `headlessui-portal-root`

**Comment by exponent42** [comment] 2021-08-07 13:51
SSR playing trickery here. This hook solved it for me:

```javascript
// useHasMounted.ts

export default function useIsMounted() {
  const [isMounted, setIsMounted] = React.useState(false);
  React.useEffect(() => {
    setIsMounted(true);
  }, []);
  return isMounted;
}
```

Use it like so

```javascript
// page.tsx (NextJS)

import useIsMounted from '@hooks/useIsMounted'

 const isMounted = useIsMounted()

  if (!isMounted) {
    return null
  }

```

**Comment by travis** [comment] 2021-11-07 16:21
Wow, just spent a while trying to figure out what I was doing wrong - seeing the same behavior, where the dialog doesn't work after I navigate to a second page. I don't understand how @exponent42's hook is supposed to be used to solve this - has anyone found workarounds for this issue?

**Comment by RobinMalfait** [comment] 2022-02-21 16:34
Hey! Thank you for your bug report!
Much appreciated! 🙏

This bug should be fixed and is available in the newest version of Headless UI. Here is an updated codesandbox with the latest version: https://codesandbox.io/s/headless-ui-next-issue-forked-jp70dj

**Closed by RobinMalfait** 2022-02-21 16:34 UTC
