### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by polgiron** [tailwindlabs/headlessui#2345] opened 2023-03-08 14:19 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.13

**What browser are you using?**

Chrome, Safari

**Describe your issue**

I've just updated to the latest version v1.7.13 and just with the basic example at the top of the page https://headlessui.com/react/dialog I'm getting a react warning "Can't perform a React state update on an unmounted component"

<img width="572" alt="Screenshot 2023-03-08 at 15 16 51" src="https://user-images.githubusercontent.com/8901804/223736906-1e1023dc-3a3b-4b96-9f46-4926c7f13193.png">

**Comment by thecrypticace** [comment] 2023-03-08 16:40
Hey, thank you for this bug report! 🙏

I took the basic example from the docs and created both a Next.js project and Vite project with React 18 and am not seeing this behavior. I also created one using a transition (as that component also appears in your stack trace) and do not see this behavior there either. As a reproduction was not provided I'm going to close this issue as there's not enough information for us to go on to create one.

If you could provide:
- a minimal reproduction as a github repository
- The browser + version you are using
- The version of React you are using
- What OS you are testing on (unlikely to be relevant here but it is still occasionally useful)

Then I'll definitely re-open this and take another look (if you could @-mention me it'll get to me **much** quicker). Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Closed by thecrypticace** 2023-03-08 16:40 UTC

**Comment by jamesmacwilliam** [comment] 2023-03-09 13:07
this code copied from the https://headlessui.com/react/dialog does trigger the error above when the dialog is closed, the basic example works but this one does not and it is the first example on the page:

```
import { Dialog, Transition } from '@headlessui/react'
import { Fragment, useState } from 'react'

export default function MyModal() {
  let [isOpen, setIsOpen] = useState(true)

  function closeModal() {
    setIsOpen(false)
  }

  function openModal() {
    setIsOpen(true)
  }

  return (
    <>
      <div className="fixed inset-0 flex items-center justify-center">
        <button
          type="button"
          onClick={openModal}
          className="rounded-md bg-black bg-opacity-20 px-4 py-2 text-sm font-medium text-white hover:bg-opacity-30 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75"
        >
          Open dialog
        </button>
      </div>

      <Transition appear show={isOpen} as={Fragment}>
        <Dialog as="div" className="relative z-10" onClose={closeModal}>
          <Transition.Child
            as={Fragment}
            enter="ease-out duration-300"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="ease-in duration-200"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <div className="fixed inset-0 bg-black bg-opacity-25" />
          </Transition.Child>

          <div className="fixed inset-0 overflow-y-auto">
            <div className="flex min-h-full items-center justify-center p-4 text-center">
              <Transition.Child
                as={Fragment}
                enter="ease-out duration-300"
                enterFrom="opacity-0 scale-95"
                enterTo="opacity-100 scale-100"
                leave="ease-in duration-200"
                leaveFrom="opacity-100 scale-100"
                leaveTo="opacity-0 scale-95"
              >
                <Dialog.Panel className="w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all">
                  <Dialog.Title
                    as="h3"
                    className="text-lg font-medium leading-6 text-gray-900"
                  >
                    Payment successful
                  </Dialog.Title>
                  <div className="mt-2">
                    <p className="text-sm text-gray-500">
                      Your payment has been successfully submitted. We’ve sent
                      you an email with all of the details of your order.
                    </p>
                  </div>

                  <div className="mt-4">
                    <button
                      type="button"
                      className="inline-flex justify-center rounded-md border border-transparent bg-blue-100 px-4 py-2 text-sm font-medium text-blue-900 hover:bg-blue-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"
                      onClick={closeModal}
                    >
                      Got it, thanks!
                    </button>
                  </div>
                </Dialog.Panel>
              </Transition.Child>
            </div>
          </div>
        </Dialog>
      </Transition>
    </>
  )
}
```

**Comment by fahmij8** [comment] 2023-03-13 15:58
I can confirm that this also happened to me, not blocking users but kinda annoying to have the error. any updates on this one?

**Comment by fahmij8** [comment] 2023-03-13 16:14
Hey, I just found out the root cause of this issue. 

You see, as stated by @jamesmacwilliam that first example code is having this kind of error while the basic example are not.
After comparing, I found that the first example code doesn't have the `open` attribute on the `<Dialog>` tag. If you add that attribute, this _hard to trace error_ will disappear ✨

**Comment by polgiron** [comment] 2023-03-13 16:19
I think if you follow the Transition example https://headlessui.com/react/dialog#transitions there is no `open` props on the Dialog, it's handled by the Transition wrapper

**Comment by polgiron** [comment] 2023-03-23 09:09
hey @thecrypticace, I've tried to make a minimal reproduction as a github repository and everything was fine - for others coming here, the error disappeared when I upgraded react to v18. Thanks.
