### ISSUE TITLE
[Bug]: Listbox compatibility with Safari browser

### ISSUE THREAD

**Issue by ahmed-abdelhamid** [tailwindlabs/headlessui#724] opened 2021-08-09 09:59 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.4.0

### What browser are you using?

Chrome, Safari

### Reproduction repository

https://codesandbox.io/s/tailwind-example-j31f6

### Describe your issue

I have a form that has a text input and 2 (Listbox components), I always use my keyboard in navigating the form. In chrome when the browser is focused on the text input then I press (Tab), the focus changes to the Listbox and this is the behavior I need, but with Safari this is not the case and the focus never goes to the (Listbox). I do not know if this is a bug or this behavior is expected because of compatibility issues with Safari.

**Comment by RobinMalfait** [comment] 2021-08-23 13:19
Hey! Thank you for your bug report!
Much appreciated! 🙏

Is this issue still happening? If so, can you also share the Safari version you are using?

I'm currently on: Version 14.1 (16611.1.21.161.6)
I can't reproduce it with this version.

https://user-images.githubusercontent.com/1834413/130454025-246bc90f-65db-40b2-8937-be1f7ffd8594.mov

**Comment by ahmed-abdelhamid** [comment] 2021-08-23 13:46
@RobinMalfait

Unfortunately, yes. I am still suffering from that issue.
Safari version that I use is: Version 14.1.2 (16611.3.10.1.6)

**Comment by RobinMalfait** [comment] 2021-09-12 18:18
Hey!

I still can't reproduce this with the shared codesandbox. If you can provide more info on how to reproduce it that would be nice. Do you have any browser extensions that could be the bottleneck (can you disable them all and try again)? Are you able to reproduce this on another machine? 

The `Listbox.Button` is a normal `button` under the hood, so I can't think of any reason why this wouldn't focus in your case.

Going to close it for now, is this is still an issue for you then I would recommend you to open a new issue and provide as much information as possible to reproduce this behaviour.

**Closed by RobinMalfait** 2021-09-12 18:18 UTC
Labels: Needs more info

**Comment by oaleynik** [comment] 2022-08-09 11:59
@RobinMalfait @ahmed-abdelhamid faced the same issue with Safari 15.6. Found a few workarounds:

1. Use <Options + Tab>
2. Turn on Safari > Preferences > Advanced > Press Tab to highlight each item on a web page
3. Render <ListboxButton> component as anchor element with zero tabindex by setting `as="a" tabindex="0" role="button"`

Note: even on https://headlessui.com/vue/listbox while using Safari I can't cycle through elements on the page. In chrome the tabbing works as it was historically.

**Comment by briavicenti** [comment] 2025-08-11 18:30
@RobinMalfait this is an outstanding issue on Safari - I am unable to focus the demo `Listbox` via tabbing on the current [HeadlessUI React documentation](https://headlessui.com/react/listbox) and Safari 18.5. Can we please reopen this issue?
