### ISSUE TITLE
Content behind Dialog flickers when horizontally scrollable

### ISSUE THREAD

**Issue by agcty** [tailwindlabs/headlessui#2309] opened 2023-02-25 14:47 UTC
Opening a new issue because the previous one that tracked this issue was closed: https://github.com/tailwindlabs/headlessui/issues/963

Version: 1.7.12

**What browser are you using?**

Issue only happens on iOS Safari as far as I'm aware. Used 16.3.1 to test.

**Reproduction URL**

https://github.com/agcty/my-remix-app

**Describe your issue**

When using the Dialog component, in some cases the content behind it will flicker.

Reproduction steps:

1) More content than the screen's height
2) horizontally scrollable content using overflow-x-scroll or overflow-x-auto

Flickering should appear only on horizontally scrollable content.

https://user-images.githubusercontent.com/12101091/221363109-22c02a63-927e-4946-acc8-857d365670e3.MP4

**Comment by agcty** [comment] 2023-02-25 14:52
I don't know exactly what it is that causes the flicker but the content in the Dialog doesn't seem to matter, in fact you can remove everything within the Dialog and just use a plain Dialog component and it will still flicker.

**Comment by agcty** [comment] 2023-02-25 14:58
Another finding: removing all of the transitions still leaves the content flickering, really seems to be just the Dialog component that causes the flickering.

**Comment by thecrypticace** [comment] 2023-02-27 15:10
Here's a frame-by-frame slow down of the "important" bits of the entrance and exit from the video above:

https://user-images.githubusercontent.com/614993/221600693-c8e97e76-4785-455a-9e2e-2826ea88cc55.mov

It looks as if Safari is not drawing entire sections of the document but not sure why.

**Comment by thecrypticace** [comment] 2023-02-27 15:23
Note: I can reproduce this in the simulator on iOS 15 and iOS 16 on different simulated devices.

**Comment by agcty** [comment] 2023-02-27 15:56
Thanks for reproducing @thecrypticace! Seems really weird that entire sections aren't drawn, could this be a webkit bug? Really not sure what might be the cause of this though.

**Comment by thecrypticace** [comment] 2023-02-27 19:08
Another followup here:
1. I tested in Chrome (which is obvs, for now, still WebKit-based on iOS) and the issue exists there also.
2. The issue is _not_ reproducible on Desktop Safari even after forcefully enabling the iOS-specific code that's being called
3. I also set up a Vite project so I could test React Spectrum / Aria which uses a similar approach and the issue exists there as well.
4. I have been unable to get the flicker to show in the timeline recording feature in Safari. Even if it flickers on screen the screenshots do not show a flicker. This to meet feels like a repainting issue when communicating with the GPU or something. Maybe it's not invalidating the right rectangles when drawing. But it's also not recording every individual frame so this may not be evidence of anything useful.

All in all, I feel like this is a WebKit bug. I'm going to spend a bit of time fiddling with stuff to get this down to a much simpler "does-not-use-react-at-all" reproduction that I can file.

**Comment by thecrypticace** [comment] 2023-02-28 15:43
@RobinMalfait and I did some investigating this morning. The gist of the issue is:

1. When the content is scrollable it gets placed on a GPU layer — and flickers as you've seen.
2. If you remove the scroll container but add `transform:translate3d(0,0,0)` as a style property it will also flicker because this forces the element onto a GPU layer.
3. For some reason, if you remove the wrapping anchor tag the flickering seems to disappear — I have no idea why this changes anything. It shouldn't imo. Buttons also exhibit the flickering behavior.

My guess is there is a delay in uploading the right layers to the GPU which results in the flicker — so definitely a WebKit bug and it's somehow only triggered when the body is scrolled or given a margin top.

The only real "workaround" is placing your app in a scrolling. container that is basically `h-screen` (on iOS it's a little more complicated because viewport units work weirdly there (I recommend testing `100svh` / `100dvh` / `100lvh` for heights). This way the body itself never scrolls. This has limitations — like Headless UI does not prevent the scrolling of these containers. It would also possibly cause issues when using `#fragments` in urls, scroll to top, or any other things that assume the viewport is scrolling.

**Comment by agcty** [comment] 2023-02-28 16:13
Thanks for the detailed insights! Another workaround that works is (unfortunately) not using headlessui and its Dialog component at all. I was able to come up with a reasonable approach that doesn't need headlessui at all, instead I now use a few hooks from usehooks-ts to copy the Dialog behaviour. It's not perfect but it works reasonably well.

Looks somewhat like this:
```jsx
import { useLockedBody, useMediaQuery, useOnClickOutside } from "usehooks-ts"

function MobileCart() {
  const snap = useSnapshot(cart);
  const open = snap.open;
  const cartSnap = useSnapshot(cart);

  const ref = useRef<HTMLDivElement>(null);
  useOnClickOutside(ref, closeCart);
  useLockedBody(open, "root");

  const totalPrice = cartSnap.packs.reduce((acc, item) => acc + item.price, 0);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ transition: { duration: 0.15 }, opacity: 0 }}
      className={clsx(
        "fixed inset-0 border-gray-300 shadow-lg z-50",
        className
      )}
    >
      <motion.div
        className="fixed inset-0 z-10 bg-black/30"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ transition: { duration: 0.15 }, opacity: 0 }}
      />
    </motion.div>
  );
}
```

I do not know however why this works without a flicker, not too familiar with the inner workings of the Dialog component but one difference between this custom solution and Dialog is that the custom one doesn't set the inert attribute. But it could also be anything else.

**Comment by thecrypticace** [comment] 2023-02-28 17:27
Yeah, the thing that triggers the bug is that Headless UI is performing extra steps to prevent scrolling on iOS. Specifically, it set's a margin on the HTML element and scrolls the document to the top. This doesn't result in any visual shift but is required to trick Safari on iOS into preventing the scroll as an `overflow: hidden` is, unfortunately, not enough to prevent scrolling there.

**Comment by thecrypticace** [comment] 2023-03-01 18:35
I have filed a bug [on the WebKit bug tracker](https://bugs.webkit.org/show_bug.cgi?id=253171) with a minimized reproduction to track this. Seeing as this is a WebKit bug there's not much for us to do here given that the thing that triggers it is _also_ the only way to prevent scrolling on iOS. Going to close this one and I'll keep an eye on the bug on WebKit's bug tracker.

If we come up with a workaround then I'll be sure to comment on this issue.

**Comment by bryantcodesart** [comment] 2023-03-10 07:57
@thecrypticace Is there any way to easily opt out of this scroll locking behavior without forking the package?  E.g. via the API?

Best I can figure there is NOT a simple opt out, but wanted to double check before I just fork the package and try to pull that functionality out selectively on ios!  (I kinda suspect this is not a feature you'd want in the main package otherwise I'd offer to contribute...)

Replacing the body scroll with a scrolling div is a very high cost in my current project (which has many scroll behaviors/anims and lots of window scroll event listeners that this would break).  And my clients will definitely comment on the flicker.  (They are all boutique designers.). 

But I also love Headless UI too much to give it up without a fight! :)

I have a want to be more proactive than waiting for a webkit fix, because even when they DO fix it, itll take some time for that fix to proliferate to users. (I still routinely run into users a few major versions behind on iOS!)

**Comment by thecrypticace** [comment] 2023-03-10 15:38
@bryantcodesart We don't have a workaround for this right now and generally we don't want a toggle for fairly important behavior. Especially given that the bug is localized to a single platform under specific conditions.

We're gonna take another look at this soon-ish but in the meantime you could patch Headless UI for your use case. You can do this using the `patch-package` npm package or, if you're using Yarn v2+ or pnpm, you can use their native patching support.

Basically you'll want to target this file and change the `if (!isIOS())` check to `if (true)`
https://github.com/tailwindlabs/headlessui/blob/9a7dcfc76d9d3c748dc75f83e398d0ab5d36e0fc/packages/%40headlessui-react/src/hooks/document-overflow/handle-ios-locking.ts#L9-L11


The patch could look something like this: https://gist.github.com/thecrypticace/fe46b78bdc364711e605f0497942f703

I've opted to leave out the minified / prod CJS file because it's one file with all of Headless UI but the relevant snippet there currently looks like this: `if(!Jt())return{};`

**Comment by bryantcodesart** [comment] 2023-03-10 16:23
Yoooo this is outstanding advice.  Thank you!  I was headed down a dumber road than this and you just saved me an afternoon.

And it makes total sense why you wouldn't want this in your library.  Letting desperate devs on deadline selectively opt out of accessibility features feels like a slippery slope--and energy that could be better spent elsewhere.

I do feel like this is an urgent enough issue that it deserves some documentation of some kind--who among us doesn't ultimately require flawless execution on ios--one platform as it may be.  But again I recognize why it won't and shouldn't be a priority.

Maybe the right middleground is for me to just report back here how your solutions works as soon as I have the space to try it and add any additional thoughts/notes/changes I required to get things off the ground.

**Comment by thecrypticace** [comment] 2023-03-21 16:59
@bryantcodesart Any chance you have an update on how the patch idea went?

**Comment by bryantcodesart** [comment] 2023-03-24 00:00
@thecrypticace Sorry for the delay.  Just got to the project phase where I could try this.  The below is half a verification report and half notes for future friends with this issue!

- I used `patch-package` (First timer--but the docs led me well.  Although I will note there are some yarn-specific notes.)
- I replicated your exact patch.
- I don't see the flicker! Yay! And I saw the testing console.logs I added to the patch to verify it was actually being applied.
- I was able to deploy to Vercel (although I had to avoid building from previous caches.)

I will confess I didn't understand why I was patching _both_ files listed--simply because I'm not an experienced node package author and don't know the anatomy of a typical package.  It's probably obvious to others.  It may be equally obvious to others that the `/node_modules/@headlessui/react/dist/hooks/document-overflow/handle-ios-locking.js` file was the one that generated console logs and (apparently) the fix when I was on testing on my Vercel staging environment.  Anyway I'm curious about that, but what's important is...

THIS WORKED FOR ME!

THANK YOU THANK YOU!

For real, I love Headless UI so much and I was worried I would have to reinvent the wheel instead of using your amazing project!  Cheers to your work! 😄

**Comment by thecrypticace** [comment] 2023-03-24 01:35
Yesssss! So happy to hear that! 🥳🥳 

I suggested patching both files purely because I wasn't aware what files your setup would end up using. Some setups will load the CJS version and some will load the ESM version. This was the easiest way to cover all the bases in hopes that the solution would work.

Good news — you should only need to patch the one file for your project!

> For real, I love Headless UI so much and I was worried I would have to reinvent the wheel instead of using your amazing project! Cheers to your work! 😄

❤️❤️❤️ 

Gonna close this again now that you've got a workable solution :)

**Closed by thecrypticace** 2023-03-24 01:35 UTC
