### ISSUE TITLE
Opacity of Dialog.Overaly after transition

### ISSUE THREAD

**Issue by cding91** [tailwindlabs/headlessui#374] opened 2021-04-16 03:24 UTC
### What package within Headless UI are you using?

headlessui/react

### What version of that package are you using?

1.0.0

### What browser are you using?

Chromium Edge

### Reproduction repository

https://github.com/cding91/IssueReproduce

### Description

I grabbed the example code for Dialog. The example code uses transition on the opacity of the overlay. I intend to make use opacity-50 for the final looks of the overlay. I hope overlay's opacity can transition from 0 to 50. What it did is shown in the code snippet below. 

But it seems the overlay's opacity changes from 0 to 50 then flashes to 100 (see the image). Is this the right behavior that I should expect? Is there something that I should or should not do to get the right transition? Thank you.

```
  <Transition.Child 
    as={Fragment}
    enter="transition duration-500"
    enterFrom="opacity-0"
    enterTo="opacity-50"
    leave="transition duraiton-500"
    leaveFrom="opacity-50"
    leaveTo="opacity-0"
  >
    <Dialog.Overlay className="fixed inset-0 opacity-50 bg-gray-500" />
  </Transition.Child>
```

![image](https://user-images.githubusercontent.com/43915456/114967549-a9e02000-9e42-11eb-8e1e-1820f980cc8d.png)

**Comment by mattellig** [comment] 2021-04-17 05:35
I was having the same/similar issue. Something like this worked for me:

`<Transition.Child
    as={Fragment}
    enter="ease-out duration-500"
    enterFrom="opacity-0"
    enterTo="opacity-100"
    leave="ease-in duration-500"
    leaveFrom="opacity-100"
    leaveTo="opacity-0"
>
    <Dialog.Overlay className="fixed inset-0 bg-gray-500 bg-opacity-50 transition-opacity" />
</Transition.Child>`

Specify the desired opacity with a bg-opacity utility on the overlay itself. Animates nicely and has the desired effect.

**Comment by cding91** [comment] 2021-04-17 15:20
> I was having the same/similar issue. Something like this worked for me:
> 
> ```
> <Transition.Child
>     as={Fragment}
>     enter="ease-out duration-500"
>     enterFrom="opacity-0"
>     enterTo="opacity-100"
>     leave="ease-in duration-500"
>     leaveFrom="opacity-100"
>     leaveTo="opacity-0"
> >
>     <Dialog.Overlay className="fixed inset-0 bg-gray-500 bg-opacity-50 transition-opacity" />
> </Transition.Child>
> ```
> 
> Specify the desired opacity with a bg-opacity utility on the overlay itself. Animates nicely and has the desired effect.

It works! Thanks. 

Wonder if this is what I am supposed to be doing...

**Comment by hugotiger** [comment] 2021-04-17 19:36
Hey!

I had the same issue and just wanted to note that I seem to have found the cause of the issue. When you set a opacity on the `<Dialog.Overlay>` it seems to override the opacity set by the `<Transition.Child>`-component.

One solution is doing as @mattellig suggested. Although setting `transition-opacity` is not needed. Either that or add a semi-transparent color value to your `tailwind.config.js` and use that color instead. 

I don't know if this is intended behaviour or not 🤔

Best regards,
Hugo

**Comment by adamwathan** [comment] 2021-04-17 19:51
Hey! The issue here is the `opacity-50` class that is sitting on the overlay element permanently:

<img width="572" alt="Screen Shot 2021-04-17 at 3 46 44 PM" src="https://user-images.githubusercontent.com/4323180/115125125-246c8500-9f94-11eb-87db-12c8851dfa0f.png">

The way the transition component works, it adds the `enter` classes to the element at the beginning of the transition, meaning the element has these classes at first:

```
<Dialog.Overlay className="fixed inset-0 opacity-50 bg-gray-500 transition duration-500 opacity-0" />
```

Notice how both `opacity-50` and `opacity-0` are on the element at the same time. This is a conflict, and whichever one appears later in the CSS file happens to win, in this case `opacity-50` so `opacity-0` is never applied.

The solution in general it to avoid conflicting classes being on an element at the same time. Using `bg-opacity-50` for the overlay is a great way to do that, another approach is to just use two separate elements, where the inner element is the actual 50% transparent overlay, and the outer element transitions from 0 to 100 opacity:

```
  <Transition.Child 
    as={Fragment}
    enter="transition duration-500"
    enterFrom="opacity-0"
    enterTo="opacity-100"
    leave="transition duraiton-500"
    leaveFrom="opacity-100"
    leaveTo="opacity-0"
  >
    <Dialog.Overlay className="fixed inset-0">
      <div className="absolute inset-0 opacity-50 bg-gray-500"/>
    </Dialog.Overlay>
  </Transition.Child>
```

Headless UI has no way to know it should remove the `opacity-50` class when it starts the transition and adds the `opacity-0` class because it has no idea what those class names mean or anything.

**Closed by adamwathan** 2021-04-17 19:51 UTC

**Comment by 99diagha** [comment] 2021-04-18 09:51
Another way to do this is just replace `Fragment` with `div`

```
<Transition.Child
    as="div"
    ...
>
```
