### ISSUE TITLE
[Disclosure] Nuxt SSR Hydration missmatch

### ISSUE THREAD

**Issue by mwohlan** [tailwindlabs/headlessui#2913] opened 2024-01-04 09:49 UTC
**What package within Headless UI are you using?**

@headlessui/vue 

**What version of that package are you using?**

insiders but its the same with 1.7.16

**What browser are you using?**

See Stackblitz

**Reproduction URL**

https://stackblitz.com/edit/github-ng1nkc?file=app.vue

**Describe your issue**

The server  rendered ids for the button and panel differ from what is expected on the client causing a hydration missmatch warning/error in the console:

![Screenshot from 2024-01-04 10-40-56](https://github.com/tailwindlabs/headlessui/assets/76627776/e0bbfbc7-df38-46da-a192-c9d863728792)

Could be related to #2624 and #2645

**Comment by 4350pChris** [comment] 2024-01-05 19:47
Same problem here. It seems the server does not reset its counter, as it keeps incrementing the id values whenever I refresh the page.

**Comment by itpropro** [comment] 2024-01-08 02:09
The same thing happens for the `menu` component:

![image](https://github.com/tailwindlabs/headlessui/assets/15030951/062df26a-c9c1-42c3-83eb-6db22344cad1)

**Comment by jontybrook** [comment] 2024-01-09 21:09
Same problem here. It could be unrelated - but I believe this issue started showing up when I upgraded to Nuxt 3.9 (and thus Vue 3.4, vite 5 etc)

**Comment by alex-eliot** [comment] 2024-01-10 14:43
This problem also occurs on the MenuButton, MenuItems, and MenuItem components on Nuxt.

**Comment by itpropro** [comment] 2024-01-13 18:12
Also occurs on `headlessui-listbox-button`, basically every button component. Any update @RobinMalfait ?

**Comment by ErriourMe** [comment] 2024-01-20 22:36
The same problem with Popover component.
![image](https://github.com/tailwindlabs/headlessui/assets/43105218/5d4e2ee7-b32c-4974-9df6-adb35b814370)

**Comment by brettshepherd** [comment] 2024-01-24 17:18
Same problem for me as well. Anyone find a temporary fix for this until the library gets patched?

**Comment by xak2000** [comment] 2024-01-25 15:36
@brettshepherd I found a workaround. It's not perfect, but at least it works.

I put the problematic parts of the template into `<ClientOnly>` component. This makes element IDs to be assigned only once (on the client). The problem of this solution is that the part of the component is not rendered until page is fully loaded. That makes the layout blinky as HTML elements could change their width/height after page is loaded.

To workaround that layout problem, I use `#fallback` feature of `<ClientOnly>` component, when possible:

```
  <ClientOnly>
    <Menu as="div" class="..." v-bind="$attrs">
      ...
        <MenuButton class="...">
          <EllipsisVerticalIcon class="h-5 w-5" aria-hidden="true" />
        </MenuButton>
      ...
    </Menu>
    <template #fallback>
      <div class="h-5 w-5" /> <-- the same width/height as the <MenuButton>, that will be rendered only on the Client
    </template>
  </ClientOnly>

```

I'm not happy with this workaround at all. Looking forward for the fix of this issue. 👍

**Comment by mikenavi** [comment] 2024-01-25 15:40
as a temp workaround you can globally override vue version in your `package.json` like this:

```json
...
"overrides": {
    "vue": "^3.3.13"
},
...
```

**Comment by manniL** [comment] 2024-01-29 07:37
I briefly mentioned that in [my video about the Vue 3.4 hydration updates](https://youtu.be/d4-OjlicbiY?t=364). These warnings are "no problem" for now and ideally will be fixed when Vue provides a way to generate random id's which can be easily passed over from server to the client.

Functionality-wise, things should work as before as the "hydration problems" existed before but weren't checked from Vue.

**Comment by Foresteam** [comment] 2024-01-31 00:00
Just encountered this issue, with tab component (HeadlessTab)
```
- rendered on server: id="headlessui-tabs-tab-18"
- expected on client: id="headlessui-tabs-tab-2"
```

**Comment by ExEr7um** [comment] 2024-01-31 00:04
Nuxt `v3.10` added `useId` composable for generating SSR-safe unique IDs (https://github.com/nuxt/nuxt/pull/23368).

**Comment by itpropro** [comment] 2024-01-31 01:29
> Nuxt `v3.10` added `useId` composable for generating SSR-safe unique IDs ([nuxt/nuxt#23368](https://github.com/nuxt/nuxt/pull/23368)).

Maybe it will also land in vue in time 🤞

**Comment by reinink** [comment] 2024-02-01 21:58
Hey folks! 👋

Thanks for reporting this issue and sharing this extra information.

## The issue

Here is the issue as I understand it today:

Vue.js improved its hydration issue detection in v3.4, which is why these warnings started appearing. If you downgrade to Vue.js v3.3, you won't see these warnings anymore, although technically the SSR hydration issues still exist.

These improvements in Vue.js v3.4 are highlighting an SSR id generation issue in Headless UI. Right now Headless UI uses a global incrementing id:

https://github.com/tailwindlabs/headlessui/blob/edbcb81ead08682ac309f8999a9abf20e5a78e49/packages/%40headlessui-vue/src/hooks/use-id.ts#L1-L8

And while this guarantees that the ids are unique, it doesn't guarantee that they will be the same on both the server and client. And when they don't match, a hydration warning is shown.

## Vue.js fix coming in v3.5

Unfortunately there isn't a reliable way today for us to generate an SSR-friendly unique id in Headless UI, as we don't have control over the server.

What we really need is something like React's `useId()` hook — which is actually exactly what the React version of Headless UI uses today for id generation.

Fortunately, there's some good news! According to [this tweet](https://twitter.com/youyuxi/status/1745379112456429688) from Evan You, it sounds like Vue.js will be adding a `useId()` composable in v3.5. Once this is available we'll definitely update Headless UI to use this more SSR-compatible method of id generation.

## Temporary fix in Nuxt

As noted elsewhere in this issue, Nuxt (which does have control over the server) has come up with their own `useId()` composable (https://github.com/nuxt/nuxt/pull/23368) as a stopgap until a more official solution is added to Vue.js in v3.5.

While this new `useId()` composable has already been released in Nuxt v3.10, Headless UI can't just use it, as not all Headless UI projects are Nuxt projects.

That said, we're currently working on a solution for Nuxt users where you'll be able to "provide" Headless UI with this more reliable `useId()` composable.

We actually already have a working prototype locally. This is what it will look like to implement in your Nuxt projects:

> [!NOTE]
> **This doesn't actually exist in Headless UI yet, this is coming soon!**

```vue
<!-- app.vue -->

<template>
  <Switch>
    <!-- .... -->
  </Switch>
</template>

<script setup>
import { Switch } from '@headlessui/vue'

provide('headlessui.useid', () => useId('myapp-'))
</script>
```

If all goes well, this temporary fix could be available as early as tomorrow. Just keep in mind that you'll need to be on the latest version of Nuxt (at least v3.10) plus, of course, the latest version of Headless UI when we get that out.

**Comment by ExEr7um** [comment] 2024-02-02 01:07
> Hey folks! 👋
> 
> Thanks for reporting this issue and sharing this extra information.
> 
> ## The issue
> Here is the issue as I understand it today:
> 
> Vue.js improved its hydration issue detection in v3.4, which is why these warnings started appearing. If you downgrade to Vue.js v3.3, you won't see these warnings anymore, although technically the SSR hydration issues still exist.
> 
> These improvements in Vue.js v3.4 are highlighting an SSR id generation issue in Headless UI. Right now Headless UI uses a global incrementing id:
> 
> https://github.com/tailwindlabs/headlessui/blob/edbcb81ead08682ac309f8999a9abf20e5a78e49/packages/%40headlessui-vue/src/hooks/use-id.ts#L1-L8
> 
> And while this guarantees that the ids are unique, it doesn't guarantee that they will be the same on both the server and client. And when they don't match, a hydration warning is shown.
> 
> ## Vue.js fix coming in v3.5
> Unfortunately there isn't a reliable way today for us to generate an SSR-friendly unique id in Headless UI, as we don't have control over the server.
> 
> What we really need is something like React's `useId()` hook — which is actually exactly what the React version of Headless UI uses today for id generation.
> 
> Fortunately, there's some good news! According to [this tweet](https://twitter.com/youyuxi/status/1745379112456429688) from Evan You, it sounds like Vue.js will be adding a `useId()` composable in v3.5. Once this is available we'll definitely update Headless UI to use this more SSR-compatible method of id generation.
> 
> ## Temporary fix in Nuxt
> As noted elsewhere in this issue, Nuxt (which does have control over the server) has come up with their own `useId()` composable ([nuxt/nuxt#23368](https://github.com/nuxt/nuxt/pull/23368)) as a stopgap until a more official solution is added to Vue.js in v3.5.
> 
> While this new `useId()` composable has already been released in Nuxt v3.10, Headless UI can't just use it, as not all Headless UI projects are Nuxt projects.
> 
> That said, we're currently working on a solution for Nuxt users where you'll be able to "provide" Headless UI with this more reliable `useId()` composable.
> 
> We actually already have a working prototype locally. This is what it will look like to implement in your Nuxt projects:
> 
> Note
> 
> **This doesn't actually exist in Headless UI yet, this is coming soon!**
> ```
> 
> 
> <template>
>   <Switch>
>     
>   </Switch>
> </template>
> 
> <script setup>
> import { Switch } from '@headlessui/vue'
> 
> provide('headlessui.useid', () => useId('myapp-'))
> </script>
> ```
> 
> If all goes well, this temporary fix could be available as early as tomorrow. Just keep in mind that you'll need to be on the latest version of Nuxt (at least v3.10) plus, of course, the latest version of Headless UI when we get that out.

That's great news! I should also mention, that there is a Nuxt Module for Headless UI (https://github.com/P4sca1/nuxt-headlessui) and I think it can incorporate that temporary fix.

**Comment by P4sca1** [comment] 2024-02-02 14:14
Once the proposed temporary solution @reinink mentioned is available, I will update the Nuxt HeadlessUI module to make use of it.

**Comment by reinink** [comment] 2024-02-02 20:52
Hey folks! As promised, we've got a fix in place for this as of `@headlessui/vue@1.7.18`, which was just published a few minutes ago.

We decided to create a small `provideUseId()` composable that you can import as a way of providing the new Nuxt `useId()` composable that's available as of Nuxt v3.10. Here's how:

```vue
<!-- app.vue -->

<template>
  <Switch>
    <!-- .... -->
  </Switch>
</template>

<script setup>
import { Switch, provideUseId } from '@headlessui/vue'

provideUseId(() => useId())
</script>
```

As mentioned yesterday, make sure you're on the latest version of both Headless UI and Nuxt:

```sh
npm install @headlessui/vue@latest nuxt@latest
```

We're currently working on Headless UI v2.0, but that will likely come out officially after Vue.js v3.5, so in all likelihood we will just use the native `useId()` support for the next major release.

Going to close this issue now, but please report back if you have any further issues 👍

**Closed by reinink** 2024-02-02 20:52 UTC

**Comment by xak2000** [comment] 2024-02-03 19:01
@reinink Can you clarify, please, where to put this `provideUseId(() => useId())` line?

Should it be present in every component, that uses any headlessui component? Or it is enough to call it just once at a global level (such as `app.vue` component in Nuxt)?

**Comment by thecrypticace** [comment] 2024-02-04 16:35
@xak2000 It uses provide() and inject() internally so it's sufficient to call it once in the top-most component in your app. e.g. `app.vue`

**Comment by gkkirilov** [comment] 2024-02-04 17:55
I did that but still get an error for the disclosure component
![image](https://github.com/tailwindlabs/headlessui/assets/8720012/cc59efda-1274-4cf4-90c2-94f379ff9359)


Here is reproduction https://stackblitz.com/edit/nuxt-starter-u2abnr?file=app.vue
@reinink

**Comment by mwohlan** [comment] 2024-02-05 13:31
@reinink I am still getting hydration missmatches even after the fix:

This is what it looks like now your provided solution for nuxt:

![image](https://github.com/tailwindlabs/headlessui/assets/76627776/ab0e17e8-1b4c-49ae-97c4-c9651a203f90)

The question remains if this is an issue with useId or with headlessui ?

**Comment by thecrypticace** [comment] 2024-02-05 13:39
@mwohlan can you provide a reproduction?

**Comment by mwohlan** [comment] 2024-02-05 15:11
@thecrypticace 

https://stackblitz.com/edit/github-bbxtfw?file=app.vue

Okay this seems to be an issue with the nuxt-headlessui module. Importing the the components explicitly from headless-ui fixes the hydration missmatch. This is kinda weird since I forced the module to use the fixed version...

**Comment by DamianGlowala** [comment] 2024-04-04 08:58
Is `provideUseId` available in insiders version? Sadly, it doesn't seem to be available.

**Comment by mikezange** [comment] 2024-05-21 09:04
If you ran into this issue (like me) using:
Astro `v4.8.6` 
Vue `v3.4.27` 
HeadlessUI `1.7.22`

You can add the `client:only="vue"` directive to the outer component, it is very much a work around like: https://github.com/tailwindlabs/headlessui/issues/2913#issuecomment-1910454923

But until its fixed permanently it cleans up the console

Example: 

```
Layout.astro
...
<Nav client:only="vue" />
...
```

```
Nav.vue
<template>
  <Disclosure as="nav" class="bg-white shadow" v-slot="{ open }">
      ....
  </Disclosure>
</template>
```

I am by no means a frontend pro, so I don't know if this will have any knock on effects.

**Comment by danschalow** [comment] 2024-06-13 09:21
@zenire it's not optimal, but we were having issues with both `:` and `-`.

We are working with the following.

```typescript
// app.vue

import { provideUseId } from '@headlessui/vue'

provideUseId(() => useId().replace(/[-:]/, '_'))
```

**Comment by zenire** [comment] 2024-06-13 11:53
Thnx @danschalow I also discovered this issue just now: https://github.com/nuxt/nuxt/pull/26315

**Comment by notflip** [comment] 2024-07-23 06:49
@danschalow Is this a temporary fix until the SSR issue is fixed, or is this line something we're going to have to always add?

**Comment by felixgabler** [comment] 2024-09-07 21:54
Does the release of Vue 3.5 change anything for this? A stable `useId()` is now included in Vue itself

**Comment by xak2000** [comment] 2024-09-13 19:19
I seen the last [@headlessui/vue@v1.7.23](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Fvue%40v1.7.23) switched to use Vue's `useId()` if available, but I still have hydration mismatch problems for some reason.

Such as:
```
[Vue warn]: Hydration attribute mismatch on 
 
  - rendered on server: id="headlessui-popover-button-6"
  - expected on client: id="headlessui-popover-button-1"
  ```

I didn't tried `Popover` directly though, the problem in my case is caused by this line of this library: https://github.com/elreco/vue-tailwind-datepicker/blob/c08427247a9b90af3a50c5e770c9fd5f5571ec34/src/VueTailwindDatePicker.vue#L1436

**Comment by masterjiyuhang** [comment] 2024-10-16 07:46
> I seen the last [@headlessui/vue@v1.7.23](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Fvue%40v1.7.23) switched to use Vue's `useId()` if available, but I still have hydration mismatch problems for some reason.
> 
> Such as:
> 
> ```
> [Vue warn]: Hydration attribute mismatch on 
>  
>   - rendered on server: id="headlessui-popover-button-6"
>   - expected on client: id="headlessui-popover-button-1"
> ```
> 
> I didn't tried `Popover` directly though, the problem in my case is caused by this line of this library: https://github.com/elreco/vue-tailwind-datepicker/blob/c08427247a9b90af3a50c5e770c9fd5f5571ec34/src/VueTailwindDatePicker.vue#L1436

I encountered the same problem. I found that this problem occurred when I encapsulated the headless tab into a component and called it repeatedly. I wonder if this can help you.

**Comment by CyJackX** [comment] 2025-12-03 05:20
- rendered on server: id="headlessui-tabs-tab-v-0-11-0"
  - expected on client: id="headlessui-tabs-tab-v-0-0-0"
