### ISSUE TITLE
(Vue) Focus issue with Listbox

### ISSUE THREAD

**Issue by Uninen** [tailwindlabs/headlessui#262] opened 2021-02-26 12:06 UTC
I'm trying to write a country select widget that has a search field for a big list of countries. Turns out using Listbox for this is really difficult, as handling the focus properly seems nearly impossible with any implementation I've tried. It would be very helpful to have more control of the focus or at least a way to disable the current focus implementation.

**Comment by RobinMalfait** [comment] 2021-02-26 12:14
Hey! Thank you for your suggestion!
Much appreciated! 🙏

The focus trap is important for accessibility reasons so we will not remove that.
The feature you actually want is a combobox so that we can have a search field + listbox, which we have on the list for feature requests. 

Therefore going to close this one as a duplicate of https://github.com/tailwindlabs/headlessui/issues/254

**Closed by RobinMalfait** 2021-02-26 12:14 UTC

**Comment by awkale** [comment] 2021-03-17 14:05
Is there a rough estimate when the combobox would be available?

**Comment by adamwathan** [comment] 2021-03-17 14:14
Haven't even started thinking about it so can't really say.

**Comment by hidewak** [comment] 2021-11-17 07:46
Hi, I had the exact same use case as Uninen, any news on that? Thanks
