### ISSUE TITLE
Dialog doesn't support negative tabIndex

### ISSUE THREAD

**Issue by lukasgebhard** [tailwindlabs/headlessui#2922] opened 2024-01-10 10:29 UTC
**What package within Headless UI are you using?**

@headlessui/react 

**What version of that package are you using?**

v1.7.15

**What browser are you using?**

Chrome

**Reproduction URL**

https://codesandbox.io/p/devbox/boring-thunder-r9dnz8

**Describe your issue**

1. Go to the sandbox and tab to the "Open Dialog" button
2. The button is now focused (indicated by blue background). Press enter to open the dialog
3. The dialog is not open and the "Close Dialog" button is focused. However, the dialog title should be focused instead because it has `tabIndex="-1"`.

Note that with `tabIndex="0"`, everything works as expected. I need `tabIndex="-1"`, though.

**Comment by RobinMalfait** [comment] 2024-01-11 13:03
Hey!

In the insiders version (`npm install @headlessui/react@insiders`) and in the alpha version (`npm install @headlessui/react@next`), the `Dialog` will have a `tabIndex={-1}` by default such that we can focus the `Dialog` by default.

Going to close this for now, since the expected behaviour should work in insiders already.
Hope this helps!

**Closed by RobinMalfait** 2024-01-11 13:03 UTC
