### ISSUE TITLE
ComboBox mouse and keyboard different behavior

### ISSUE THREAD

**Issue by makroxyz** [tailwindlabs/headlessui#2563] opened 2023-06-29 12:36 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

^1.7.10

**What browser are you using?**

Chrome, Firefox

**Describe your issue**

It is related to PR #2272 

The behavior between keyboard and mouse is different.

```vue
<Combobox
    v-model="selectedCity"
    by="istat"
    as="div"
    @focusin="selectedCity = ''"
>
.........
</Combobox>
```

selecting with keyboard all is fine, but using mouse a focus event is send to ComboBox and that v-model variable is reset.

I need to reset a field when has focus. That works fine until 1.7.9

**Comment by RobinMalfait** [comment] 2023-06-29 14:04
Hey, thank you for this bug report! 🙏

The difference is expected because 2 things are happening:
1. When you are using the keyboard, the `input` field is focused and stays focused while you are using your arrow keys.
2. If you are using the mouse, then the browser moves the focus to the `Combobox.Option` when you click it and we move it back into the focus field such that you can continue using the keyboard.

Therefore this behaviour is correct and is not a bug. The reason it worked until 1.7.9 is because before that there _was_ an actual bug where you couldn't use the keyboard anymore after you used the mouse _unless_ you manually moved focus back into the `input`.

That said, I know this doesn't help you, but can you tell me more about the use case you are trying to solve right now to see if there are better solutions you can apply here?

**Comment by makroxyz** [comment] 2023-06-29 14:29
As I wrote above I need to reset ComboBox when focused.
I have a special form with 4 ComboBoxes: the 2nd depends on 1st, the 3rd from 2nd and so on.
When I put focus in 1st field I need to reset his own value (and by reaction all descending fields).
I've spent all the morning, but didn't find a solution.

I  understand what you explained, but I think keyboard and mouse must "behave" in the same way...

If I use only keyboard it works fine! That's not good!!

**Comment by RobinMalfait** [comment] 2023-06-29 18:07
I see what you mean, unfortunately I think that the focus option is still not going to work even if we fix the inconsistency (fixing this would force us to blur and re-focus the input when you selected an item via the keyboard). But I'm here to try and help you, so let's see if we can figure out another solution that does work!

If I understand correctly you have multiple comboboxes that depend on each other, if a value changes in combobox A, and combobox B depends on combobox A, then you want to reset combobox B so that you can show the correct values in combobox B based on the new value of combobox A. Is this assumption correct?

The reason I think the `focus` solution won't work is because the moment you <kbd>tab</kbd> to combobox A it will reset its value, then resets the value of combobox B and so on. This feels very destructive to me. It also means that if a user is just tabbing through the form then all of a sudden a bunch of data is lost because it was reset due to the reset chain triggered on focus. Keep in mind that focus is also trigger when you click inside of an `input` field, but maybe this is what you want?

The `input` being focused again once you click on an option is also the expected behaviour, so this in turn will also reset the combobox. Unfortunately we can't fix this because it is the browser that moves focus to the `Combobox.Option` the moment you click it. Sadly, this is not something we can fix, the browser will move the focus and as far as I know we can't stop it from doing that. The only thing we can do is to move focus back into the input (this is to guarantee users to be able to continue typing and use arrow keys).

I made a little demo outside of Headless UI / React / Tailwind CSS that shows this problem: https://jsfiddle.net/Lkx8bsnq/
1. Open your devtools
2. Click inside of the `input` field to focus it
3. Click the button

Now, you will notice that you are still in the `input` field, however this only worked because we moved focus back into the input field, because there is no way for us to keep the focus in the input field itself. I added some logs by using `focus` and `blur` event listeners to trace what's going on.

These are the logs you should see:
```
`input` received focus
Moving focus to <button id=​"b">​Click me​</button>​
`input` received focus
```

I think, and please correct me if I'm wrong here, you only want to reset the other comboboxes if you actually change the `value`. That's mainly why I asked you about the actual use case to try and understand what you really want to achieve here. If this assumption is correct, then we should be able to rely on the values being changed and not on the underlying click / focus / ... events. If this is not your use case, and you really do wish to use the underlying `focus` event then I'm afraid I won't be able to help you because of the restrictions the browser has. If you do have a minimal reproduction repo or CodeSandbox then I'm more than happy to try and help wherever I can.

In case my assumption is correct where you want to reset the other comboboxes if the value change then we can explore that route a bit further. I made a CodeSandbox based on this assumption and based on the information you gave me where comboboxes need to reset based on other comboboxes: https://codesandbox.io/p/sandbox/dry-hooks-pvqd6h this CodeSandbox resets other comboboxes when the value changes. The first example is a very verbose/explicit one. The second is a bit more abstract but scales a bit better. 

Is this a solution that works for you example?

In either case, I'm going to close this issue for now since I don't think there is an actual bug that we can fix here. If you do have more questions or we discover some bugs based on what you are trying to do then I'll open this issue again.

I hope this helps!

**Closed by RobinMalfait** 2023-06-29 18:07 UTC
Labels: Needs more info

**Comment by makroxyz** [comment] 2023-06-30 05:44
Thanks for your amazing reply!
I will do as you suggest... waiting for a change instead reset on focus!

**Comment by makroxyz** [comment] 2023-06-30 09:10
Ehm... another issue...

I'd like to move focus on next field after selected... 
as usual with keyboard no problems.... with mouse focus remains on selected combobox...
