### ISSUE TITLE
bug: scroll not working if I scroll over overlay in dialog

### ISSUE THREAD

**Issue by ashwinkhode** [tailwindlabs/headlessui#1132] opened 2022-02-22 14:46 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Chrome

**Reproduction URL**

https://utc3i4.csb.app/

**Describe your issue**

I am not able to scroll modal if I scroll over the overlay. I can only scroll modal if I scroll over the modal content. Let me know if I can provide some more info if needed

Current Behavior - When I scroll over overlay of the modal, modal content is not scrolling
Expected Behavior - When I scroll over overlay of the modal or anywhere over the screen if the modal is open, then the modal should scroll even if I scroll outside modal content

**Screenshot**
![image](https://user-images.githubusercontent.com/53361996/155154074-10a58f50-730f-4b01-9259-917f17f62568.png)

**Comment by RobinMalfait** [comment] 2022-02-24 13:51
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is a known issue and we will work on it soon but have to figure a few things out first. Going to close it as a duplicate of #1056

**Closed by RobinMalfait** 2022-02-24 13:51 UTC

**Comment by RobinMalfait** [comment] 2022-04-14 15:26
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1333, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.

However, in order to make it work properly, you have to update the `Dialog.Overlay` with `Dialog.Backdrop`. In addition, you have to mark your panel with your contents by wrapping it in a `Dialog.Panel`. In your case I swapped the `div` out with a `Dialog.Panel`. 

Here is an updated CodeSandbox that includes the insiders build: https://codesandbox.io/s/holy-leaf-wkf4pv?file=/src/App.js
