### ISSUE TITLE
Warning: Extra attributes from the server: role

### ISSUE THREAD

**Issue by binajmen** [tailwindlabs/headlessui#1877] opened 2022-09-27 15:09 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

^1.6.6

**What browser are you using?**

Chrome

**Reproduction URL**

Project still in development.

**Describe your issue**

I'm subscribed to Tailwind UI and using the last Radio Group component:
https://tailwindui.com/components/application-ui/forms/radio-groups#component-7b583a008c3fc62c0fe403d10ca042bb

I get the following warning in the console:
```
Warning: Extra attributes from the server: role
    at input
    at div
    at http://.../menu-JP4IGN5X.js:133:13
    ...
```

Used in a SSR context (Remix).

This is non blocking, although I suspect this should be tracked for future enhancement/correction :)

**Comment by RobinMalfait** [comment] 2022-09-28 13:41
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you attach a reproduction repo so that we can take a look?

I tried to reproduce this in Next.js (the local playgrounds we use) and couldn't reproduce this exact warning. This is the result I get from SSR:

```js
<div id="headlessui-radiogroup-:R6m:" role="radiogroup">
    <label class="sr-only" id="headlessui-label-:R3em:"> Privacy setting </label>
    <div class="-space-y-px rounded-md bg-white">
        <div class="rounded-tl-md rounded-tr-md z-10 border-indigo-200 bg-indigo-50 relative flex cursor-pointer border p-4 focus:outline-none" id="headlessui-radiogroup-option-:Rdem:" role="radio" aria-checked="true" tabindex="0" data-headlessui-state="checked">
            <span class="border-transparent bg-indigo-600 mt-0.5 flex h-4 w-4 shrink-0 cursor-pointer items-center justify-center rounded-full border" aria-hidden="true">
                <span class="h-1.5 w-1.5 rounded-full bg-white"></span>
            </span>
            <span class="ml-3 flex flex-col">
                <span class="text-indigo-900 block text-sm font-medium" id="headlessui-label-:Rddem:">Public access</span>
                <span class="text-indigo-700 block text-sm" id="headlessui-description-:Rldem:">This project would be available to anyone who has the link</span>
            </span>
        </div>
        <div class="border-gray-200 relative flex cursor-pointer border p-4 focus:outline-none" id="headlessui-radiogroup-option-:Rlem:" role="radio" aria-checked="false" tabindex="-1" data-headlessui-state="">
            <span class="border-gray-300 bg-white mt-0.5 flex h-4 w-4 shrink-0 cursor-pointer items-center justify-center rounded-full border" aria-hidden="true">
                <span class="h-1.5 w-1.5 rounded-full bg-white"></span>
            </span>
            <span class="ml-3 flex flex-col">
                <span class="text-gray-900 block text-sm font-medium" id="headlessui-label-:Rdlem:">Private to Project Members</span>
                <span class="text-gray-500 block text-sm" id="headlessui-description-:Rllem:">Only members of this project would be able to access</span>
            </span>
        </div>
        <div class="rounded-bl-md rounded-br-md border-gray-200 relative flex cursor-pointer border p-4 focus:outline-none" id="headlessui-radiogroup-option-:Rtem:" role="radio" aria-checked="false" tabindex="-1" data-headlessui-state="">
            <span class="border-gray-300 bg-white mt-0.5 flex h-4 w-4 shrink-0 cursor-pointer items-center justify-center rounded-full border" aria-hidden="true">
                <span class="h-1.5 w-1.5 rounded-full bg-white"></span>
            </span>
            <span class="ml-3 flex flex-col">
                <span class="text-gray-900 block text-sm font-medium" id="headlessui-label-:Rdtem:">Private to you</span>
                <span class="text-gray-500 block text-sm" id="headlessui-description-:Rltem:">You are the only one able to access this project</span>
            </span>
        </div>
    </div>
</div>
```

... where the role is properly applied.

So I wonder if you have other things going on that could cause issues.

**Comment by RobinMalfait** [comment] 2022-10-03 10:30
Hey!

Going to close this for now, if you still have this issue then please create a new issue with a reproduction repo attached so that we can start debugging.

**Closed by RobinMalfait** 2022-10-03 10:30 UTC
Labels: Needs more info

**Comment by binajmen** [comment] 2022-10-03 10:44
Hey, so sorry, it was due to a bad setup when upgrading to React 18. I should have closed this issue by myself. Cheers!
