### ISSUE TITLE
[Bug]: Headless UI menu with React 18 alpha not working

### ISSUE THREAD

**Issue by bigint** [tailwindlabs/headlessui#890] opened 2021-10-27 02:47 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

Chrome

### Reproduction repository

https://gitlab.com/yo/devparty

### Describe your issue

The menu is not expanding with react 18 inside nextjs 12, but it works fine with react 17 and nextjs 11

Codesandbox: https://codesandbox.io/s/headlessui-in-react-18-jv689

**Comment by bencehusi** [comment] 2021-11-02 13:23
@bigint what I found is that it indeed doesn't work in development mode, however, it does work in production.

Run npm run build and npm run start and it works.

Anyhow, it'd be really great if someone could shed a light on this.

**Comment by simonswiss** [comment] 2021-11-03 01:25
Was able to reproduce the problem, which affects the `Transition` component in Headless UI, which will not show its children (even with `show={true}`) with React 18 alpha.

It shows properly when using Next.js 12 with React 17.

**Comment by Wajid2001** [comment] 2021-11-29 07:06
Hey Someone Please fix this issue

**Comment by RXminuS** [comment] 2021-11-30 12:57
> Hey Someone Please fix this issue

It's open source, feel free to create a PR. Or if you don't have the time, why not create a git bounty or donate to the project. So many ways to contribute!

Regardless, your comment comes across as rude and generally it's best to either just subscribe to a thread if the issue is of interest to you (that way the core devs can see which issues bubble towards the top) or contribute with more details about the context in which it isn't working as expected for you.

I know (assume) you probably didn't mean it that way but sometimes you need to be a bit careful about the tone of a message when all you have is text and not any non-verbal communication.

**Comment by Wajid2001** [comment] 2021-11-30 13:53
> > Hey Someone Please fix this issue
> 
> @Wajid2001 It's open source, feel free to create a PR. Or if you don't have the time, why not create a git bounty or donate to the project. So many ways to contribute!
> 
> Regardless, your comment comes across as rude and generally it's best to either just subscribe to a thread if the issue is of interest to you (that way the core devs can see which issues bubble towards the top) or contribute with more details about the context in which it isn't working as expected for you.
> 
> I know (assume) you probably didn't mean it that way but sometimes you need to be a bit careful about the tone of a message when all you have is text and not any non-verbal communication.

Sorry for that comment, it was not my intention to hurt someone's feeling, but to address the issue to professional developer's like. And I have also deleted that comment.

By the way thank you for informing me about the open source. But my skills are not that much, I will surely looking forward towards solving this issue or other issues, to  make this developer community a better place.

And I hope, professional developer's like you will solve this issue soon.

Thanks

**Comment by RobinMalfait** [comment] 2022-01-19 13:57
Hey! Thank you for your bug report!
Much appreciated! 🙏

We haven't worked on React 18 support yet since this also introduces breaking changes. Will close this in favor of a tracking issue for React 18: https://github.com/tailwindlabs/headlessui/issues/681

**Closed by RobinMalfait** 2022-01-19 13:57 UTC

**Comment by glushkina1** [comment] 2022-07-07 23:17
<img width="300" height="300" alt="Menu (Dropdown) - Headless UI 🔊 2022-07-08 2 AM-10-20" src="https://user-images.githubusercontent.com/40953265/177886603-60f6c498-a314-4952-b335-188220841b47.png">
<img width="300" height="300" alt="Stop The War 🔊 2022-07-08 2 AM-10-40" src="https://user-images.githubusercontent.com/40953265/177886614-36a92a2e-6f92-4ecb-b6d7-b47d8a373ef5.png">


I've tried func Example, nothing changed in a file, but it doesn't work properly 

```
  "@headlessui/react": "^1.6.6",
    "@heroicons/react": "^1.0.6",
    "next": "^12.2.0",
    "react": "^18.2.0",
```


Does anyone know why?

**Comment by RobinMalfait** [comment] 2022-07-08 09:29
@glushkina1 Headless UI is Headless which means it is unstyled. The examples use [Tailwind CSS](https://tailwindcss.com/) so make sure to install that as well if you want to play with this.

**Comment by glushkina1** [comment] 2022-07-09 20:12
@RobinMalfait thanks for you response. it didn't work because of import wrong css files

**Comment by Chayuga** [comment] 2022-12-21 00:49
@RobinMalfait @RXminuS I am using:

```
"next": "13.0.7",
"react": "18.2.0",
"react-dom": "18.2.0",
```

I spent a lot of time troubleshooting this issue on NextJS 13, only to import 

```
import '../styles/dist.css';
import '../styles/globals.css';
```

inside app/layout.tsx file and the issue was fixed.
