### ISSUE TITLE
The requested module 'react' does not provide an export named 'useLayoutEffect'

### ISSUE THREAD

**Issue by ranashamshair** [tailwindlabs/headlessui#1614] opened 2022-06-23 15:09 UTC
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1606

<div type='discussions-op-text'>

<sup>Originally posted by **ranashamshair** June 21, 2022</sup>
Hi i am using headles ui 
with "next": "12.1.6", "react": "18.1.0", "react-dom": "18.1.0",

Server Error
SyntaxError: The requested module 'react' does not provide an export named 'useLayoutEffect'

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
};
module.exports = nextConfig;

![error](https://user-images.githubusercontent.com/75786212/174712118-f8d04667-c67b-4662-b26c-98f534071d2f.png)

everything is fine but i don't know why this error is come when i reomove headles ui components then working fine but when use headles component error is come?

Thanks</div>

**Comment by ranashamshair** [comment] 2022-06-23 15:11
Once i switched to react js 17.0.2 everything working fine.

**Comment by RobinMalfait** [comment] 2022-06-24 10:10
Closing in favor of the original Discussion. Make sure to remove your .next folder, if that doesn't work please provide a reproduction repo.

**Closed by RobinMalfait** 2022-06-24 10:10 UTC

**Comment by swinner2** [comment] 2022-06-30 04:29
I'm running into this issue on vercel
<img width="1017" alt="Screen Shot 2022-06-29 at 9 28 49 PM" src="https://user-images.githubusercontent.com/6707308/176592958-58d91882-183c-4a05-8362-12375b7019c5.png">

**Comment by swinner2** [comment] 2022-06-30 23:59
using `@headlessui/react@insiders` fixed my issue.

**Comment by mattlrobinson7** [comment] 2022-07-04 00:30
Having the same issue as well. Looks like this worked for me in 1.4.1 and started failing when I upgraded to 1.6.5. Upgrading to insiders did not fix this for me.

**Comment by mattlrobinson7** [comment] 2022-07-04 15:52
Note that this works on localhost, but when deployed (vercel) is when I hit the error. @RobinMalfait, this issue is marked as closed, but the linked discussion has no solution or comments. Is there a fix or suggested workaround here?

**Comment by austincollinpena** [comment] 2022-07-08 12:06
I'm also facing this issue.

**Comment by cdt-eth** [comment] 2022-07-11 20:51
also experiencing. installing `@headlessui/react@insider`, removing the `.next` folder, or reinstalling all dependencies didn't fix it, @RobinMalfait

**Comment by AdrianoLupossa** [comment] 2022-07-13 16:50
Reinstaliing all dependencies and changing node version worked well for me

**Comment by maxcountryman** [comment] 2022-07-18 13:33
> > Reinstaliing all dependencies and changing node version worked well for me
> 
> 
> 
> Can you tell me what node version worked for you?
> 
> 
> 
> Are you building locally or on somewhere like Vercel or Cloudflare?

Node 16.7.0 on Cloudflare works for me now.

**Comment by cdt-eth** [comment] 2022-07-19 16:38
> Are you building locally or on somewhere like Vercel or Cloudflare?

Next.js site using Vercel

**Comment by mattlrobinson7** [comment] 2022-07-19 17:05
Can we reopen this issue? This is blocking me from upgrading

**Comment by RobinMalfait** [comment] 2022-07-19 17:13
Please open a new issue, can't help without a reproduction repo.
