### ISSUE TITLE
Combobox (Autocomplete) is broken on website's doc

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [tailwindlabs/headlessui#1739] opened 2022-08-04 15:12 UTC
**What package within Headless UI are you using?**
React in the examples

For example: @headlessui/react

**What version of that package are you using?**
latest
For example: v0.3.1

**What browser are you using?**

For example: Chrome, Safari, or N/A

Safari

**Reproduction URL**

https://headlessui.com/react/combobox

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

**Describe your issue**

The combobox input does not update onChange

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead.

**Comment by RobinMalfait** [comment] 2022-08-04 15:28
Hey! Thank you for your bug report!
Much appreciated! 🙏

Going to close this as a duplicate of #1735, thanks for reporting!

**Closed by RobinMalfait** 2022-08-04 15:28 UTC
