### ISSUE TITLE
Transition: In Vue, Transition enter animations do not work/flash when child has a Swiper element

### ISSUE THREAD

**Issue by alex-eliot** [tailwindlabs/headlessui#2557] opened 2023-06-25 17:48 UTC
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.14

**What browser are you using?**

Encountered on Chrome 114, Safari 16 (both MacOS and iOS), Firefox 114.

**Reproduction URL**

https://codesandbox.io/p/sandbox/eloquent-currying-d4g8l9

I took the code from https://tailwindui.com/components/application-ui/overlays/modals and replaced the inner text with a minimal Swiper component.

**Describe your issue**

If there is a Swiper component inside a TransitionChild component, the enter animation will not play, and it will flash into view.

**Comment by alex-eliot** [comment] 2023-06-25 19:39
To provide more insight, here's why this issue is caused:

When the component is to be rendered via the [render function here](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/transitions/transition.ts#L371C6-L380C9) it is rendered without the enterFrom and enter classes, which means it's rendered as it is. By the time [the logic reaches here](https://github.com/tailwindlabs/headlessui/blob/main/packages/@headlessui-vue/src/components/transitions/utils/transition.ts#L67C3-L68C37), the component is in full view (possibly because swiper takes a little while to mount? I'm unsure). This causes the "opacity-0" to not be visible at all because it's immediately replaced with "opacity-100".

I cloned the repo, installed the swiper component and tinkered with the code, and found that replacing [this part](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/transitions/transition.ts#L354C7-L354C40) with the following code fixed the issue:

```typescript
let ourProps = {
  ref: container,
  class: normalizeClass([
    ...enterFromClasses,
    ...enterClasses
  ])
}
```

However, this causes some tests to fail, hence why I haven't made a PR (I don't have a lot of time to get too much into it). Still, I hope that this helps you find the core issue much faster.

**Comment by mattmolinare** [comment] 2023-06-28 21:18
I'm having this exact same issue in React as well.

**Comment by malectro** [comment] 2023-07-06 20:58
Might be helpful, but I had a similar issue with 1.7.15 and fixed it by setting `className="duration-300"` instead of `enter="duration-300"`.

**Comment by mattmolinare** [comment] 2023-07-10 14:44
@malectro I can confirm this fix works but it is an anti-pattern.

**Comment by thecrypticace** [comment] 2023-08-15 22:42
Hey, I've been looking into this one and it seems that Swiper is calling `window.getComputedStyle(…).getPropertyValue(…)` on an element that is in the tree that is transitioning.

This is apparently causing the transition to be cancelled. I'm not yet sure why this is but you can work around this by delaying the mount of the `<Swiper>` element by one frame which should side-step the problem for now:
https://codesandbox.io/p/sandbox/bold-cache-gsgddh?file=/src/App.vue:98,1-104,2

**Comment by Joostdeboer** [comment] 2023-08-18 07:57
We seem to be having this issue as well in React 18.0, but get this problem even without using the Swiper element. Using 'className' instead of 'enter' did not fix it for us, and since we're using React, I'm not sure if the code of @thecrypticace works for me too, also because I'm unfamiliar with what the ref inside is supposed to accomplish.

**Comment by thecrypticace** [comment] 2023-08-18 19:18
Hey all. Here's a link to the repro using just pure HTML/JS/CSS: https://jsbin.com/liluxacoyu/edit?html,output

The gist of what's happening here is that:
- An element is added to the DOM (by Vue / React)
- `window.getComputedStyle(…).getPropertyValue(…)` is called on it OR any of it's descendants (in this case, by Swiper in the same frame as the addClass)
- We add a class to trigger the animation (by Headless UI)
- The browser starts and then immediately cancels the transition (Safari, Chrome, Edge, FF, etc…)

The problem does not happen if `window.getComputedStyle()`… is called _after_ the classes are added. This can be immediately after (as you see in the reproduction above). But I think the most reliable workaround is to delay Swiper (or any 3rd-party affecting code / component) from being run by at least one full frame / paint cycle. The reason being is that you can't really cause code to happen immediately after Headless UI adds/removes classes (because javascript).

So, this 1-frame delay workaround is achievable by doing a nested `requestAnimationFrame()` callback:

```js
requestAnimationFrame(() => {
  requestAnimationFrame(() => {
    // your code here to conditionally show the component
    // or call `window.getComputedStyle().getPropertyValue()`
  })
)
```

In my workaround I posted above I used this technique to only mount the `<Swiper>` component unmounted once the animation had already started (after 1 frame). And since the delay is only one frame it's unlikely to be noticeable.

Given that this isn't a Headless UI issue itself — and that the interaction requires hyper-specific circumstances with 3rd-party code — I'm going to close this one.

**Closed by thecrypticace** 2023-08-18 19:18 UTC

**Comment by Tchilly** [comment] 2024-09-19 23:54
Don't mean to open unnecessary tickets, but this happens with the sidebar navigation things on tailwindui.com /  application-shells/sidebar as well. transition in "pops into view/no nice fade etc." in v1.7.14, but works as intended with v1.6.* Same with combo boxes, dialogs etc.

**Comment by jelledv49** [comment] 2025-01-31 09:38
> Hey all. Here's a link to the repro using just pure HTML/JS/CSS: https://jsbin.com/liluxacoyu/edit?html,output
> 
> The gist of what's happening here is that:
> 
>     * An element is added to the DOM (by Vue / React)
> 
>     * `window.getComputedStyle(…).getPropertyValue(…)` is called on it OR any of it's descendants (in this case, by Swiper in the same frame as the addClass)
> 
>     * We add a class to trigger the animation (by Headless UI)
> 
>     * The browser starts and then immediately cancels the transition (Safari, Chrome, Edge, FF, etc…)
> 
> 
> The problem does not happen if `window.getComputedStyle()`… is called _after_ the classes are added. This can be immediately after (as you see in the reproduction above). But I think the most reliable workaround is to delay Swiper (or any 3rd-party affecting code / component) from being run by at least one full frame / paint cycle. The reason being is that you can't really cause code to happen immediately after Headless UI adds/removes classes (because javascript).
> 
> So, this 1-frame delay workaround is achievable by doing a nested `requestAnimationFrame()` callback:
> 
> requestAnimationFrame(() => {
>   requestAnimationFrame(() => {
>     // your code here to conditionally show the component
>     // or call `window.getComputedStyle().getPropertyValue()`
>   })
> )
> 
> In my workaround I posted above I used this technique to only mount the `<Swiper>` component unmounted once the animation had already started (after 1 frame). And since the delay is only one frame it's unlikely to be noticeable.
> 
> Given that this isn't a Headless UI issue itself — and that the interaction requires hyper-specific circumstances with 3rd-party code — I'm going to close this one.

Hey, wanted to say thanks for sharing your solution! 🙌 I was facing the same issue (but with Embla) and I tried deferring the mounting until the transition was done, but that looks terrible. I didn't realize I could just wait a cycle and then mount.

**Comment by Phyllon** [comment] 2025-03-18 15:20
A good solution to this problem is using the `@after-enter` event on the `TransitionChild` and set a boolean `ref` (e.g. `hasTransitioned`) to `true` -> `@after-enter="hasTransitioned = true"`
Then on `Swiper` component just use `Swiper v-if="hasTransitioned" ...` so it's loaded lazily :)
