### ISSUE TITLE
[BUG] `Transition` entering is broken when wrapped with another component receiving `key` prop

### ISSUE THREAD

**Issue by xsjcTony** [tailwindlabs/headlessui#2545] opened 2023-06-20 03:26 UTC
**What package within Headless UI are you using?**

`@headlessui/react`

**What version of that package are you using?**

`v1.7.15`

**What browser are you using?**

`Chrome`

**Reproduction URL**

https://stackblitz.com/edit/vitejs-vite-d9yltt?file=src%2FApp.tsx

**Describe your issue**

Imagine a `Modal` component that I encapsulated, with content and open state being passed by `props`. In my real use case, I have another wrapper with some state to control the content as well as modal open state in `props`, but due to I need to ensure it's going to open a new fresh modal (with fresh form inside), I have to pass `key` to the `wrapper` component contains the modal. (Suggested by React doc: https://react.dev/learn/you-might-not-need-an-effect#resetting-all-state-when-a-prop-changes)

Under this scenario, that `enter` transition will then be broken (i.e. no effect at all). In my reproduction, Even without the wrapper, when assigning a `key` to `<Modal />` component straight away will break the `enter` transition as well. But you are free to uncomment the wrapper to verify it's broken in both case.

Due to passing a `key` to reset all props is the recommended way by React doc, so I'm assuming that it's a bug of this library instead of I'm writing anything wrong, but please correct me if I'm being a dumb.

Below are my real use case diagram, but it's trivial.

![image](https://github.com/tailwindlabs/headlessui/assets/45784210/d0ce7983-ff4c-40b7-b61e-53f7950b56f4)

**Comment by thecrypticace** [comment] 2023-06-20 14:28
Thanks! This is a duplicate of #2546. We'll track it there.

**Closed by thecrypticace** 2023-06-20 14:28 UTC
