### ISSUE TITLE
Dialog throws error if there are no focusable elements

### ISSUE THREAD

**Issue by pradyuman** [tailwindlabs/headlessui#265] opened 2021-03-01 08:13 UTC
I get the following error if I create a Dialog with no interactive components (just text):
`Error: There are no focusable elements inside the <FocusTrap />`

**Comment by 3-Bluezzy** [comment] 2021-03-02 04:40
*

**Comment by jamby77** [comment] 2021-03-02 12:57
Installing via `yarn add @headlessui/react` does not provide Dialog component. How did you install it?

**Comment by ChristoRibeiro** [comment] 2021-03-02 13:40
> Installing via `yarn add @headlessui/react` does not provide Dialog component. How did you install it?

@jamby77 you can use it with:

`npm install @headlessui/react@dev`

or 

`yarn add @headlessui/react@dev`

**Comment by RobinMalfait** [comment] 2021-03-02 13:43
Hey! Thank you for your issue!
Much appreciated! 🙏

The error is thrown by design. Once you open a Dialog people should be able to interact with its contents and should not be able to escape it (unless pressing escape or using outside click).

What is your use case exactly?

**Comment by pradyuman** [comment] 2021-03-05 23:25
My use case was for displaying a Help Dialog when someone clicks an information bubble in the application. I ended up adding a close button to get around the issue, and you're probably right that it's good practice to make sure there's something interactive on the dialog.

It might be worth adding this to the documentation so that people know this is intended.

**Comment by davidalejandroaguilar** [comment] 2021-03-10 02:30
This error also happens on Next.js's hot reload. However, after you make a hard refresh, it works again. I'll try to make a sample repo later.

**Comment by RobinMalfait** [comment] 2021-03-12 17:12
I wrote about this behaviour in the docs, therefore I will close this issue. Thanks for the information!

**Closed by RobinMalfait** 2021-03-12 17:12 UTC
Labels: Needs more info

**Comment by mperrotti** [comment] 2021-04-07 00:13
@RobinMalfait - I've been getting this error in `@headlessui/react` when the component re-renders and then `isOpen` is set to `true` using state.

I'm able to work around this by conditionally rendering my component instead of letting the `open` prop show and hide the modal.

Example of my workaround:
```jsx
{isOpenState && (
    <Dialog open={true}>dialog content</Dialog>
)}
```

I'd much prefer to follow the docs and rely on the `open` prop, so I'd like to figure out what's going wrong.

---

Does this issue sound familiar? Do you think it's something with my usage?

I'll post another comment if I figure out what's wrong, and I'll open a PR if it's something in the Dialog component.

PS: +1 for this accessibility safeguard!

**Comment by edgarasben** [comment] 2021-04-14 18:44
I am getting the same error when trying to use Dialog component from @headlessui/react (https://headlessui.dev/react/dialog).

Other components work fine.

**Comment by Xairoo** [comment] 2021-04-14 22:05
You have to set `initialFocus` and also use it in your return code.

Based on the example code @ https://headlessui.dev/react/dialog#rendering-to-a-portal they forgot to place `ref={cancelButtonRef}` inside an element (doesn't have to be a button, could be a div or so too).
```
const cancelButtonRef = useRef();

...

initialFocus={cancelButtonRef}

...

<button
	ref={cancelButtonRef}
	type="button"
	className="inline-flex justify-center px-4 py-2 text-sm font-medium text-blue-900 bg-blue-100 border border-transparent rounded-md hover:bg-blue-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-500"
	onClick={closeModal}
>
	Got it, thanks!
</button>
```

**Comment by snowsea-dev** [comment] 2021-04-19 19:40
I met the same issue. I am working on Nextjs.

**Comment by edgarasben** [comment] 2021-04-19 20:30
@snowsea-dev the solution @Xairoo provided works well to me. thank you.

**Comment by snowsea-dev** [comment] 2021-04-23 01:07
When we put <Select /> component of material-ui in modal, it causes error.

**Comment by 1trackprojects1** [comment] 2021-05-09 21:02
I'm having the same issue but i have no clue whats wrong im using tailwindui's new react code for the navbar

**Comment by mkamran67** [comment] 2021-05-14 06:37
Tried that link with Next.js the ref did not solve it.

**Comment by seans84** [comment] 2021-05-23 22:59
What @1trackprojects1 has stated, your Dialog needs a focusable element within it. You can use a ref, or a semantic close button which is an implicit focusable element.

For example you can skirt this issue by adding this at the top of your modal:

```
                <div className="absolute top-1 right-1">
                  <button
                    type="button"
                    className="inline-flex justify-center px-2 py-1 text-sm font-medium text-gray-200 bg-gray-900 border border-transparent rounded hover:bg-gray-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-blue-500"
                    onClick={closeModal}
                  >
                    X
                  </button>
                </div>
```

**Comment by mxswat** [comment] 2021-05-25 12:23
Does not seem to work in my use case, I tried to replace an existing modal/dialog system. Where the content is loaded in an asynchronous way

I had to add a hidden button to solve this problem, since it was blocking the rendering
```
  public render(): JSX.Element {
    const isVisible = !!this.props.show
    // console.log(isVisible)
    return (
      <Dialog open={isVisible} onClose={() => this.state.isOpen = false} className="bg-background-tertiary fixed inset-0 m-28 overflow-y-auto z-10">
        <Dialog.Overlay />
        <div className='menu-layer' ref={this.setMenuLayer} />
        <div {...this.props}>
          {this.mMenuLayer !== null ? this.props.children : null}
        </div>
        <button className="focus-trap-bypass"></button> <-- hidden after the render is complete
      </Dialog>
    );
  }
```

**Comment by mxswat** [comment] 2021-05-25 12:43
I tried to replace an existing modal/dialog system. Where the content is loaded in an asynchronous way

I had to add a fake focus ref and then change it when the content is loaded, otherwise that error log will block my render
```
  public render(): JSX.Element {
    const isVisible = !!this.props.show
    
    return (
      <Dialog initialFocus={this.fakeRef} open={isVisible} onClose={() => this.state.isOpen = false} className="bg-background-tertiary fixed inset-0 m-28 overflow-y-auto z-10">
        <Dialog.Overlay />
        <div className='menu-layer' ref={this.setMenuLayer} />
        <div ref={this.fakeRef} tabIndex={-1} {...this.props}>
          {this.mMenuLayer !== null ? this.props.children : null}
        </div>
      </Dialog>
    );
  }
```

**Comment by DouglasCalora** [comment] 2021-05-30 19:24
This is very bad, what if I don't want a focusable element inside my dialog? Like a dialog only for showing text for example?

**Comment by DouglasCalora** [comment] 2021-05-30 21:55
Fixed with this workaround, added a button.
![image](https://user-images.githubusercontent.com/32134017/120121202-79491100-c178-11eb-814e-aea9e3340003.png)

**Comment by IRediTOTO** [comment] 2021-06-03 04:39
I get this error too, but sometimes it shown when I edit code and save file, just need refresh and no error :\ 
Don't know why

**Comment by Ghirigoro** [comment] 2021-06-05 13:49
I am getting this error when I **do** have a focusable element inside a dialog. Does the focusable element need to not be nested?

**Comment by ridhoajibx** [comment] 2021-06-05 14:02
> I'm having the same issue but i have no clue whats wrong im using tailwindui's new react code for the navbar
> 
> Re: FIXED IT!
> 
> for anyone else having same issue please go to https://headlessui.dev/react/dialog#managing-focus-within-your-dialog
> and see the `Managing focus within your dialog` section
> 
> add the ref and initialFocus to the elements as shown and the navigation issue should be fixed!

thanks bro, it's save me

**Comment by brandonparis** [comment] 2021-07-07 22:11
I'm having the same issue, but have tried pretty much all the solutions above. The Dialog crashes with the message above `Error: There are no focusable elements inside the <FocusTrap />` only when a particular `<input type="checkbox" />` is _unchecked_. Any idea what could be the issue here?

**Comment by Terkea** [comment] 2021-07-14 16:57
I found a way around that.

simply add a ref to the dialog and to a div inside the body


```
let refDiv = useRef(null)

<Dialog
	initialFocus={refDiv}
	as="div"
	className="fixed inset-0 z-10 overflow-y-auto bg-gray-500 bg-opacity-60"
	onClose={closeModal}
>

<div ref={refDiv}>
    {children}
</div>
...

**Comment by codal-Jamie** [comment] 2021-11-29 12:35
I was running into the same issue until I realized I was trying to display two Dialogs at once based upon the same state. Also, it's good practice to set an initial state using the useRef() hook when having more than Dialog on one page even though they might be in separate components.

**Comment by lorlab** [comment] 2021-12-30 09:35
I am seeing this warning when I open a modal that was not rendered on initial page load, but appears later. The modal has a button inside, but when I try to open it it throws the warning and does not appear. This doesn't happen if the modal is present on initial page load.

**Comment by jiblett1000** [comment] 2022-02-16 11:25
I'm getting this error when using :unmount="false" using nuxt3. Doesn't seem to affect functionality, just throws the error.

**Comment by bde-maze** [comment] 2023-01-09 14:31
> 

This is normal, for accessibility reasons you always want to have at least a close button

**Comment by StepRob** [comment] 2023-02-17 17:35
**Managing initial focus**
For accessibility reasons, your dialog should contain at least one focusable element. By default, the Dialog component will focus the first focusable element (by DOM order) once it is rendered, and pressing the Tab key will cycle through all additional focusable elements within the contents.
If you'd like something other than the first focusable element to receive initial focus when your dialog is initially rendered, you can use the initialFocus ref:
Check the documentation: [https://headlessui.com/react/dialog#managing-initial-focus](url)

**Comment by GoudekettingRM** [comment] 2024-02-13 15:27
I'm getting this error with the following component. There's clearly a button in there tho...

```ts
'use client';
import { Dialog, Transition } from '@headlessui/react';
import { ReactNode, useState } from 'react';

interface IGenericInfoModalProps {
  title: string;
  buttonText: string;
  children?: ReactNode;
}

const GenericInfoModal = ({ title, buttonText, children }: IGenericInfoModalProps) => {
  const [modalOpen, setModalOpen] = useState(false);

  return (
    <>
      <button
        type='button'
        className='text-gray-700 underline'
        onClick={() => {
          setModalOpen(true);
        }}
      >
        {buttonText}
      </button>

      <Transition show={modalOpen}>
        <Dialog
          open={modalOpen}
          onClose={() => {
            setModalOpen(false);
          }}
          className='fixed inset-0 z-50 lg:hidden'
        >
          <div className='min-w-screen flex min-h-screen sm:items-center sm:justify-center'>
            <Transition.Child
              enter='ease-out duration-200'
              enterFrom='opacity-0'
              enterTo='opacity-100'
              leave='ease-in duration-200'
              leaveFrom='opacity-100'
              leaveTo='opacity-0'
            >
              <Dialog.Overlay className='fixed inset-0 min-h-screen bg-gray-800 opacity-50' />
            </Transition.Child>

            <Transition.Child
              enter='transition ease-out duration-200'
              enterFrom='-translate-x-full sm:translate-x-0 sm:translate-y-1'
              enterTo='translate-x-0 sm:translate-y-0'
              leave='transition ease-in duration-200'
              leaveFrom='translate-x-0 sm:translate-y-0'
              leaveTo='-translate-x-full sm:translate-x-0 sm:translate-y-1'
            >
              <div
                className='
                  relative flex max-h-[calc(100vh-5rem-1px)] w-[calc(100vw-3rem)] min-w-[288px]
                  max-w-sm flex-col overflow-hidden rounded-br-lg bg-white text-sm
                  leading-relaxed shadow-xl sm:max-h-[calc(100vh-10rem)] sm:rounded-lg
                '
              >
                <div
                  className='
                    flex h-12 w-full shrink-0 items-center border-b border-gray-300
                    bg-white px-4 font-semibold text-slate-800
                  '
                >
                  <Dialog.Title className='text-base'>{title}</Dialog.Title>

                  <button
                    type='button'
                    className='
                      group -mr-2 ml-auto grid h-8 w-8 place-content-center
                      rounded-full transition-colors hover:cursor-pointer hover:bg-gray-100
                    '
                    onClick={() => {
                      setModalOpen((currentState) => !currentState);
                    }}
                  >
                    X
                  </button>
                </div>

                <div className='flex flex-1 flex-col overflow-y-auto pb-10 pt-6 text-default'>{children}</div>
              </div>
            </Transition.Child>
          </div>
        </Dialog>
      </Transition>
    </>
  );
};

export default GenericInfoModal;

```

**Comment by eddwinpaz** [comment] 2024-02-20 02:07
just in case anyone comes with this problem on Vue 3 , this worked for me.

`
let refDiv = useRef(null)

<Dialog
	initialFocus={refDiv}
	as="div"
	className="fixed inset-0 z-10 overflow-y-auto bg-gray-500 bg-opacity-60">

<div ref="refDiv">
   
</div>
`
