### ISSUE TITLE
[Bug]: Uncaught RangeError: Maximum call stack size exceeded. focusElement of Modal

### ISSUE THREAD

**Issue by tianyingchun** [tailwindlabs/headlessui#825] opened 2021-09-20 09:41 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.4.1

### What browser are you using?

chrome

### Reproduction repository

Not now.

### Describe your issue

while we create `Modal` multiple (2+) it will throw me 

```
focus-management.esm.js?d1e3:99 Uncaught RangeError: Maximum call stack size exceeded.
    at focusElement (focus-management.esm.js?d1e3:99)
    at eval (use-focus-trap.esm.js?25af:110)
    at handler (use-window-event.esm.js?b5e3:8)
    at focusElement (focus-management.esm.js?d1e3:99)
    at eval (use-focus-trap.esm.js?25af:110)
    at handler (use-window-event.esm.js?b5e3:8)
    at focusElement (focus-management.esm.js?d1e3:99)
    at eval (use-focus-trap.esm.js?25af:110)
    at handler (use-window-event.esm.js?b5e3:8)
    at focusElement (focus-management.esm.js?d1e3:99)
    at eval (use-focus-trap.esm.js?25af:110)
    at handler (use-window-event.esm.js?b5e3:8)
    at focusElement (focus-management.esm.js?d1e3:99)
    at eval (use-focus-trap.esm.js?25af:110)
    at handler (use-window-event.esm.js?b5e3:8)
    at focusElement (focus-management.esm.js?d1e3:99)
    at eval (use-focus-trap.esm.js?25af:110)
    at handler (use-window-event.esm.js?b5e3:8)
    at focusElement (focus-management.esm.js?d1e3:99)
    at eval (use-focus-trap.esm.js?25af:110)
```
[Screenshot here](https://pasteboard.co/C0itYZq2Hgsm.png)

BTW, can `Modal` need to provider flag props to disabled `focusElement` feature, in most case we don't need this, i think.

**Comment by kpratik2015** [comment] 2021-09-25 20:55
Faced this too. +1

**Comment by RobinMalfait** [comment] 2021-09-25 21:00
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is definitely an error that should be fixed, however the root cause is that you are rendering 2 dialogs as **siblings**, if you want nested dialogs, then you have to nest them inside one another, and not render them as a sibling.

The reason that this error is happening is because the dialog is implemented in a way so that if an element is being focused **outside** of a dialog, that the focus is restored into the dialog itself.
However, with 2 sibling dialogs this happens:
```
Dialog A has focus
Dialog B gets rendered, steals focus
Dialog A loses focus, thus tries to restore focus into A
Dialog B loses focus, thus tries to restore focus into B
Dialog A loses focus, thus tries to restore focus into A
Dialog B loses focus, thus tries to restore focus into B
Dialog A loses focus, thus tries to restore focus into A
Dialog B loses focus, thus tries to restore focus into B
...
```

**Comment by tianyingchun** [comment] 2021-11-01 10:36
what's progress of this issue

**Comment by gsidsid** [comment] 2021-11-05 17:14
Add an `initialFocus` prop to the dialog and set it to `document.activeElement`. For folks using vue:

```
<template>
    <Dialog as="div" class="fixed z-10 inset-0 overflow-y-auto" @close="open = false" :initialFocus="getActiveElement()">
   ...
    </Dialog>
</template>
<script>
...
   methods: {
       getActiveElement() {
           return document.activeElement;
       }
   }
...
</script>
```

**Comment by Mangor1no** [comment] 2021-11-18 12:33
> what's progress of this issue

@RobinMalfait replied the solution. Basically what you need to do is move one modal into other.

`<ModalOne><ModalTwo /></ModalOne>`

**Comment by kayvaninvemo** [comment] 2021-12-04 12:27
In our design we have stripe elements in a dialog, and stripe elements are rendered in iframe, the focus trap does not work well with iframe, i guess. That would be nice to have a "opt out of focus trap" option in dialogs.

**Comment by tianyingchun** [comment] 2021-12-05 01:08
provider option to disable focus trap is make sense, in some edge case, the focus element won't work i think.

**Comment by mockingjet** [comment] 2021-12-06 03:17
Same problem here. To be honest, I would rather abandon focus trap to prevent this error

**Comment by tianyingchun** [comment] 2021-12-06 09:32
Oh extra new `Component` named `FocusStrap` for Modal, if we need, we can place `FocusStrap` into Modal children props

**Comment by tejasupmanyu** [comment] 2021-12-11 09:02
Is there a fix to this? any workaround for react?

**Comment by obianachebe** [comment] 2021-12-18 05:10
I'm also experiencing issues with focus trap and Stripe elements in a dialog. When a Stripe element input component is currently focused and you then attempt to focus on another element outside of the Stripe iframe, the Stripe element will demand back focus making it so you won't move on to other components in a form. 

As @kayvaninvemo mentioned, I don't think FocusTrap plays well with iframes.

This happens sporadically on Chrome and consistently on Firefox.

Is there any workaround for this? I just need to be able to move my cursor through form elements without FocusTrap getting in the way.

**Comment by adamhp** [comment] 2022-01-23 17:58
I know this isn't ideal, but in my case, I have a confirmation modal that then opens another modal afterwards. I was running into this focus issue on Safari, but I added a slight timeout to the second modal, so that it basically waits for the other to be completely closed and unmounted (I think?).

Something like
```javascript
<Confirm onConfirm={() => { setTimeout(openOtherModal, 500) }}/>
```

Like I said, not ideal, but may help in certain cases that can deal with the timeout.

**Comment by Mhmdhammoud** [comment] 2022-01-29 14:12
> I'm also experiencing issues with focus trap and Stripe elements in a dialog. When a Stripe element input component is currently focused and you then attempt to focus on another element outside of the Stripe iframe, the Stripe element will demand back focus making it so you can’t move on to other components in a form.
> 
> As @kayvaninvemo mentioned, I don't think FocusTrap plays well with iframes.
> 
> This happens sporadically on Chrome and consistently on Firefox.
> 
> Is there any workaround for this? I just need to be able to move my cursor through form elements without FocusTrap getting in the way.

I've experienced the same issue, please let me know if this get's fixed anytime soon.

**Comment by memiljamel** [comment] 2022-02-23 07:17
@Mhmdhammoud  if you don't use transition component it should work but if you use transition component make sure on TransitionRoot component apply props :show and also on Dialog component apply props :open with same value.

**Comment by RobinMalfait** [comment] 2022-03-04 09:15
Hey! Thank you for your bug report!
Much appreciated! 🙏

For everyone finding this issue.

The problem: You want 2 Dialogs, but it won't work
Solution: Dialogs **must** be nested if you want multiple Dialogs. Dialogs can't be siblings because if you happen to open them at the same time each Dialog will try to steal focus again because a Dialog should be considered a separate page where you can't interact with the content behind it.

**Closed by RobinMalfait** 2022-03-04 09:15 UTC

**Comment by MLDMoritz** [comment] 2022-03-06 15:01
This shouldn't be closed. There should be a proper solution for Dialogs that get opened one after another or at least proper reporting of how to resolve the issue.

**Comment by ThenTech** [comment] 2022-03-09 22:15
I also continue to run into this, each dialog is always sibling in a portal outside of root, as they can be opened by global methods and are not redefined in other components.

My use case is a base modal that has a form the user can fill in, and on error, I show another modal with the error message, thus creating a second sibling, triggering the focus loop when the error modal closes.

Setting `initialFocus={document.activeElement}` does not seem to work. (React)

Can't we just disable the Dialog component from trying to get focus in the first place? Like mentioned by @mockingjet and @tianyingchun, the FocusTrap behaviour could be opted out of.

**Comment by tianyingchun** [comment] 2022-03-10 05:40
now i resolved this issue, close previous dialog before  new dialog open.

**Comment by fedorinoGore** [comment] 2022-03-28 14:21
@RobinMalfait Guys, this is a real issue. Having modals as siblings is not a whim it is a real requirement. Please provide an option to disable this behaviour...

**Comment by M1ck0** [comment] 2022-04-06 11:13
Workaround for this.

Set `open` prop on `Modal` to `false` and it will work without throwing that error. If anyone knows why it behaves this way, comment please.

**Comment by wrod7** [comment] 2022-04-11 02:18
im having this issue when i have a Dialog inside a Tab.List

**Comment by solomonhawk** [comment] 2022-04-20 17:39
👍  Building a payments form inside an accessible dialog - using Stripe Elements (which renders its own inputs inside iframes) results in some serious issues related to focus management. Is there anything that can be done?

**Comment by Mhmdhammoud** [comment] 2022-04-21 09:40
> 👍 Building a payments form inside an accessible dialog - using Stripe Elements (which renders its own inputs inside iframes) results in some serious issues related to focus management. Is there anything that can be done?

I had the same issue with Stripe element, but it only happens on Firefox
Try Google Chrome it's working just fine there....

**Comment by RobinMalfait** [comment] 2022-04-21 09:54
@solomonhawk try installing the [insiders](https://github.com/tailwindlabs/headlessui#installing-the-insiders-version) build

**Comment by kayvaninvemo** [comment] 2022-04-21 10:45
> > 👍 Building a payments form inside an accessible dialog - using Stripe Elements (which renders its own inputs inside iframes) results in some serious issues related to focus management. Is there anything that can be done?
> 
> I had the same issue with Stripe element, but it only happens on Firefox Try Google Chrome it's working just fine there....

It has also issue on Chrome, if you notice the "tab" key does not work smoothly, I should press tab key 2 times to go to the next card element.

**Comment by solomonhawk** [comment] 2022-04-21 12:20
> @solomonhawk try installing the [insiders](https://github.com/tailwindlabs/headlessui#installing-the-insiders-version) build

Thank you for the suggestion.

Unfortunately `insiders` doesn't seem to have any impact in my case. Tabbing through the stripe elements fields still doesn't work properly. 

For a little more context: I use the individual `CardNumberElement` / `CardExpiryElement` / `CardCvcElement`, wrapped in a custom connected form field component.

The issue in my case is that focus never leaves the card input (or it continuously is re-focused when attempting to tab past).

I tried `insiders` and saw no change in this behavior. I also tested with Stripe's all-in-one `CardElement` (combined input for card number/expiry/cvc) without my custom component wrapper and the issue was mostly the same except I can tab through card number and expiry but focus gets "stuck" on the CVC input (which is the last input inside the iframe).

**Comment by solomonhawk** [comment] 2022-04-21 15:22
I spent a little time trying to dig deeper and wasn't able to come to any conclusions. Interestingly, `react-modal` does not exhibit the same issue (but also traps focus). I'd really prefer not to introduce another separate dependency strictly for modals with worse accessibility but this is currently a huge blocker for the project I'm working on.

Appreciate all the hard work that goes into maintaining this library 🙏

**Comment by RobinMalfait** [comment] 2022-04-21 21:16
@solomonhawk sorry to hear about that. Can you create and share a reproduction repo / CodeSandbox that showcases the issue(s)?

**Comment by solomonhawk** [comment] 2022-04-27 16:21
@RobinMalfait I hope to find time to create a minimal reproduction, but I'm not sure when I'll be able to. Appreciate the reply!

**Comment by acatalina** [comment] 2022-05-03 07:24
hey @solomonhawk, I came across this issue as I had the same problem with stripe elements and the dialog. Just tried 1.6.0 and it solved the issue although I cannot use the new Dialog.Panel as it triggers the onClose method on the Dialog while clicking around. Hope it helps

**Comment by mreduar** [comment] 2022-05-05 21:35
> Add an `initialFocus` prop to the dialog and set it to `document.activeElement`. For folks using vue:
> 
> ```
> <template>
>     <Dialog as="div" :initialFocus="getActiveElement()">
>    ...
>     </Dialog>
> </template>
> <script>
> ...
>    methods: {
>        getActiveElement() {
>            return document.activeElement;
>        }
>    }
> ...
> </script>
> ```

This trick works to avoid the error, but it seems that the recursion problem still affects the performance and also if the page has scroll it is not possible to scroll after the modal is closed.

**Comment by mreduar** [comment] 2022-05-05 22:18
> hey @solomonhawk, I came across this issue as I had the same problem with stripe elements and the dialog. Just tried 1.6.0 and it solved the issue although I cannot use the new Dialog.Panel as it triggers the onClose method on the Dialog while clicking around. Hope it helps

I confirm that this is solved by upgrading to the latest version.

**Comment by moseskamau338** [comment] 2022-08-16 15:45
We really need a permanent solution to this issue. I have the latest release installed and tried the `activeElement` trick but I still have this issue. I have a scenario where I must use modals as siblings otherwise I would have to re-organize the whole application codebase.

Please assist if you can.

**Comment by sgarcia-dev** [comment] 2023-08-21 14:54
> @RobinMalfait Guys, this is a real issue. Having modals as siblings is not a whim it is a real requirement. Please provide an option to disable this behaviour...

While I (and the community) strongly agrees with this being a real requirement, it's an open source library maintained for free, and we have no right to demand anything.

HOWEVER, I do think it's both deceiving, and dangerously close to a lie-by-omission that the [Dialog (Modal) docs on headlessui.com](https://headlessui.com/react/dialog) _do not ever mention_ this limitation. Despite its massive impact on how large scale web applications are architected. If there are no plans to add support for multiple modal support as siblings, we should at the bare minimum communicate this **publicly** and loudly instead of burying this valuable piece of information in a Closed issue.

I went ahead and created https://github.com/tailwindlabs/headlessui/issues/2689 in hopes of giving this issue some closure.

**Comment by pinguluk** [comment] 2023-09-21 09:16
For me it was caused due a misconfiguration in webpack, that caused the Modal to be rendered twice https://github.com/mui/material-ui/issues/24641#issuecomment-1729167309
