### ISSUE TITLE
Form isn't submitted when focused on toggle/radio group and pressing enter

### ISSUE THREAD

**Issue by henribru** [tailwindlabs/headlessui#394] opened 2021-04-18 11:56 UTC
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.0.0

### What browser are you using?

Firefox

### Reproduction repository

https://codesandbox.io/s/blue-grass-g6j68?file=/src/App.vue

If you press enter while focused on native radio and checkbox components in a form, the form gets submitted. This is not the case for the Headless UI toggle and radio group components.

**Comment by adamlindqvist** [comment] 2021-04-28 11:09
Experiencing the same behavior in the react package.

**Comment by RobinMalfait** [comment] 2021-04-28 11:26
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed in v1.1.1, can you verify if that works for you @adamlindqvist?

**Comment by prophet1996** [comment] 2021-05-24 08:04
tested, works fine on 88.0 firefox, ubuntu

**Comment by henribru** [comment] 2021-05-24 15:43
> tested, works fine on 88.0 firefox, ubuntu

I'm using the exact same setup without it working unfortunately :/

**Comment by RobinMalfait** [comment] 2022-03-04 11:11
Hey! Thank you for your bug report!
Much appreciated! 🙏

Yep this is currently a limitation because our components that contain data (`Listbox`, `Switch`, `Combobox` and `RadioGroup`) currently don't use native form elements behind the scenes. This is a feature I want to tackle in the near future. The idea would be if you put a `name="..."`* prop on the component, that it will use a proper native form element.

\*API is not set in stone and can still change.

Going to close this for now since it is not a bug, but just an unimplemented feature.

**Closed by RobinMalfait** 2022-03-04 11:11 UTC
