### ISSUE TITLE
ESLint - Vue - Linting errors with HeadlessUI using "reserved" names

### ISSUE THREAD

**Issue by OliverRC** [tailwindlabs/headlessui#3014] opened 2024-02-28 14:13 UTC
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2923

<div type='discussions-op-text'>

<sup>Originally posted by **OliverRC** January 10, 2024</sup>
I have been doing some ESLint setup on an existing project and am getting errors on some of the HeadlessUI components.

Some examples
```
error  Name "Dialog" is reserved in HTML  vue/no-reserved-component-names
error  Name "Menu" is reserved in HTML  vue/no-reserved-component-names
error  Name "Switch" is reserved  vue/no-reserved-component-names
```

This is quite interesting; while it's okay for me to alias the components, it makes copying and using code a bit harder.
~~Ignoring the linting error also feels a little heavy-handed.~~
EDIT: In fact, it does not even look like you can disable this in `eslint-plugin-vue`
https://eslint.vuejs.org/rules/no-reserved-component-names.html
https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/no-reserved-component-names.js#L114

What do you think the best approach here is?</div>

**Comment by adamwathan** [comment] 2024-02-28 14:22
Going to close this in favor of the discussion since it's not a bug 👍

**Closed by adamwathan** 2024-02-28 14:22 UTC

**Comment by OliverRC** [comment] 2024-02-28 14:24
Cool but I've had zero feedback to the discussion... I agree with closing it as long as there is some actual discourse on the strategy one can use.
