### ISSUE TITLE
prevent dialog and transition go to the top of the page

### ISSUE THREAD

**Issue by jdortegar** [tailwindlabs/headlessui#1283] opened 2022-03-29 23:35 UTC
### Discussed in https://github.com/tailwindlabs/headlessui/discussions/1089

<div type='discussions-op-text'>

<sup>Originally posted by **Siumauricio** February  5, 2022</sup>
Are there are any way to prevent the transition makes dialog or any component go to at the top of the page?
I just want the component stay at the same position where dialog or any component opened

```js
const NavbarMenu = ({ isOpen, menuClick }) => {
  return (
    <Transition appear={true} show={isOpen}>
      <Transition.Child
        class="flex flex-col bg-yellow-700 fixed top-0 right-0 p-5 z-20 w-1/2 h-full transition ease-in-out duration-300"
        enter="transition-opacity ease-in-out duration-700"
        enterFrom="translate-x-full"
        enterTo="translate-x-0"
        leave="transition-opacity ease-out duration-700"
        leaveFrom="opacity-100"
        leaveTo="opacity-0"
      >
        <Exit className="text-yellow-100 w-1/6" onClick={() => menuClick()} />
        <div className="flex flex-col gap-y-4 mt-10 font-poppins font-bold text-xl text-yellow-100">
          <span>About</span>
          <span>About</span>
          <span>About</span>
        </div>
      </Transition.Child>
    </Transition>
  );
};
```
</div>

**Comment by RobinMalfait** [comment] 2022-03-30 12:12
Hey! Thank you for your bug report!
Much appreciated! 🙏

Initially this looks like a duplicate of #983

However, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Closed by RobinMalfait** 2022-03-30 12:12 UTC
