### ISSUE TITLE
[react] Static Option on Listbox breaks keyboard accessibility

### ISSUE THREAD

**Issue by matt-morris** [tailwindlabs/headlessui#148] opened 2020-11-16 17:39 UTC
Not sure if this is a bug or if I'm misunderstanding the feature, but we're running into an issue with the focus trap when using the `static` property. 

The goal is to have an always open select menu, so, my first instinct was to simply not render the button and make the menu static.  Example: https://codesandbox.io/s/jovial-sanne-2x7iz?file=/src/App.js

This works great, except we realized that the focus trap is still present, regardless of state, so if you use the static option, you can't tab past the menu.
Example: https://codesandbox.io/s/modest-wiles-id8qu?file=/src/App.js

Is there a plan for this sort of thing already? Are we just abusing this component? I guess I'm just trying to figure out whether this is an opportunity to improve the Listbox, if there's something on the roadmap already for this use case, or if we should be making our own component for this.

**Comment by RobinMalfait** [comment] 2020-11-30 12:38
Hey! Thank you for your bug report!
Much appreciated! 🙏

It feels like you are abusing the component a bit.
But I am curious about the exact use case you have for a select component being always open?

Currently we don't have the option to allow for multiple selected items in a listbox.
With that in mind, it seems like you want a group of radio inputs? 🤔

**Comment by matt-morris** [comment] 2020-12-02 20:55
Yeah, a radio button group is actually what we've gone with for now, but it's not ideal for a couple of reasons. First, when the group has focus, although you can navigate through it with arrow keys, each option is actually selected as you move through it. 

We're using it to set a current filter for a list of items with an animated layout, so if a user arrows through options quickly, the reflows begin to look a little jarring. 

![radio-button-group-example-00](https://user-images.githubusercontent.com/3513140/100928729-d2730900-34a3-11eb-808e-9409aa03a946.gif)

It's not the end of the world, obviously, but it's also not the best UX. It's much smoother to be able to let the user navigate the options before selecting it. 

The other reason we're not thrilled with radio buttons is that it turns out there's a surprising amount of cross-browser weirdness with them. I hadn't ever realized until now how disjointed it actually is until I started looking into this issue. In Chrome, clicking one of the radio buttons focuses the group, but not in Safari or Firefox. Chrome and Firefox both cycle through the list while Safari stops at either end. Again, none of this is the absolute worst, but it's enough to make think about a headless menu component where we can normalize and control this stuff. 

The `Listbox` with a `static` menu is _almost_ perfect for our use case, if we could just turn off the focus trap. No worries if that's not in the cards right now. I just wanted to bring it up here. We're very invested in the possibilities of this library, and so we're looking to help out however we can. We build and manage hundreds of websites with similar content but different styles, so the headless approach is very freeing for us.

**Comment by RobinMalfait** [comment] 2021-01-29 12:29
Hey! Thanks for the extra information. I feel like the `Listbox` is not really suited for this, but I could be wrong. Opting out of the focus-trap _feels_ like a smell to me that we might need another type of component for this (again could be wrong here).

@davidluhr given the above information, from an accessibility perspective as well, do you know of any suitable components for the behaviour they want? Is Listbox without a focus trap a "good" solution here, or are there more preferable ones?

**Comment by davidluhr** [comment] 2021-01-29 21:02
@matt-morris Looking at the recording you provided, it seems that the left column is likely a sidebar navigation. It be best to simply provide a list of links that change the route and animate the new results on the route change. This would be useful for users who want to navigate specifically to a particular category (each category has its own URL).

Listboxes assume that the menu is hidden until revealed with a dedicated trigger button, hence the focus cycling/trapping. If the menu is always shown, and there is no trigger button, I agree with @RobinMalfait that this is not well suited for a Listbox, and instead should just be static content on the page.

**Comment by RobinMalfait** [comment] 2021-01-30 15:32
Hey! I am going to close this issue now, because I don't think it will be a good idea to provide an option to disable the focus trap (because of the aforementioned reasons). Thanks!

**Closed by RobinMalfait** 2021-01-30 15:32 UTC

**Comment by sp88011** [comment] 2022-06-04 22:32
@RobinMalfait I'm running into a similar case here where I like to have a multi-select list. 

Listbox seems almost perfect, except for the focus issue described by OP. 

(RadioGroups don't work because they only allow a single select)

I believe this is a common use. Am I missing an obvious solution?

**Comment by RobinMalfait** [comment] 2022-06-05 10:40
@sp88011 please open a new issue with a reproduction repo / CodeSandbox attached.
