### ISSUE TITLE
[Bug]: Cannot close Dialog with ESC when dialog buttons is not focused

### ISSUE THREAD

**Issue by molteber** [tailwindlabs/headlessui#606] opened 2021-06-09 08:32 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v1.2.0

### What browser are you using?

Chrome Version 91.0.4472.77 (Official Build) (64-bit)

### Reproduction repository

https://github.com/molteber/headless-ui-react-dialog-esc-bug

### Describe your issue

I want to allow closing of a dialog when the user press the `ESC` key. This works only when an element inside the dialog is focused it seems.
I was expecting it to also work then buttons inside the dialog is not focused.

I tried looking up if dialogs is supposed to behave like this, but i did no go too deeply into my research and did not find anything about it

**Comment by RobinMalfait** [comment] 2021-06-09 13:45
Duplicate of #524

**Closed by RobinMalfait** 2021-06-09 13:45 UTC

**Comment by molteber** [comment] 2021-06-09 13:58
Ah, issue didn't show up on searching for `esc`. Thanks
