### ISSUE TITLE
Open to collaborators?

### ISSUE THREAD

**Issue by jnarowski** [tailwindlabs/headlessui#264] opened 2021-02-27 16:10 UTC
I love this project idea and am basically doing the same thing in my own project for Vue. Figured it might be easier with two folks to at least cover the base components.

Let me know if you're interested in some help on the Vue project.

**Comment by RobinMalfait** [comment] 2021-03-05 20:24
Hey! Thank you for your question!
Much appreciated! 🙏

Currently we are focusing on the components we need and we are having a bunch of internal discussions where we discuss the API and how it should behave. This means that currently opening up for new components are a bit hard. We are open for suggestions of new components though! That being said we are open for PR's that fix certain bugs and that have an issue linked (so that we can have a conversation before somebody does a bunch of work. If it turns out that we don't want to support feature X that would be annoying for anyone involved).

Adam also talked a bit about this here: https://github.com/tailwindlabs/headlessui/issues/58#issuecomment-704398729

---

Duplicate of #58, #133

**Closed by RobinMalfait** 2021-03-05 20:24 UTC
