### ISSUE TITLE
Space character ignored by the Text input when used inside Radio-Group option

### ISSUE THREAD

**Issue by karthikarul20** [tailwindlabs/headlessui#1758] opened 2022-08-11 07:12 UTC
**What package within Headless UI are you using?**

@headlessui/react

**Describe your issue**

I use input box inside the radio-group option and it does not accept "space" characters typed in it.
This is a screenshot on how my Text Input looks inside the Radio-Group option.
![Screenshot 2022-08-11 at 3 09 31 PM](https://user-images.githubusercontent.com/5412806/184081658-e587b978-e8eb-4042-9235-20a18adb4ac6.png)

This is because the radio-group is listening for the keydown event and handles the logic for up/down/left/right arrow and space keys.
https://github.com/tailwindlabs/headlessui/blob/b28d177a95d45aa101cc959385ca9d019e13616f/packages/%40headlessui-react/src/components/radio-group/radio-group.tsx#L243-L255

Because of this, I cannot enter any space in my text input and I dont see any solution for this.

Please suggest if there is any workaround for this problem.

**Comment by hussamkhatib** [comment] 2022-08-11 08:37
can you mention steps to reproduce the issue ?

**Comment by RobinMalfait** [comment] 2022-08-11 08:50
Hey! Thank you for your bug report!
Much appreciated! 🙏

The RadioGroup component exists to replace the native `<input type="radio" />` that you can style. The `space` character is used to select the active RadioGroup Option. 

Using an input inside your `RadioGroup.Option` doesn't semantically make much sense because that would be the equivalent of doing this:

```html
<input type="radio">
  <input type="text" />
</input>
``` 

Instead, render the `input` for your message as a sibling and only show it based on the selected `RadioGroup` option.

Going to close this since this is not a bug, just misuse of the component.
Hope this helps!

**Closed by RobinMalfait** 2022-08-11 08:50 UTC

**Comment by Tylerian** [comment] 2022-10-05 12:46
> Using an input inside your RadioGroup.Option doesn't semantically make much sense because that would be the equivalent of doing this: 
> ```html
> <input type="radio">
>  <input type="text" />
> </input>
> ```

Following that logic we shouldn't either be able to introduce normal html inside `RadioGroup.Option` since `input` elements of type `radio` never expects children at all.

That said, there are cases where we need to introduce inputs within this component (like the one example OP posted, or in my case a [checkout form with multiple payment options](https://user-images.githubusercontent.com/1430805/194061169-4060f307-4173-42d5-ad39-a2088a7810b6.png)) and it shouldn't be a problem at all. 

What's the reason behind `preventDefault`ing space keystroke events? If the form is rendered inside a `RadioGroup.Option` that is already selected, it shouldn't affect its behavior to bubble up the event so other components can intercept it.

@karthikarul20 As a workaround, I propose you intercept `onKeyDown` events on your affected inputs and call `stopPropagation()` on them  so they don't get intercepted by the `RadioGroup.*` components and get `preventDefault`ed.
