### ISSUE TITLE
[Combobox] Arrow up/down is prevented default and stopped propagation

### ISSUE THREAD

**Issue by cabello** [tailwindlabs/headlessui#1718] opened 2022-07-26 19:02 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.6.0

**What browser are you using?**

N/A

**Reproduction URL**

https://github.com/cabello/headlessui-combobox-arrows-bug/tree/main

Screenshot of the repository

<img width="1286" alt="CleanShot 2022-07-26 at 14 55 56@2x" src="https://user-images.githubusercontent.com/60936/181089598-9848fc00-306d-4fc1-a8ed-73783fe3b10d.png">

**Describe your issue**

I used Combobox to build an Emoji autocomplete.

<img width="334" alt="CleanShot 2022-07-26 at 13 30 55@2x" src="https://user-images.githubusercontent.com/60936/181089684-19e5cf98-3fc2-40cd-a6cd-c18bfd0ae88b.png">

It worked like a charm, the accessibility is there, tab, enter, keys works as expected, however I noticed that I can no longer navigate the textarea using arrow up/down keys, only left/right.

I suspect the `preventDefault` and `stopPropagation` from this code chunk: https://github.com/tailwindlabs/headlessui/blob/6598db59b7c2d78d00bab4c9c9314a526ddb79e6/packages/%40headlessui-react/src/components/combobox/combobox.tsx#L656-L683

I am considering alternatives as this might not be what the Combobox was designed for. It's a mix of Popover + Combobox.

**Comment by RobinMalfait** [comment] 2022-07-27 10:00
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is indeed expected behaviour, let's imagine that we did allow for arrow up and arrow down inside the textarea than this would happen:

- On arrow up, your cursor would jump AND your selection would change
- On arrow down, your cursor would jump AND your selection would change

That doesn't feel correct / intuitive. To "solve" this, you could either disable the default arrow key support and move the selection (what we do with the Combobox), or you could keep the default arrow key support and disable the selection of the active combobox option.

This has issues on its own, because then you are basically removing keyboard support of the Combobox and you can only choose Combobox items via the mouse.

Another solution could be that we give more control on when to open the Combobox exactly (when you focus the input, when you type a specific character, ...) but that's currently out of scope and we currently don't have plans to change this behaviour.

So going to close this right now with a won't fix, but you might be able to revisit this approach once we have more control on when the combobox opens.

**Closed by RobinMalfait** 2022-07-27 10:00 UTC

**Comment by cabello** [comment] 2022-07-27 16:44
My user experience is so close to being perfect though.

When the Combobox is open everything works as expected, you go up and down options, you press Enter to select one or Tab.

I control when to show options using a sequence detection, `:` followed by two characters, then I filter the list of emojis and display them to the user.

The keyboard a11y is there, works like a charm.

If I could control the behaviour of the keystrokes when the Combobox is closed, then it would work in a two-dimensional input like text-area. Otherwise the `as=` prop should only receive an Input, styled Input or a descendant of Input.

This is part of the code I use to do keystroke detection:
```tsx
const onLocalKeyDown =
  (activeOption: string | number | ReadonlyArray<string>) =>
  (event: KeyboardEvent<HTMLTextAreaElement>) => {
    if (showEmojiPicker) {
      if (event.key === Keys.Colon) {
        // This is the second : if there is an exact match, use it.
        const emoji = filteredEmojis.find(
          (emoji) => emoji.id === emojiQuery
        );
        if (emoji != null) {
          onEmojiSelect(emoji.native);
          event.preventDefault();
          return;
        } else {
          setEmojiQuery(null);
        }
      }

      if (event.key === Keys.Tab && activeOption != null) {
        // Selects the emoji and prevents tab from moving focus
        // to next element.
        onEmojiSelect(activeOption.toString());
        event.preventDefault();
        setEmojiQuery(null);
        return;
      }

      if (event.key === Keys.Enter) {
        // Don't send the enter up the chain causing the message
        // to be posted because the user just selected an emoji.
        return;
      }

      if (event.key === Keys.ArrowLeft || event.key === Keys.ArrowRight) {
        // Similar to Slack we close the autocomplete on lateral arrows.
        setEmojiQuery(null);
        return;
      }
    }

    onKeyDown(event);
  };
```
