### ISSUE TITLE
Popover graphical flicker - iOS Safari

### ISSUE THREAD

**Issue by longfellowone** [tailwindlabs/headlessui#1341] opened 2022-04-16 03:09 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0

**What browser are you using?**

Safari

**Reproduction URL**

`https://github.com/longfellowone/gwe.git`

`git checkout d9e61da`

**Describe your issue**

Two issues

1. Flickering when opening hamburger menu with Popover component (code was pulled from tailwindui)
2. Popover component does not work with React 18

https://user-images.githubusercontent.com/36570412/163659147-557b4450-86d7-4e08-a769-7247c19588d6.MP4

**Comment by RobinMalfait** [comment] 2022-04-20 12:46
Hey! Thank you for your bug report!
Much appreciated! 🙏

Would love to take a look but it seems that your repo either doesn't exist or is not public. Could you make it public so that we can take a look?

**Comment by RobinMalfait** [comment] 2022-04-28 11:52
Hey!

Going to close this since no reproduction has been provided. If you still have this issue, feel free to open a new issue with a reproduction repo / CodeSandbox attached.

**Closed by RobinMalfait** 2022-04-28 11:52 UTC
Labels: Needs more info
