### ISSUE TITLE
NextJS build breaks when upgrade 1.4.3 to 1.5.0

### ISSUE THREAD

**Issue by just-mitch** [tailwindlabs/headlessui#1235] opened 2022-03-11 21:43 UTC
**What package within Headless UI are you using?**

For example: @headlessui/react

**What version of that package are you using?**

Upgrading from @headless/react 1.4.3 to 1.5.0

**What browser are you using?**

N/A

**Reproduction URL**

I created a blank repo to reproduce this, but couldn't.

**Describe your issue**

I'm using a https://nx.dev/ monorepo to build a nextjs app (v12.1.0), and when I upgrade from 1.4.3 to 1.5.0 and try to build, I get the following: 
```
info  - Creating an optimized production build  
info  - Compiled successfully
Cannot read property 'FREE' of undefined
info  - Collecting page data .TypeError: Cannot read property 'FREE' of undefined
    at .../.next/server/chunks/7066.js:1703:73
    at Function.__webpack_require__.a (.../.next/server/webpack-runtime.js:103:13)
    at Object.413 (.../.next/server/chunks/7066.js:1695:21)
    at __webpack_require__ (.../.next/server/webpack-runtime.js:25:42)
    at .../.next/server/chunks/7066.js:1681:69
    at Function.__webpack_require__.a (.../.next/server/webpack-runtime.js:103:13)
    at Object.1441 (.../.next/server/chunks/7066.js:1673:21)
    at __webpack_require__ (.../.next/server/webpack-runtime.js:25:42)
    at .../.next/server/chunks/7066.js:1463:91
    at Function.__webpack_require__.a (.../.next/server/webpack-runtime.js:103:13)
```

I'm not sure how to give any more context or help- very happy to assist as I'd like to use the Tab as a controlled component!

**Comment by RobinMalfait** [comment] 2022-03-11 22:22
Hey!

`Cannot read property 'FREE' of undefined` doesn't seem like a Headless UI issue.
That said, make sure to nuke your caches (e.g.: `rm -rf .next node_modules`).

Since you can't reproduce it on a fresh project I'm pretty sure it is cache related.

**Comment by just-mitch** [comment] 2022-03-13 16:51
@RobinMalfait I tried those suggestions and got the same error.

**Comment by RobinMalfait** [comment] 2022-03-16 14:19
Hey!

If you can't reproduce it then it is impossible for us to help you. 
I'm going to close this issue for now, if it is still relevant for you I would encourage you to find a way to reproduce it so that we can help you.

**Closed by RobinMalfait** 2022-03-16 14:19 UTC
Labels: Needs more info
