### ISSUE TITLE
Tabs content disappear when AMP is enabled

### ISSUE THREAD

**Issue by nyedidikeke** [tailwindlabs/headlessui#778] opened 2021-08-31 05:05 UTC
**What component (if applicable)**
- URL for category: https://headlessui.dev/react/tabs
- Component name: Tab

**Describe the bug**
When AMP is enabled, contents for tabs disappears.

**To Reproduce**

1. Create an [amp-first](https://github.com/vercel/next.js/tree/canary/examples/amp-first) Next.js project by running the command below.
```sh
npm create-next-app --example amp-first amp-first-app
```

2. Install Tailwind UI by running commands below as described at https://tailwindui.com/documentation
```sh
npm install tailwindcss@latest @headlessui/react @heroicons/react
```

3. Under the `pages/` directory, edit `index.js` using the [basic Headless UI tab example](https://headlessui.dev/react/tabs#basic-example) with AMP enabled as below.
```jsx
// /pages/index.js
import { Tab } from '@headlessui/react'

export const config = { amp: true }

export default function MyTabs() {
  return (
    <Tab.Group>
      <Tab.List>
        <Tab>Tab 1</Tab>
        <Tab>Tab 2</Tab>
        <Tab>Tab 3</Tab>
      </Tab.List>
      <Tab.Panels>
        <Tab.Panel>Content 1</Tab.Panel>
        <Tab.Panel>Content 2</Tab.Panel>
        <Tab.Panel>Content 3</Tab.Panel>
      </Tab.Panels>
    </Tab.Group>
  )
}
```

4. Load Tailwind sheet on server side under `pages/_document.js`.

5. Run `npm run dev` then visit http://localhost:3000 in your browser.

**Expected behavior**
Should work as is when AMP is disabled.

**Screenshots**
Image showing the bug
![With AMP enabled](https://i.stack.imgur.com/u5L6k.png)

Image of expected behaviour
![With AMP disabled](https://i.stack.imgur.com/DtPTb.png)

**Browser/Device (if applicable)**

**Additional context**

**Comment by RobinMalfait** [comment] 2022-02-21 17:16
Hey! Thank you for your bug report!
Much appreciated! 🙏

This is related to the server side rendering issue we have for the tabs component. Going to close this as a duplicate of #1086

**Closed by RobinMalfait** 2022-02-21 17:16 UTC
