### ISSUE TITLE
Combobox with immediate does not re-open after selecting a value

### ISSUE THREAD

**Issue by jimmyzzxhlh** [tailwindlabs/headlessui#3477] opened 2024-09-12 00:57 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

2.1.6

**What browser are you using?**

Chrome

**Reproduction URL**

[Codesandbox](https://codesandbox.io/p/sandbox/react-typescript-forked-d9ym3x?workspaceId=ef53bec0-6ff1-4548-9063-2d0ce32d1a31&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0yknvnu00063b6jw56g7sum%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0yknvnu00023b6jsjoz0zr3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0yknvnu00033b6jzbbgbjtj%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0yknvnu00053b6jbzcr4azq%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0yknvnu00023b6jsjoz0zr3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0yknvnu00013b6js6fngdk3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0yko0ft00023b6jlec32dh8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0yknvnu00023b6jsjoz0zr3%2522%252C%2522activeTabId%2522%253A%2522cm0yko0ft00023b6jlec32dh8%2522%257D%252C%2522cm0yknvnu00053b6jbzcr4azq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0yknvnu00043b6jbn3g18f4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522cm0yknvnu00053b6jbzcr4azq%2522%252C%2522activeTabId%2522%253A%2522cm0yknvnu00043b6jbn3g18f4%2522%257D%252C%2522cm0yknvnu00033b6jzbbgbjtj%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0yknvnu00033b6jzbbgbjtj%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Describe your issue**

If I have `immediate` on the Combobox, I would expect every time when the combobox is clicked on, the drop down always shows up.
However, if I select a value from the combobox, and then click on the combobox again, since the focus has not gone away from the combobox, the drop down does not show up.
I have to click somewhere else and then click on the combobox to re-focus and get the dropdown.

**Comment by RobinMalfait** [comment] 2024-09-12 09:43
Hey!

The `immediate` prop opens the combobox when the input receives focus. When the combobox is open and you make a selection (using the mouse or keyboard), in both scenarios the combobox input still has the focus, so nothing changes.

That said, the moment you start typing, or press arrow down, the combobox will re-open again.
More info: https://headlessui.com/react/combobox#opening-the-dropdown-on-focus

Closing because this works as designed.

Hope this helps!

**Closed by RobinMalfait** 2024-09-12 09:43 UTC

**Comment by jimmyzzxhlh** [comment] 2024-09-12 15:38
I'm not sure if this is the right design however. The behavior is more intuitive and more consistent to open the combobox dropdown *whenever* it is being clicked on, regardless of whether it has been focused on or not.

**Comment by florianbepunkt** [comment] 2024-10-14 05:37
@RobinMalfait Depending on how the combox box is used, this design results either in a good or bad user experience. Therefore I kindly ask to revisit the design choice or make it configurable so it is up to the implementing party to decide.

Broadly speaking I see two sorts of user stories:

1. Long list or complex options. User selects mainly by typing. The current implementation works great here.
2. Combobox is used as a shiny select replacement. Few options. User mainly navigates by clicking. Current implementation works not so great here, as @jimmyzzxhlh pointed out, it is quite unintuitive. Power users are used to keyboard navigation. Casual users probably not.

Besides: What intention does a click on an already focused input convey? Did the user clicked there by accident? Or because the user wanted to see the available choices again? I think the latter is true most of the time.
