### ISSUE TITLE
[Bug]: Working in development but not in production

### ISSUE THREAD

**Issue by ahmedsamirdev** [tailwindlabs/headlessui#660] opened 2021-07-02 19:06 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.3.0

### What browser are you using?

chrome

### Reproduction repository

https://codesandbox.io/s/nameless-fog-2k3ur?file=/components/Nav.js

### Describe your issue

I have problem with "(Disclosure) from @headlessui/react" doesn't work.. this in dev mode (nextjs) deplyed in vercel

![123513373-3a31b100-d68d-11eb-86bc-577e0c3b612e](https://user-images.githubusercontent.com/16477954/124318707-56e05400-db79-11eb-90c3-73934f4eb464.png)
and this in production and after pushing the code successfully
![123513374-3e5dce80-d68d-11eb-885e-f02f96007610](https://user-images.githubusercontent.com/16477954/124318739-65c70680-db79-11eb-91af-ea45adc2aef0.png)

Here's the code ..
https://codesandbox.io/s/nameless-fog-2k3ur?file=/components/Nav.js

deployed code .. 
https://ahmedsamir.dev/test

**Comment by ahmedsamirdev** [comment] 2021-07-02 19:20
I found out the problem was the purge in tailwind.config.js
```  purge: ['./pages/**/*.js', './components/**/*.js', './layouts/**/*.js'],```
and ofc when I remove the purge it affects the site badly on mobile
why?

**Comment by adamwathan** [comment] 2021-07-03 19:42
Hey! Please provide an actual reproduction repository — if you're saying the issue is the `purge` stuff then the Codesandbox is missing a lot of important information because there is no `tailwind.config.js` file provided.

A GitHub repo of the actual Next.js is needed to really see what's going on.

Since this is a styling related thing that is fixed by editing your Tailwind config, it's definitely not a bug with Headless UI itself, so going to convert to a discussion.

**Closed by adamwathan** 2021-07-03 19:42 UTC
