### ISSUE TITLE
[Bug]: Dialog/TransitionRoot does not animate when launched from inside `MenuItem`

### ISSUE THREAD

**Issue by grantholle** [tailwindlabs/headlessui#456] opened 2021-04-27 09:46 UTC
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.1.0

### What browser are you using?

Chromium

### Reproduction repository

https://youtu.be/oMOIPmf_ij0

### Describe your issue

I'm using a `Menu` to launch [this slideout](https://tailwindui.com/components/application-ui/overlays/slide-overs#component-4d1d575bd79eef81afc9a4f2e1900ecb). I'm using the same function between buttons. The slideout doesn't animate when from inside a `MenuItem` component, but does with a regular button.

This doesn't animate

```vue
<MenuItem v-slot="{ active }">
  <button
    :class="[
      active ? 'bg-fuchsia-500 dark:bg-fuchsia-600 text-white' : 'text-gray-900 dark:text-gray-100',
      'group flex rounded-md items-center w-full px-2 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-gray-300 dark:focus:ring-gray-500',
    ]"
    @click.prevent="togglePermissions(user)"
  >
    Permissions
  </button>
</MenuItem>
```

This does

```vue
<button @click="togglePermissions(users.data[0])">
  Click
</button>
```

Sorry about the lack of repo, hopefully the video is enough to go off of. Both the dropdown and menu were lifted straight from the example.

**Comment by syropian** [comment] 2021-06-13 21:11
Also ran into this today! I'm opening a dialog from a `MenuItem` and it doesn't animate in, but it _does_ animate out. Other dialogs triggered outside `MenuItem` animate in/out as normal.

**Comment by hfalucas** [comment] 2021-07-19 17:04
Any of you guys found a solution?

**Comment by grantholle** [comment] 2021-07-20 00:00
Yes, build my own slide out component haha. Still no tailwindui solution.

**Comment by OwenVey** [comment] 2021-07-22 19:59
Took a while to figure out this was my problem with the enter animation not triggering for Dialog but I am seeing this as well. Im using Vue 3.0.5 with headless UI 1.3.0.

**Comment by hfalucas** [comment] 2021-07-23 09:42
I solved it by making the button the parent element. Still can't really understand why it solved the problem.
```
<button @click.prevent="togglePermissions(user)">
    <MenuItem v-slot="{ active }">
        <span :class="[ active ? '...' : '...']"> Permissions</span>
    </MenuItem>
</button>
```

**Comment by gerardojbaez** [comment] 2021-09-09 19:44
Adding a timeout to open the modal/slideover seems to also solve the issue: 

```javascript
confirmDelete() {
    setTimeout(() => openSlideOver.value = true, 100)
}    
```
I'm curious as to why this is happening.

**Comment by thamyzoom** [comment] 2021-09-09 22:05
😃

**Comment by rbluethl** [comment] 2021-11-07 15:37
Any news? I'm having the same issue - the enter transition of my slide over is not working.

**Comment by rbluethl** [comment] 2021-11-07 15:50
> Adding a timeout to open the modal/slideover seems to also solve the issue:
> 
> ```js
> confirmDelete() {
>     setTimeout(() => openSlideOver.value = true, 100)
> }    
> ```
> 
> I'm curious as to why this is happening.

This is strange - this does indeed work, although a bit hacky.

**Comment by rbluethl** [comment] 2021-11-07 16:06
I can confirm that this happens when there is both a `<Menu>` (+ `MenuButton` and `MenuItems`/`MenuItem`) and a `SlideOver` in the same component. When I remove the Menu, the SlideOver transition works as expected.

**Comment by michalurva** [comment] 2021-11-12 19:21
Same issue here. But opening Slideover based on passed prop from InertiaJS request.
```javascript
setup(props) {
  const openModal = toRef(props, 'open')
  return {
    openModal,
  }
}
```
Using this solution it works as expected.
> Adding a timeout to open the modal/slideover seems to also solve the issue:
> 
> ```js
> confirmDelete() {
>     setTimeout(() => openSlideOver.value = true, 100)
> }    
> ```
> 
> I'm curious as to why this is happening.

**Comment by RobinMalfait** [comment] 2022-03-04 11:01
Hey! Thank you for your bug report!
Much appreciated! 🙏

Here is an example implementation for opening a Dialog from the Menu: https://codesandbox.io/s/epic-haibt-e9eixy?file=/src/components/HelloWorld.vue

It includes a button to open the Dialog itself, this will showcase the normal behaviour.
It also includes a Menu with a single Menu Item. This item will open the Dialog (and also close itself).

A few important parts to keep in mind:
- Use the Transition components from Headless UI
- Make sure to remove the `open` and `static` props from the Dialog. This will be handled internally by the Transition component (they communicate with eachother). This is important to get the timing right, otherwise the Dialog will open instantly regardless of the `Transition`.

If you have other issues, please open a new issue with a minimal reproduction repo / codesandbox attached. If you create a CodeSandbox, I created 2 templates.
- React + Tailwind CSS
- Vue 3 + Tailwind CSS
<img width="697" alt="image" src="https://user-images.githubusercontent.com/1834413/156751655-e0a1effd-615c-4275-8190-266b81746141.png">


They should both be public.

**Closed by RobinMalfait** 2022-03-04 11:01 UTC

**Comment by andreassoegaard** [comment] 2022-06-25 11:58
This bugged me for several hours - tried to follow all the suggestions here and @RobinMalfait's great example - but nothing seemed to help.

So for anyone in the same boat:

When opening slideovers/popups etc., the first focusable element is automatically focused by the Dialog component.

When I removed all focusable elements inside the Slideover, the animation worked again. I think there is an initialFocus setting on the Dialog component to control this - but I didn't have luck using it. And I don't know why the focused element in this way cancels the animation.

Since I needed my focusable elements and couldn't just remove them (checkboxes in this case), I put a v-if="mounted" on them:

```html
...
<input v-if="mounted" type="checkbox" />
...
```

```javascript
import { ref } from 'vue'

const mounted = ref(false)
onMounted(() => { mounted.value = true })
```

Might be a bit of a hack - but now my slideover is animating both in and out, and I'm happy.

Hope it can help someone!
