### ISSUE TITLE
@headlessui/react v1.5.0 has broken tree-shaking

### ISSUE THREAD

**Issue by vikuscz** [tailwindlabs/headlessui#1299] opened 2022-04-02 08:22 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.5.0

**Describe your issue**

With v1.5.0 tree-shaking seems broken. I encounter that in some larger project with nextjs, so I tried reproduce it with minimal setup with just vite, react, typescript and one Listbox component from examples in your website, and it has same behaviour. With v1.4.3 it is ok, but with v1.5.0 it bundles whole @headlessui/react which is obvious from bundle analyzer printscreens below. Is this bug or intended behaviour for this new release?

***v1.4.3***

![v1 4 3](https://user-images.githubusercontent.com/44908888/161373794-13e1e01a-1d69-4957-ae38-f51b1ee1156c.png)

***v1.5.0***

![v1 5 0](https://user-images.githubusercontent.com/44908888/161373795-4096866d-af68-46f1-b671-79c1a37b191b.png)

**Comment by adamwathan** [comment] 2022-04-02 10:32
Duplicate of https://github.com/tailwindlabs/headlessui/issues/1238

**Closed by adamwathan** 2022-04-02 10:32 UTC
