### ISSUE TITLE
[Menu Button] Pressing Enter doesn't navigate to the item, it only closes the menu

### ISSUE THREAD

**Issue by santicros** [tailwindlabs/headlessui#20] opened 2020-09-29 07:26 UTC
Version: @headlessui/react@v0.1.3

Hey there! First thanks for your amazing job. I'm sure this will be a library that will be a must in all my projects.

I have a Menu with Next.js Links inside. When I click one item with the mouse it navigates to the page perfectly. However, clicking enter with the mouse, when one item is "active" only closes the menu, like ESC does. I believe ENTER should go to the item, so I think this is a bug 🐛

Thanks!!

**Comment by RobinMalfait** [comment] 2020-09-29 08:01
Hey! Can you provide a codesandbox or similar that showcases this issue?
I have this codesandbox where I attached an onClick to the `account settings` and the `support` items and they both seem to work as expected: https://b6xje.csb.app/

**Comment by santicros** [comment] 2020-09-30 15:46
Sure @RobinMalfait.
Here I send you a demo: https://929l7.sse.codesandbox.io/

It's the same as the react one in Nextjs. With the mouse it works the click, but with ENTER it doesn't.

Thanks so much!

**Comment by RobinMalfait** [comment] 2020-09-30 15:56
Thank you for the repro case!

The issue is that we put props on the Link itself, but Next doesn't forward all of it to the actual underlying `a` tag (or it can't merge some of them like the `onClick` we provide).

I have a working example here: https://owvp3.sse.codesandbox.io/

### The key take away here is:

#### 1. Add a custom NextLink where we ensure that all props are forwarded to the `a` directly.

```js
function NextLink(props) {
  const { href, children, ...rest } = props;
  return (
    <Link href={href}>
      <a {...rest}>{children}</a>
    </Link>
  );
}
```

#### 2. Use the new `NextLink` component, put all the props on that component, and drop the intermediate `a` (since it is now part of the `NextLink`)
```js
<Menu.Item>
  {({ active }) => (
    <NextLink
      href="support"
      className={`${
        active ? "bg-gray-100 text-gray-900" : "text-gray-700"
      } flex justify-between w-full px-4 py-2 text-sm leading-5 text-left`}
    >
      Account settings
    </NextLink>
  )}
</Menu.Item>
```

---

Does this help?

**Comment by santicros** [comment] 2020-09-30 16:04
Wow! That was so fast!!
Great, the solution is perfect for what I needed. Thanks!!!! 
Will be interesting to add it to the docs in the future :D

**Comment by RobinMalfait** [comment] 2020-09-30 16:56
Perfect, glad it worked out! Going to close this. If you have other issues please open a new issue!

**Closed by RobinMalfait** 2020-09-30 16:56 UTC
Labels: question

**Comment by joeynenni** [comment] 2020-11-30 22:55
Wow, this was super helpful! I was stuck on this for awhile and got super close, my code was exactly the same minus the `{..rest}` trick. I also had to remove the `as="div"` attribute I had on my `Menu.Item` that I had added earlier because it was making other things work. Everything works great now using your example, thanks!

**Comment by jcamato** [comment] 2021-10-03 03:27
> Thank you for the repro case!
> 
> The issue is that we put props on the Link itself, but Next doesn't forward all of it to the actual underlying `a` tag (or it can't merge some of them like the `onClick` we provide).
> 
> I have a working example here: https://owvp3.sse.codesandbox.io/
> 
> Does this help?

Hi @RobinMalfait,

I followed your example exactly after already trying the one [here](https://headlessui.dev/react/menu#integrating-with-next-js), and I keep getting the following error. Is this a known issue with Headless UI and Next js? 

![error](https://user-images.githubusercontent.com/10441545/135738298-b9944682-684e-4627-9184-16a34a464a0b.png)
?

**Comment by RobinMalfait** [comment] 2021-10-03 09:15
@jcamato there might be another issue in your code. Could you create a minimal reproduction repo and share it? Maybe open a new issue so that we can focus on it, instead of working on old/resolved issues.

**Comment by jcamato** [comment] 2021-10-03 16:34
@RobinMalfait, absolutely! I will work on that, thank you.

**Comment by ReeceTrolley-HRS** [comment] 2022-10-03 15:57
> Thank you for the repro case!
> 
> The issue is that we put props on the Link itself, but Next doesn't forward all of it to the actual underlying `a` tag (or it can't merge some of them like the `onClick` we provide).
> 
> I have a working example here: https://owvp3.sse.codesandbox.io/
> 
> ### The key take away here is:
> #### 1. Add a custom NextLink where we ensure that all props are forwarded to the `a` directly.
> ```js
> function NextLink(props) {
>   const { href, children, ...rest } = props;
>   return (
>     <Link href={href}>
>       <a {...rest}>{children}</a>
>     </Link>
>   );
> }
> ```
> 
> #### 2. Use the new `NextLink` component, put all the props on that component, and drop the intermediate `a` (since it is now part of the `NextLink`)
> ```js
> <Menu.Item>
>   {({ active }) => (
>     <NextLink
>       href="support"
>       className={`${
>         active ? "bg-gray-100 text-gray-900" : "text-gray-700"
>       } flex justify-between w-full px-4 py-2 text-sm leading-5 text-left`}
>     >
>       Account settings
>     </NextLink>
>   )}
> </Menu.Item>
> ```
> 
> Does this help?

For anybody getting a error with `ref`s using this method, the below code works for me using next@12.2.3.

![image](https://user-images.githubusercontent.com/109088124/193622666-ca67912f-e2c5-4f76-a59a-e52bf8807ba5.png)

```tsx
import Link from 'next/link';
import React, { HTMLAttributes, LegacyRef } from 'react';
import { UrlObject } from 'url';

const NextLink = React.forwardRef((
  props: HTMLAttributes<HTMLAnchorElement> & { href: string | UrlObject },
  ref: LegacyRef<HTMLAnchorElement>
) => 
{
  const { href, children, ...rest } = props;
  return (
    <Link href={href}>
      <a {...rest} ref={ref}>{children}</a>
    </Link>
  );
});

NextLink.displayName = "NextLink";

export default NextLink;
```
