### ISSUE TITLE
headlessui portal root causes layout issues in some cases

### ISSUE THREAD

**Issue by MarkMurphy** [tailwindlabs/headlessui#2924] opened 2024-01-11 14:45 UTC
@headlessui/react
v2.0.0-alpha.4

My project was laid out like the following:

```react
<body className="grid grid-rows-[auto,_1fr] h-full overflow-y-scroll">
  <Header />
  <Main />
</body>
```

Because of the grid layout on the body, the headless-portal-root element would cause the content to jump whenever it's added to the body.

```html
<div id="headlessui-portal-root">...</div>
```

This is more of an FYI than anything. I ended up just wrapping my content in a div and putting the layout classes on that instead. i.e.

```react
<body className="h-full overflow-y-scroll">
  <div className="grid grid-rows-[auto,_1fr] h-full">
    <Header />
    <Main />
  </div>
</body>
```

It may also be worth mentioning that the portal root seems to be prepended to the body rather than appended. This causes issues with inherent  z-indexes such that a listbox in my header will appear behind a button rendered in my main content.

**Comment by RobinMalfait** [comment] 2024-01-15 22:42
Hey!

Thanks for the heads up, we made this trade-off because a lot of tools (and browser extensions) inject themselves at the end of the body already. In general I think that the solution you came up with (a dedicated spot for your app) is the way to go and keeping the body untouched for the most part (except for some (min)height/scrolling just like you did).

The part does confuse me is this:
> It may also be worth mentioning that the portal root seems to be prepended to the body rather than appended.

Because we explicitly _do_ append things:
- https://github.com/tailwindlabs/headlessui/blob/aff438eb06f6b39da041d56d6506c0c0c9ef8646/packages/%40headlessui-react/src/components/portal/portal.tsx#L47
- https://github.com/tailwindlabs/headlessui/blob/aff438eb06f6b39da041d56d6506c0c0c9ef8646/packages/%40headlessui-react/src/components/portal/portal.tsx#L55
so I wonder if our code is running _before_ any of your code is running and that your code is appending to the body and therefore _after_ the portal root. 🤔

This seems a bit odd because the portal root should only be created once an actual Dialog opens and therefore your page should already exist, I think.

If you are running into issues because of this, can you open a new issue for that use case with a minimal reproduction repo attached? 

For the main issue, I'm going to close this issue for now because the solution you came up with is what I would have suggested to do as well. If more people run into this, then we can revisit and maybe even move the portal root between the `body` and the `html` but that sounds like another can of worms to investigate and would love to not do that at this point yet.

Hope this helps!

**Closed by RobinMalfait** 2024-01-15 22:42 UTC
