### ISSUE TITLE
nuxt 3 RC 7 Error: Cannot find module Combobox.js

### ISSUE THREAD

**Issue by agracia-foticos** [tailwindlabs/headlessui#1760] opened 2022-08-11 13:44 UTC
I have installed Nuxt 3 RC 7.

**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

"version": "1.6.7",

**What browser are you using?**

Chrome

**Describe your issue**

When i run the server with "npm run dev" throws this error in the console.
If i transpile the package in nuxt config, the server will run, but throws other errors

**Comment by agracia-foticos** [comment] 2022-08-11 13:47
the full trace of error:
 ERROR  Cannot start nuxt:  Error: Cannot find module /@fs/home/foticos/var/www/wanapix_next/node_modules/@headlessui/vue/dist/components/combobox/combobox.js imported from file:///home/foticos/var/www/wanapix_next, file:///home/foticos/var/www/, file:///home/foticos/var/www/wanapix_next/_index.js, file:///home/foticos/var/www/node_modules

  at resolvePath (node_modules/mlly/dist/index.mjs:1079:10)
  at isValidNodeImport (node_modules/mlly/dist/index.mjs:1329:30)
  at isExternal (node_modules/externality/dist/index.mjs:122:49)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async transformRequest (node_modules/@nuxt/vite-builder/dist/chunks/dev-bundler.mjs:43:7)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/chunks/dev-bundler.mjs:75:15)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/chunks/dev-bundler.mjs:84:5)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/chunks/dev-bundler.mjs:84:5)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/chunks/dev-bundler.mjs:84:5)
  at async transformRequestRecursive (node_modules/@nuxt/vite-builder/dist/chunks/dev-bundler.mjs:84:5)

**Comment by RobinMalfait** [comment] 2022-08-11 13:58
Hey! Thank you for your bug report!
Much appreciated! 🙏

Headless UI definitely exports things correctly, some things you can try:
1. Make sure you have everything installed.
2. Make sure you don't have any (incorrect) caches going on.
3. Remove caches just in case.

We recently fixed a Vite issue, so you could play with the `insiders` build and see if that fixes things in your scenario.

Since no reproduction repo has been provided, I'm going to close this and hope that the above guesses can help you out. If it doesn't work, please open a new issue with a reproduction repo attached so that we can take a look.

Hope this helps!

**Closed by RobinMalfait** 2022-08-11 13:58 UTC
