### ISSUE TITLE
[Bug]: Stacking Dialog: There are no focusable elements inside the <FocusTrap />

### ISSUE THREAD

**Issue by trueninjaturtle** [tailwindlabs/headlessui#413] opened 2021-04-20 17:01 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

v0.3.1

### What browser are you using?

Chrome

### Reproduction repository

TBA

### Describe your issue

Hi,

I'm trying to have 2 Dialogs on the same page. The result is that when firing the second Dialog, it always throws the "There are no focusable elements inside the <FocusTrap />". Is this a limitation?

**Comment by Krystofee** [comment] 2021-04-21 07:15
I think I've opened issue about the same thing a day before, have a look at it - https://github.com/tailwindlabs/headlessui/issues/407.

This error happens when there is no focusable element inside Dialog. If there is, Dialogs can be stacked arbitrarily.

**Comment by trueninjaturtle** [comment] 2021-04-21 10:17
Hi @Krystofee 

Thanks for your reply. I tried a lot of options with Buttons, <Dialog.Title> etc, and opening the 2 Dialogs standalone, they work and open nicely. When trying to open along eachother, the last opened crashes with the message.

**Comment by 0xktz** [comment] 2021-04-21 11:29
Try adding tabIndex={n} to a couple of divs inside the dialog just in case

**Comment by RobinMalfait** [comment] 2021-04-21 12:15
Hey! Thank you for your bug report!
Much appreciated! 🙏

Opening multiple Dialogs should be possible. This is a duplicate of #407 so going to close this one.

**Closed by RobinMalfait** 2021-04-21 12:15 UTC
