### ISSUE TITLE
HeadlessUI Modal problem with 3rd party components

### ISSUE THREAD

**Issue by eskiesirius** [tailwindlabs/headlessui#1252] opened 2022-03-17 22:08 UTC
I tried using datepicker of flowbite and tw-elements inside the modal and yet datepicker didn't work properly.

**Comment by RobinMalfait** [comment] 2022-03-17 22:57
Hey! Thank you for your bug report!
Much appreciated! 🙏

I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

At first sight, this looks like a duplicate of https://github.com/tailwindlabs/headlessui/issues/432

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

**Closed by RobinMalfait** 2022-03-17 22:57 UTC

**Comment by eskiesirius** [comment] 2022-03-23 19:59
It is different.. please check it here.. https://codesandbox.io/s/elegant-rumple-p7z1r5?file=/src/App.vue

I have 2 datepicker.. outside the modal and inside modal.. outside modal is working but the inside isn't
