### ISSUE TITLE
[Vue] Menu - Manually closing stopped working since v1.7.8

### ISSUE THREAD

**Issue by NicolaiHorlacher** [tailwindlabs/headlessui#2546] opened 2023-06-20 11:25 UTC
**What package within Headless UI are you using?**

@headlessui/vue

**What version of that package are you using?**

v1.7.14

**What browser are you using?**

Chrome, Firefox

**Reproduction URL**

https://stackblitz.com/edit/headlessui-menu-item-close-bug?file=src%2FApp.vue

**Describe your issue**

Closing menus manually doesn't work since release v1.7.8 of @headlessui/vue.
This functionality is especially useful for Link-Components that use `event.preventDefault()` like `router-link` of `vue-router`.

In the example the menu does not close when the router link entry is clicked.
If the HeadlessUI version is pinned to 1.7.7, everything works just fine.

Docs for reference:
https://headlessui.com/vue/menu#closing-menus-manually

**Comment by RobinMalfait** [comment] 2023-06-28 13:45
Hey, thank you for this bug report! 🙏

A bit of a story on this topic, let's dive in! So by default the `Menu` component closes if an item inside is invoked (e.g.: a `button` or an `a`). Sometimes you want the `Menu` _not_ to close, and since closing the `Menu` is a default behaviour of our `Menu` component, we added the additional API where if you run `event.preventDefault()` that _you_ are in control of closing the `Menu` yourself. A use case for this is making an API call and showing a spinner, and once everything is done, then you can close the `Menu`.

This brings us to the part where you run into the issue you are having. Typically most router implementations intercept `<a>` clicks and use `e.preventDefault()` to prevent a full page refresh. To solve this we expose the `close` function such that you can still call it to close the `Menu` manually.

This is also where the fun happens, it looks like the incoming `@click` isn't called by `vue-router`. There might be some improvements that we can do within Headless UI itself but for now there are a few options you can choose:

1. Use `@click.capture="close"` this allows you to call the `close` function in the capturing phase of the event instead of the bubbling phase.
2. Use `@mousedown="close"` this uses a different event than `click` that is `defaultPrevented` by `vue-router`.

Here is a little demo based on your StackBlitz with various solutions: https://stackblitz.com/edit/headlessui-menu-item-close-bug-uwmgmk?file=src%2FApp.vue

Hope this helps for now!

**Closed by RobinMalfait** 2023-06-28 13:45 UTC

**Comment by NicolaiHorlacher** [comment] 2023-07-04 10:24
Thanks for the reply and provided example.

I like the solution with `@click.capture="close"`. Listening to other events like click is a bit messy when accessibility is a requirement.

Curiously, the example with `@click.capture="close"` doesn't work in Firefox. If I downgrade the version of HeadlessUI to 1.7.7, the example works again in Firefox.

Something seems to be wrong with Firefox, HeadlessUI and `event.preventDefault()` in combination.

Do you have any further insides? Some changes in HeadlessUI 1.7.8 seem to have altered the interaction with `preventDefault` and I'm still not sure if this is intentional or a bug.

**Comment by PatFox** [comment] 2023-08-10 09:19
I can confirm that while `@click.capture` works in Chrome, it does not work in Firefox. Also, using `@mouseodown` seems to prevent the link from functioning. I don't think this issue should be marked as 'closed'

**Comment by andredewaard** [comment] 2023-08-31 09:02
This indeed fixes the bug in Chrome but it still doesn't work in Firefox.

**Comment by NicolaiHorlacher** [comment] 2023-11-21 07:38
I stumbled upon this issue again, because I'm still stuck on the relatively old `v1.7.7` of HeadlessUI and encountered other issues that are already fixed in newer versions.

I agree with @PatFox and think it is a good idea to open the issue again in order find a solution to the root cause of the problem.

It seems like the bug was introduced in #2138. Unfortunately these changes affect the inner workings of HeadlessUI, so I don't feel confident to fix it myself.

@RobinMalfait I would appreciate if you could have another look at this.
