### ISSUE TITLE
headlessui-portal-root randomly disapperars from dom on react 18

### ISSUE THREAD

**Issue by lionelhorn** [tailwindlabs/headlessui#2379] opened 2023-03-18 09:43 UTC
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
1.7.13

**What browser are you using?**
Chrome 113.0.5660.0

**Reproduction URL**
I understand why you would want a reproduction and I will try to provide one if the info described below isn't enough to inform you.
Give the apparently random nature of the issue.

Could it be related in some ways to https://github.com/tailwindlabs/headlessui/issues/1407 ?

**Describe your issue**
#### When using Dialog Using react 18.2.0 with the older react render API the `<div id="headlessui-portal-root">` randomly disappears from the dom as shown in the video below
```ts
const root = createRoot(document.getElementById(`root`));
root.render(<App />);
```
`react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
p`

<video src="https://user-images.githubusercontent.com/50528276/226097614-28235265-1f08-4463-8665-6358d408cdbc.mp4" controls="controls" style="max-width: 1100px;"/>

**Comment by lionelhorn** [comment] 2023-03-18 09:45
#### When changing the <App/> render with 
```ts
const root = createRoot(document.getElementById(`root`));
root.render(<App />);
```

The Dialog and portal stays in the dom.

<video src="https://user-images.githubusercontent.com/50528276/226098019-aa742445-bb63-43a6-9a57-1d438ef44a32.mp4" controls="controls" style="max-width: 1100px;" />

**Comment by thecrypticace** [comment] 2023-03-18 11:54
@lionelhorn 

1. A project that can reproduce the issue is always useful to us — even if it's showcasing a behavior that has some randomness attached to it. It saves us setup time as some issues could potentially be related to or caused by project-specific settings or set up.
2. You uploaded the same video in both comments by accident:

<img width="613" alt="Screen Shot 2023-03-18 at 07 49 52" src="https://user-images.githubusercontent.com/614993/226103970-6b3cf909-3243-442d-a3cc-1fd9899d969a.png">

**Comment by RobinMalfait** [comment] 2023-03-22 12:48
Hey, thank you for this bug report! 🙏

It looks like when you used the newer way of setting up React DOM that it seems to work as expected.

Going to close this issue for now. If using the new method doesn't work for you or you have other issues then please open a new issue with a minimal reproduction repo attached so that we can take a look.

**Closed by RobinMalfait** 2023-03-22 12:48 UTC
