### ISSUE TITLE
Nested Popovers no longer work on version 1.7.8

### ISSUE THREAD

**Issue by alex-ketch** [tailwindlabs/headlessui#2292] opened 2023-02-17 18:19 UTC
Encountered this just now and seems like the discussion should be an issue instead.
Can try and investigate sometime over the coming weekends if desired.

### Discussed in https://github.com/tailwindlabs/headlessui/discussions/2221

<div type='discussions-op-text'>

<sup>Originally posted by **THowland1** January 28, 2023</sup>
### Summary
With the latest update of 1.7.8, when using React 17, Popovers inside another Popover's Panel don't have IDs on the buttons, which makes them unable to open the next level down
![image](https://user-images.githubusercontent.com/39370163/215295594-7bdfd926-4ca7-4a8d-8773-9ba309b814fd.png)

### Minimal Repro:
"react": "^17.0.1",
"react-dom": "^17.0.1",
"@headlessui/react": "1.7.8"
https://codesandbox.io/p/sandbox/nifty-benz-jq19yx?selection=%5B%7B%22endColumn%22%3A44%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A44%2C%22startLineNumber%22%3A2%7D%5D&file=%2Fsrc%2FApp.tsx

### Another minimal repro
"react": "^18.0.1",
"react-dom": "^18.0.1",
"@headlessui/react": "1.7.8"
https://codesandbox.io/p/sandbox/charming-river-dut1og?selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A9%7D%5D&file=%2Fpackage.json

### Working Repro (old version)
"react": "^17.0.1",
"react-dom": "^17.0.1",
"@headlessui/react": "1.7.7"
https://codesandbox.io/p/sandbox/zealous-sinoussi-68j10g?selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A15%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A15%7D%5D&file=%2Fpackage.json</div>

**Comment by RobinMalfait** [comment] 2023-02-17 18:26
Hey! Thank you for your bug report!
Much appreciated! 🙏

Going to close this as a duplicate of #2285

**Closed as completed** 2023-02-17 18:26 UTC
