### ISSUE TITLE
Maximum call stack size exceeded with sibling Modals

### ISSUE THREAD

**Issue by vpaul18** [tailwindlabs/headlessui#907] opened 2021-11-03 09:36 UTC
This issue has also been mentioned in #825, but no solution has been given, and, as a result, I have opened a new issue on it. How do you actually solve the focus problem when you render sibling modals?

I have a list, whose items can be updated within the modal. Whenever an items needs to be updated , a modal pops up and then closes. As a result of this, I must have sibling Modals, not nested ones. How to solve it ? Thanks!

Uncaught RangeError: Maximum call stack size exceeded.
    at focusElement (focus-management.ts:102)
    at use-focus-trap.ts:139
    at handler (use-window-event.ts:13)
    at focusElement (focus-management.ts:102)
    at use-focus-trap.ts:139
    at handler (use-window-event.ts:13)
    at focusElement (focus-management.ts:102)
    at use-focus-trap.ts:139
    at handler (use-window-event.ts:13)
    at focusElement (focus-management.ts:102)
    at use-focus-trap.ts:139
    at handler (use-window-event.ts:13)
    at focusElement (focus-management.ts:102)
    at use-focus-trap.ts:139
    at handler (use-window-event.ts:13)
    at focusElement (focus-management.ts:102)
    at use-focus-trap.ts:139
    at handler (use-window-event.ts:13)
    at focusElement (focus-management.ts:102)

**Comment by RobinMalfait** [comment] 2021-11-03 10:07
Hey! Thank you for your bug report!
Much appreciated! 🙏

The other issue you mentioned is still open. Therefore going to close this as a duplicate of #825. Opening multiple issues for the same issue won't help, thanks.

**Closed by RobinMalfait** 2021-11-03 10:07 UTC
