### ISSUE TITLE
[bug] weird(cannot) scroll after two dialog intersect showing

### ISSUE THREAD

**Issue by Ding-Fan** [tailwindlabs/headlessui#1698] opened 2022-07-19 10:28 UTC
https://github.com/tailwindlabs/headlessui/blob/5af3bd4b7164a0205ac70c179d8e9651afbb0a72/packages/%40headlessui-react/src/components/dialog/dialog.tsx#L254

- DialogA:LoadingMask shows
- do some fetching
- done fetching
- DialogB:Confirmation shows
- DialogA:LoadingMask hides
  - expected: `html style` has `overflow:hidden`
  - actually: `html style` is empty
- click confirm
- DialogB:Confirmation hides
  - expected: `html style` is empty
  - actually: `html style` has `overflow:hidden`

**Comment by timmaier** [comment] 2022-07-26 02:19
This is happening for me too in vue with headless v 1.6.7.

When two modals are open and both are closed one after the other the overflow: hidden remains on the outter html tag

**Comment by timmaier** [comment] 2022-07-26 06:04
Here's a reproduction link:
[https://stackblitz.com/edit/vitejs-vite-bbesl5?file=src/App.vue](url)

**Comment by Ding-Fan** [comment] 2022-07-26 08:38
I'm using this as a workaround

```ts
        // prevent scroll bug
        // https://github.com/tailwindlabs/headlessui/issues/1698
        const HTMLDOM = document.querySelector('html')

        if (HTMLDOM) {
          // https://stackoverflow.com/a/67384208/6236633
          // HTMLDOM.style = ''
          HTMLDOM.setAttribute('style', '')
        }
```

**Comment by thecrypticace** [comment] 2022-07-28 13:26
@timmaier I can't reproduce this with your stackblitz (also the url in the markdown is not filled in 😄)

Perhaps I'm doing something wrong here tho?

https://user-images.githubusercontent.com/614993/181515965-625e3038-95a6-47c2-b287-a6f348991362.mov

**Comment by timmaier** [comment] 2022-07-29 05:11
Hmm that's the exact use case I tested here is a screen recording of the behaviour this stackblitz: https://stackblitz.com/edit/vitejs-vite-bbesl5?file=README.md

![modal_scroll_bug](https://user-images.githubusercontent.com/19884817/181687106-32d897cb-2878-4f7c-a94f-7bc9c115b071.gif)


I'm using chrome: Version 102.0.5005.115 (Official Build) (arm64)

**Comment by timmaier** [comment] 2022-07-29 05:14
Okay I think it only seems to only happen when I hit ESC key twice to close both modals?

**Comment by thecrypticace** [comment] 2022-07-29 17:19
Ah yep that reproduces the issue! And the ESC key closes the wrong modal first… 🤦 . Awesome thanks for the reproduction. Will take a look!

**Comment by thecrypticace** [comment] 2022-07-29 20:08
Okay, I talked with @RobinMalfait some and we actually don't support multiple open sibling dialogs. It is definitely something we want to support but there will likely be more we have to change to properly support that. In the short term you might be able to work around the issue by nesting the dialogs/modals inside one another as children. This allows us to properly restore state. This is also why the ESC closes the first modal first and not the second one.

I'm closing this for now (sorry!) but will keep it on the mind for when we do eventually find a way to properly support multiple open dialogs that are siblings.

Here's a comment from an earlier issue with some examples with nested versus sibling dialogs: https://github.com/tailwindlabs/headlessui/issues/426#issuecomment-1059185316

**Closed by thecrypticace** 2022-07-29 20:08 UTC
