### ISSUE TITLE
Transition not working with nextjs on build

### ISSUE THREAD

**Issue by akhilmhdh** [tailwindlabs/headlessui#160] opened 2020-11-27 10:13 UTC
### Issue

I am using Transition component in NextJS. It works quite fine in development. But on build transition is not at all seen. Dont know where I am making mistake but I followed the doc itself.

### Steps to reproduce the behavior
1. Create a simple nextjs app `npx create-next-app test`
2. Follow any of the example of transition component in react doc
3. Run the build command to get your static file
4. Open and transition not seen

### Expected behavior

Transition occurs on page

### System

- Nextjs - 10.0.3
- @headlessui/react - 0.2.0
- tailwindcss - npm:@tailwindcss/postcss7-compat@^2.0.1
- react: "17.0.1",

**Comment by gino** [comment] 2021-01-04 00:02
It seems that I also face the same issue.

I am trying to use the `appear` prop to get a transition on the initial page load and it works perfectly fine in dev-mode. But unfortunately, as soon as I build my application using `next build` and try to run it `next start`, my transitions are no longer visible.

**Comment by tclare95** [comment] 2021-01-30 17:25
Just as an update on this - I am having a similar issue but only when headlessui is called via a component - if it is used directly on a page it works correctly.

**Comment by RobinMalfait** [comment] 2021-01-30 17:27
Hey! Thank you for your bug report!
Much appreciated! 🙏

Could you (or anyone having the same issue) provide a small repository as a reproduction case?

**Comment by RobinMalfait** [comment] 2021-02-05 17:12
Closing because there is no reproduction case repo.
If this issue still occurs, please open a new issue with a reproduction repo so that we can take a look.

**Closed by RobinMalfait** 2021-02-05 17:12 UTC

**Comment by andrei-zgirvaci** [comment] 2021-03-04 09:52
Having the exact same issue as described above.

Here is a transaction that works in dev but not in production:

```jsx
<Transition
  appear={true}
  show={true}
  enter="transition delay-1000 duration-1000"
  enterFrom="transform opacity-0 -translate-x-5"
  enterTo="transform opacity-100 translate-x-0"
  className="-z-1"
>
  <h6 className="h-5 -mt-2 text-sm tracking-wider uppercase origin-bottom-left rotate-90 transform-gpu whitespace-nowrap text-my-purple-light">
    Mobile App Developer · entrepreneur
  </h6>
</Transition>
```

Live demo: http://freelance-portfolio.vercel.app

**Comment by MaxOrelus** [comment] 2021-08-04 16:19
I'm having the same issue. The transition doesn't work using Next.js project.

**Comment by jaxramus** [comment] 2022-06-30 14:39
same here, transitions completely broken on static build

**Comment by jaxramus** [comment] 2022-06-30 17:14
I figured it out. One of my useEffect parameters was causing it. 

Check your useEffect it might be why your transitions are messed
