### ISSUE TITLE
Dialog shifts position on close as of v1.7.11

### ISSUE THREAD

**Issue by Naddiseo** [tailwindlabs/headlessui#2320] opened 2023-02-28 19:03 UTC
**What package within Headless UI are you using?**
@headlessui/react

**What version of that package are you using?**
v1.7.11 (also present in v1.7.12)

**What browser are you using?**

Fails on firefox and chrome

**Reproduction URL**
[a codesandbox link](https://codesandbox.io/p/sandbox/funny-cloud-h3sis5?selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A80%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A80%7D%5D&file=%2Fpages%2Findex.tsx)

**Describe your issue**

The dialog component shifts over to the left by ~40px upon closing if there is a vertical scrollbar on the screen. It appears to have been introduced in [this commit](https://github.com/tailwindlabs/headlessui/commit/adfe121678646b3f1441b312aa3564553f8bf336) (I've done a bisect from v1.7.10 to main as of this morning.)

**Comment by dgknca** [comment] 2023-03-05 19:21
I also had this problem and used [this way](https://github.com/tailwindlabs/headlessui/pull/2328/commits/36ac5cfbb3ad06b3c93266f01f536df327f2fd7a) to solve it. This problem is ignored by the authors because there is no scroll in the examples in the document.

**Comment by Kipicenko** [comment] 2023-03-21 19:56
Also faced this problem. @dgknca way certainly helps, but it's a crutch. Please correct. My suggestions.
1) Give full control to the html tag control to put
`"overflow: hidden, padding-right: (window.innerHeight - document.body.offsetWidth + 'px')`
And then it will be possible to add through the Transition callback functions (beforeEnter and afterLeave)
2) Make some props

**Comment by joepetrillo** [comment] 2023-04-13 18:16
Also seeing this issue with my modals if they have a transition and are on a page with y-scroll.

**Comment by psugihara** [comment] 2023-04-19 16:39
@joepetrillo disabling `scroll-behavior: smooth;` fixes this for me, though obiously not ideal

**Comment by marianobenitezz** [comment] 2023-04-24 14:28
So, version 1.7.1 seems to be working. Just downgrade it for now?

**Comment by 2-fly-4-ai** [comment] 2023-05-22 17:46
This issue is not solved. I see it everywhere and it is a major pain. Stop trying to close these.

**Comment by DavideFrancescon** [comment] 2023-08-22 10:55
@2-fly-4-ai  @Naddiseo @dgknca @RobinMalfait  Can you still reproduce this? I just tried and can't, maybe it's cause i'm using macOs that hides the scrollBars automatically, but even when i [lock it in view](https://stackoverflow.com/questions/7492062/css-overflow-scroll-always-show-vertical-scroll-bar) it just works as it should. Maybe it was resolved in a recent PR, which is probably what happened seeing [this](https://github.com/tailwindlabs/headlessui/pull/2328)

**Comment by DavideFrancescon** [comment] 2023-08-22 16:00
> > @2-fly-4-ai @Naddiseo @dgknca @RobinMalfait Can you still reproduce this? I just tried and can't, maybe it's cause i'm using macOs that hides the scrollBars automatically, but even when i [lock it in view](https://stackoverflow.com/questions/7492062/css-overflow-scroll-always-show-vertical-scroll-bar) it just works as it should. Maybe it was resolved in a recent PR, which is probably what happened seeing [this](https://github.com/tailwindlabs/headlessui/pull/2328)
> 
> Still happens in 1.7.16 with the codesandbox link I provided (on Ubuntu/firefox)

Okay i was able to replicate it easily on a windows device with chrome, @RobinMalfait are you still working on this or can I give it a look? Not promising i can fix it, but maybe with the link i sent before something can be done

**Comment by RobinMalfait** [comment] 2023-09-04 21:02
Hey!

This can be solved by adding `w-screen` to the wrapping div element of the Dialog panel component.

Concretely, you can apply the following diff:

```diff
- <div className="fixed inset-0 z-30 overflow-y-auto">
+ <div className="fixed inset-0 z-30 w-screen overflow-y-auto">
```

I've updated the CodeSandbox with this change as well: https://codesandbox.io/p/sandbox/epic-field-3t4w53?file=%2Fpages%2Findex.tsx%3A21%2C53&selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A80%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A80%7D%5D

I wrote more about what's going on in a similar issue: https://github.com/tailwindlabs/headlessui/issues/2525#issuecomment-1703111726

Hope this helps!

**Closed by RobinMalfait** 2023-09-04 21:02 UTC

**Comment by Naddiseo** [comment] 2023-09-04 22:00
@RobinMalfait thank you so much!

**Comment by TaeyoonKwon** [comment] 2023-12-22 16:13
> Hey!
> 
> This can be solved by adding `w-screen` to the wrapping div element of the Dialog panel component.
> 
> Concretely, you can apply the following diff:
> 
> ```diff
> - <div className="fixed inset-0 z-30 overflow-y-auto">
> + <div className="fixed inset-0 z-30 w-screen overflow-y-auto">
> ```
> 
> I've updated the CodeSandbox with this change as well: https://codesandbox.io/p/sandbox/epic-field-3t4w53?file=%2Fpages%2Findex.tsx%3A21%2C53&selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A80%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A80%7D%5D
> 
> I wrote more about what's going on in a similar issue: [#2525 (comment)](https://github.com/tailwindlabs/headlessui/issues/2525#issuecomment-1703111726)
> 
> Hope this helps!

This should be the default behavior, or at least it should be included in the demo."
