### ISSUE TITLE
Prop `id` did not match. Server: "headlessui-disclosure-button-:R6dacm:" Client: "headlessui-disclosure-button-:R1jaj5:"

### ISSUE THREAD

**Issue by xnslx** [tailwindlabs/headlessui#1561] opened 2022-06-07 20:16 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

 ^1.5.0

**What browser are you using?**

Chrome

**Describe your issue**

Hey, I am working on a react based project, but it uses react server-side rendering, I am using the headless/ui disclosure component and  I constantly get this error that I don't find any workaround. Not sure if it is a bug.  
<img width="404" alt="Screen Shot 2022-06-07 at 3 15 02 PM" src="https://user-images.githubusercontent.com/51500554/172474182-0ae4fd75-1d7b-499d-a618-fdb15b41ebb3.png">

**Comment by RobinMalfait** [comment] 2022-06-07 21:44
Hey! Thank you for your bug report!
Much appreciated! 🙏

Unfortunately, I have to close this as a reproduction was not provided. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

If this is still an issue for you, please open a new issue but include a proper reproduction GitHub repository or CodeSandbox where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

---

Fwiw, a working example can be found here:
- https://headlessui-react-git-main-tailwindlabs.vercel.app/disclosure/disclosure
- https://github.com/tailwindlabs/headlessui/blob/main/packages/playground-react/pages/disclosure/disclosure.tsx

**Closed by RobinMalfait** 2022-06-07 21:44 UTC

**Comment by cavellblood** [comment] 2022-06-14 18:04
I'm getting the same error, have been for a while but thought it was something that I was doing incorrectly. I'll see if I can get a reproduction working. I'm using [Shopify's Hydrogen Framework](https://github.com/Shopify/hydrogen) and version `1.6.3` of `@headlessui/react`.

Now that I look a little closer at that screenshot that @xnslx shared it looks like they are using Hydrogen too. Maybe it's a Hydrogen issue.

<img width="1440" alt="Screen Shot 2022-06-14 at 1 01 29 PM" src="https://user-images.githubusercontent.com/727740/173658173-bfa8c019-110d-401a-bab8-1623084daf82.png">

Hydrogen is still in a developer preview and they were using a beta version of React 18 for quite sometime but now they are using React 18.1.0.

Anyway, I'll see if I can get a reproduction up. Will need to see how easy it will be to reduce this down to something simple that I can share.

**Comment by jplhomer** [comment] 2022-06-15 17:20
Hey all - we're looking into this as well in Hydrogen. My guess is that is has to do with the nature of rendering client components, and perhaps a bug with `Suspense` + `useId()`. Haven't been able to isolate it outside of Hydrogen just yet, but will keep you posted.

**Comment by cavellblood** [comment] 2022-06-16 02:57
Thanks @jplhomer!

**Comment by nazreen** [comment] 2022-10-05 22:50
Have any of you managed to solve this? I'm not using hydrogen and I'm getting this error

**Comment by cavellblood** [comment] 2022-10-05 23:01
I'm not getting the error anymore but not at my computer right now to tell you what setup I'm using at the moment.

**Comment by xnslx** [comment] 2022-10-06 14:45
Shopify Hydrogen is taking advantage of React server side components. I have a loose feeling that it bears relation with this issue. I don't have any workabout at this point.

**Comment by jplhomer** [comment] 2022-10-06 15:01
This has been resolved in Hydrogen for a while. It was related to how we handled useId in server components.
