### ISSUE TITLE
[Bug]: Vue 3.1: CSS classes aren't applied as expected (`MenuItem`, `Switch`, and possibly others)

### ISSUE THREAD

**Issue by hognevevle** [tailwindlabs/headlessui#603] opened 2021-06-08 20:43 UTC
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://github.com/hognevevle/headlessui-bug/tree/missing-classes

### Describe your issue

This error appears when after the latest package upgrades done in the linked repo. In the prior commit, everything works OK. 

In the inspector, I see that the `class` attribute is empty. As soon as you hover the item, however, the classes will appear as they should.

Might be worth mentioning that in my other project (where I have vue-router installed), a `router-link` will render properly. So it appears to depend on the kind of child.

![CleanShot 2021-06-08 at 22 41 56](https://user-images.githubusercontent.com/2721188/121254665-d34d8300-c8aa-11eb-9272-668eb8e33bff.gif)

**Comment by rynz** [comment] 2021-06-09 00:47
There looks to be a few issues with HeadlessUI x Vue 3.1+.
Eg:
```
<Switch
    v-model="enable"
    :class="[
      ...classButton,
      'relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500',
    ]"
>
  ...
```

The `:class` will not be applied until `<Switch />` is clicked. Works okay in v3.0.11.

**Comment by rynz** [comment] 2021-06-09 00:50
```
node_modules/@headlessui/vue/dist/components/switch/switch.d.ts:45:5
    45     class?: string | Function | undefined;
           ~~~~~
    The expected type comes from property 'class' which is declared here on type 'Partial<{ as: string; modelValue: boolean; }> & Omit<Readonly<{ as: string; modelValue: boolean; } & { class?: string | Function | undefined; className?: string | Function | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "as" | "modelValue"> & Omit<...> & Record<...>'


Found 1 error.
```
Could be related, is there a reason https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/switch/switch.ts#L65 is defined explicitly as a prop?

**Comment by LaravelFreelancerNL** [comment] 2021-06-10 09:16
I can confirm this for the listbox component as well.
Neither static nor dynamically set classes are applied. The latter only when triggering the active state which will set all the appropriate classes in the following example:

```
                        <li
                            :class="[
                                active
                                    ? 'text-white bg-primary-600'
                                    : 'text-gray-900',
                                'cursor-default select-none relative py-2 pl-3 pr-9'
                            ]"
                        >
```

**Comment by rynz** [comment] 2021-06-10 09:17
Fixed in #607

**Comment by RobinMalfait** [comment] 2021-06-10 14:55
@liho00 This should be fixed, and will be available in the next release.
You can already try it using `npm install @headlessui/vue@dev` or `yarn add @headlessui/vue@dev`.

**Comment by liho00** [comment] 2021-06-10 14:58
> npm install @headlessui/vue@dev

yup the solution is in the dev branch, thanks its working now!

**Comment by RALMAZ** [comment] 2021-06-10 18:27
Thanks for fix

**Comment by johanvanhelden** [comment] 2021-06-17 14:14
@RobinMalfait do you happen to know when the next release is planned?

**Comment by schmoove** [comment] 2021-06-18 08:41
Relieved I'm not the only one experiencing this– thought I was going crazy. Thanks for fixing!

**Comment by johanvanhelden** [comment] 2021-06-30 14:55
I just updated headlessui/vue and it seems to be fixed! 🎈

**Closed** 2021-06-30 14:56 UTC

**Comment by olivoil** [comment] 2021-08-19 04:32
Hi! I'm seeing this issue with Listbox on 1.4.0 and dev and vue 3.2.2

**Comment by vesper8** [comment] 2022-04-21 18:19
Still seeing this.. `:class` not being applied for me on heroicons using Vue 3.2.33, on the application shells from Tailwind UI
