### ISSUE TITLE
Feature: close popover manually

### ISSUE THREAD

**Issue by psychonetic** [tailwindlabs/headlessui#427] opened 2021-04-22 12:40 UTC
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

v1.0.0

### What browser are you using?

Chrome

### Describe your issue

At the moment it is not possible to manually close the popover. Let's say I want to build an editable table. The editable content should be shown in the popover. When I hit the save button it should also close the popover. This is not possible, because the slots does not expose the function togglePopover.

**Comment by RobinMalfait** [comment] 2021-04-22 13:48
Hey! Thank you for your feature suggestion!
Much appreciated! 🙏

I would recommend you to move focus to the new updated content so that screenreader users also know what just changed / updated. I wrote about a similar problem here: https://github.com/tailwindlabs/headlessui/issues/358#issuecomment-822555803

**Comment by Ed1ezac** [comment] 2021-04-22 19:47
Odd enough I asked [this question](https://stackoverflow.com/questions/67212508/how-to-close-headlessui-vue-popover-from-code) today on stackoverflow...

**Comment by psychonetic** [comment] 2021-04-23 06:22
@RobinMalfait Thanks for the clarification!

I can unterstand your point, but I could also imagine cases where we don't have a visible changed element, e.g. a small chat helper form integrated in the popover. Furthermore it also seems like people questioning this quite often, because this is a common feature in most ui libraries.

BTW: how does the modal handle this? Is the body focused after closing?

So I can see three possible ways:
If the goal of this library is to enforce people to code accessible components, I agree with you.  But this should at least part of the documentation, because not every developer knows how screenreaders work. This would also help you to keep the issue board clean, so people don't question it from time to time.
 
On the other hand it should be pretty simple to expose the toggle function and leave it up to the developers. But as I said there could be situations where we don't have any active changed content outside the popover. So focussing some element just to close the popover doesn't feel natural to code and could also lead to some confusion, especially for new developers or juniors.

Also a compromise could work. So maybe the toggle/close function could be changed so that we can pass a ref or an id, which gets automatically focused. 

Then we have both: a natural way to close the popover and have still the accessible if we pass an element.

**Comment by vixeven** [comment] 2021-04-23 22:03
I have a similar scenario when the Popover should be closed by the `Done` button within it :/

Why we can't just [expose](https://ant.design/components/popover/#components-popover-demo-control) the `visible` state of the popover + auto-focusing on the `Popover.Button` after it gets closed. 👀

**Comment by jstiers** [comment] 2021-04-25 13:01
I have exactly the same issue. Even when clicking on a navigation link the popover won't close. Don't really know how to solve this.

**Comment by glennreyes** [comment] 2021-04-26 15:10
So I'm bumping into the same use case and I have two things: 

1. One - maybe possible workaround - would be to manually click the `Popover.Button` through `ref` (have to assume that popover is open), eg:

```tsx
const buttonRef = useRef();

<Popover.Button ref={buttonRef}>Click me</Popover.Button>
<Popover.Panel>
  <button onClick={() => buttonRef.current?.click()}>Content</button>
</Popover.Panel>
```

2. Ideally there was a `usePopover` hook that includes things from a context like the `open` state, a `toggle` function, etc., anything that can be consumed inside of a panel. So would be nice if I could do following inside of a panel:

```tsx
function MyPanel() {
  const popover = usePopover();

  return (
    <div>
      state: {popover.open}
      <button onClick={() => popover.close()}>Close</button>
    </div>
}

```

**Comment by DoctorDerek** [comment] 2021-04-27 02:39
> 1. Ideally there was a `usePopover` hook that includes things from a context like the `open` state, a `toggle` function, etc., anything that can be consumed inside of a panel.
Have you tried Popper / usePopper? That lets you pass the refs around. There's an example in the Headless UI docs.

**Comment by mseele** [comment] 2021-04-27 06:13
I have the same problem for programatically open the Popover. Following situation:
A user clicks on the "Add Filter" menu item in a column header menu. This should open the Filter-Popover programatically (checkout notion.io, they have a similar ux).

Please make open/close possible to trigger by the user.

**Comment by mseele** [comment] 2021-04-27 08:01
This is a workaround template for vue i've created that can toggle the popover via v-model:

```
<template>
  <Popover class="relative">
    <PopoverButton as="div">
      <button
        ref="button"
        class="px-3 py-1.5 text-xs font-medium tracking-wider rounded focus:outline-none focus-visible:bg-gray-300 hover:bg-gray-300 active:bg-gray-400"
      >
        {{ text }}
      </button>
    </PopoverButton>
    <transition
      enter-active-class="transition duration-200 ease-out"
      enter-from-class="translate-y-1 opacity-0"
      enter-to-class="translate-y-0 opacity-100"
      leave-active-class="transition duration-150 ease-in"
      leave-from-class="translate-y-0 opacity-100"
      leave-to-class="translate-y-1 opacity-0"
    >
      <PopoverPanel class="absolute right-0 transform z-60">
        <div
          ref="popover"
          class="overflow-hidden text-sm font-normal bg-white rounded shadow ring-1 ring-black ring-opacity-5 whitespace-nowrap"
        >
          <slot />
        </div>
      </PopoverPanel>
    </transition>
  </Popover>
</template>

<script lang="ts">
import { defineComponent, ref, watch } from 'vue'
import { Popover, PopoverButton, PopoverPanel } from '@headlessui/vue'

export default defineComponent({
  components: { Popover, PopoverButton, PopoverPanel },
  props: {
    text: {
      type: String,
      required: true,
    },
    modelValue: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    const button = ref<HTMLButtonElement>()
    const popover = ref<Element>()

    const emitModelValue = ref(false)

    watch(popover, (newValue) => {
      emitModelValue.value = true
      emit('update:modelValue', newValue != undefined)
    })

    watch(
      () => props.modelValue,
      (newValue) => {
        if (emitModelValue.value) {
          emitModelValue.value = false
          return
        }
        const isOpen = popover.value != undefined
        if (newValue != isOpen) {
          button.value?.click()
        }
      }
    )

    return { button, popover }
  },
})
</script>

```

And here is an example of how to use it:

```
<template>
  <action-popover v-model="open" text="click me"> content </action-popover>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import ActionPopover from './ActionPopover.vue'

export default defineComponent({
  components: { ActionPopover },
  setup() {
    const open = ref(false)

    // open popover if not already open
    // open.value = true

    // close popover if already open
    // open.value = false

    return { open }
  },
})
</script>
```

**Comment by fergusmeiklejohn** [comment] 2021-04-27 09:28
I also think that popovers and menus should have the option to close when the user clicks on them. It's the right UX in many situations.
Maybe `closeOnClick = true`

**Comment by jstiers** [comment] 2021-05-02 13:58
I did get it to work eventually, but it feels super hacky and I'm not comfortable doing this every time this issue comes up.
It does seem that there is an accessibility issue in general in the current coding meta, because of how hard focus management can be.

React router barely touches it, Next.js router doesn't really work like this, only Reach Router truly deals with accessibility.

It's too bad, because the Popover made for Headless.ui is beautiful and works really well.

**Comment by barnabasmolnar** [comment] 2021-05-03 10:57
I'm going to chime in and agree with those before me, the ability to close the popover programatically would be most welcome if not essential.

For now I'm using @glennreyes's first suggestion, which, while it does work, feels very hacky. :(

**Comment by DoctorDerek** [comment] 2021-05-03 17:39
I got it to close just fine by tracking the reference to the Popover Button
using useRef in React and sending a click to it.

**Comment by matamatanot** [comment] 2021-05-07 23:34
Using the `Disclosure` component, I was faced with the same problem.
There is `<form />` in `Disclosure.Panel`. I want to close the form(`Disclosure.Panel`.) after submitting it (after pressing the button submit).

**Comment by Xairoo** [comment] 2021-05-21 08:58
Also ran into this problem. I trigger `onClick` in a child element inside `Popover.Button`.
I don't have to close this popover by clicking outside the popover, but with the open/close button.

That's a wrapper to reuse it...

`props.visible` will set the initial open/close state.

```
import React, { useState } from 'react';
import { Popover, Transition } from '@headlessui/react';
import { usePopper } from 'react-popper';

import tw, { css } from 'twin.macro'; // Tailwind...

const Popover_ = (props) => {
	const [visible, setVisible] = useState(props.visible);
	const [referenceElement, setReferenceElement] = useState();
	const [popperElement, setPopperElement] = useState();
	const { styles, attributes } = usePopper(referenceElement, popperElement, {
		placement: 'top-end',
		modifiers: [
			{
				name: 'offset',
				options: {
					offset: [5, 5],
				},
			},
		],
	});

	function onClickHandle(e) {
		e.preventDefault();
		setVisible(!visible);
	}

	return (
		<Popover className="relative">
			{({ open }) => (
				<>
					<Popover.Button
						ref={setReferenceElement}
						css={[
							tw`px-3 py-2`,
							tw`transition duration-500 ease-in-out `,
							open && tw`text-opacity-50`,
						]}
					>
						<div onClick={(e) => onClickHandle(e)}>Open/Close</div>
					</Popover.Button>
					<Transition
						show={visible}
						enter="transition ease-out duration-200"
						enterFrom="opacity-0 translate-y-1"
						enterTo="opacity-100 translate-y-0"
						leave="transition ease-in duration-150"
						leaveFrom="opacity-100 translate-y-0"
						leaveTo="opacity-0 translate-y-1"
					>
						{visible && (
							<div>
								<Popover.Panel
									static={visible}
									ref={setPopperElement}
									style={styles.popper}
									{...attributes.popper}
									css={[tw`absolute z-50 w-screen max-w-sm px-4`]}
								>
									<div
										css={[
											tw`overflow-hidden rounded-lg shadow-lg ring-1 ring-black ring-opacity-5`,
										]}
									>
										<div
											css={[
												tw`relative grid gap-8 text-black bg-white p-7 lg:grid-cols-2`,
											]}
										>
											content
										</div>
									</div>
								</Popover.Panel>
							</div>
						)}
					</Transition>
				</>
			)}
		</Popover>
	);
};

export default Popover_;

```

**Comment by lunelson** [comment] 2021-05-28 11:41
Same issue today, with the React version. 

If I'm using a `Popover` with navigation links and it's part of a persistent layout, I need a way to trigger a close when the user navigates somewhere else. 

In Next.js for example, I can do this in a `useEffect` hook that watches the `router.asPath` value and closes the menu if it's open... but only if I have access to some kind of close function 😐

**Comment by DoctorDerek** [comment] 2021-05-28 18:52
Hey Lu,
Can't you track the state in React of whether the popover is open, and then
simply set that to false when you need it to?

There's a static popover example in the docs demonstrating using an {open}
variable...

**Comment by lunelson** [comment] 2021-05-28 19:35
@DoctorDerek no, unfortunately in the example you cite, what's being passed through is not a variable, it's just a primitive value, so you can read it, but you can't set it. Assuming the `Popover` is using some kind of state setter or reducer function internally, one solution would be to pass a reference to that function through along with the state (`open`) value

**Comment by DoctorDerek** [comment] 2021-05-28 23:20
Hey @lunelson thanks so much for your comment, because it got me to solve this "click messes up hover toggle" `Popover` bug I've needed to solve for a project.

Here's the Codesandbox reproduction showing that you can close the Popover by triggering a click on it using the `useRef` React Hook: https://codesandbox.io/s/github/DoctorDerek/headlessui-example-close-popover-dynamically-in-react-hover-flyout-dropdown-menu/tree/main/?file=/src/App.js

And the code:
```jsx
import { Fragment, useRef, useState } from "react"
import { Popover, Transition } from "@headlessui/react"
import { ChevronDownIcon } from "@heroicons/react/solid"

function classNames(...classes) {
  return classes.filter(Boolean).join(" ")
}

export default function FlyoutMenu({
  menuTitle = "Hover Popover",
  linksArray = [
    // [[title: string, href: string], ...]
    ["Home", "/"],
    ["About", "/about"],
    ["Blog", "/blog"]
  ]
}) {
  let timeout // NodeJS.Timeout
  const timeoutDuration = 400

  const buttonRef = useRef(null) // useRef<HTMLButtonElement>(null)
  const [openState, setOpenState] = useState(false)

  const toggleMenu = (open) => {
    // log the current open state in React (toggle open state)
    setOpenState((openState) => !openState)
    // toggle the menu by clicking on buttonRef
    buttonRef?.current?.click() // eslint-disable-line
  }

  // Open the menu after a delay of timeoutDuration
  const onHover = (open, action) => {
    // if the modal is currently closed, we need to open it
    // OR
    // if the modal is currently open, we need to close it
    if (
      (!open && action === "onMouseEnter") ||
      (open && action === "onMouseLeave")
    ) {
      // clear the old timeout, if any
      clearTimeout(timeout)
      // open the modal after a timeout
      timeout = setTimeout(() => toggleMenu(open), timeoutDuration)
    }
    // else: don't click! 😁
  }

  const handleClick = (open) => {
    setOpenState(!open) // toggle open state in React state
    clearTimeout(timeout) // stop the hover timer if it's running
  }

  const LINK_STYLES =
    "py-5 px-1 w-64 text-base text-gray-900 uppercase transition duration-500 ease-in-out hover:text-blue-800 hover:bg-blue-100 font-bold"

  return (
    <>
      <Popover className="relative mx-auto mt-1 w-64">
        {({ open }) => (
          <div
            onMouseEnter={() => onHover(open, "onMouseEnter")}
            onMouseLeave={() => onHover(open, "onMouseLeave")}
          >
            <div className="mx-auto">
              <Popover.Button ref={buttonRef}>
                <div
                  className={classNames(
                    open ? "text-blue-800" : "text-gray-800",
                    "bg-white rounded-md items-center mx-auto border-2 border-black border-solid flex justify-center",
                    LINK_STYLES
                  )}
                  onClick={() => handleClick(open)}
                >
                  <span className="uppercase">
                    {menuTitle} ({openState ? "open" : "closed"})
                  </span>
                  <ChevronDownIcon
                    className={classNames(
                      open ? "text-gray-600 translate-y-1.5" : "text-gray-400",
                      "ml-2 h-5 w-5 transform transition-all"
                    )}
                    aria-hidden="true"
                  />
                </div>
              </Popover.Button>
            </div>

            <Transition
              show={open}
              as={Fragment}
              enter="transition ease-out duration-200"
              enterFrom="opacity-0 translate-y-1"
              enterTo="opacity-100 translate-y-0"
              leave="transition ease-in duration-150"
              leaveFrom="opacity-100 translate-y-0"
              leaveTo="opacity-0 translate-y-1"
            >
              <Popover.Panel static className="z-10 w-64 mx-auto">
                <div className="relative grid space-y-[2px] bg-white border-2 border-gray-300 border-solid divide-y-2 rounded-md text-center">
                  {linksArray.map(([title, href]) => (
                    <Fragment key={"PopoverPanel<>" + title + href}>
                      <a href={href} className={LINK_STYLES}>
                        {title}
                      </a>
                    </Fragment>
                  ))}
                </div>
              </Popover.Panel>
            </Transition>
          </div>
        )}
      </Popover>
    </>
  )
}
```

Crossposted to #239

**Comment by DoctorDerek** [comment] 2021-05-29 05:04
#### fix: add `event.stopPropagation()` to allow `onMouseLeave` (hover event "mouse out") to trigger.
* Otherwise there is a bug where the Popover menu "click outside" event instantly closes the menu, then the `onHover(open,"onMouseLeave")` event triggers 500 milliseconds later, reopening the menu unexpectedly.
* The new behavior is that there is no action when you click outside, except the hover changes focus.
* I tested that it's working normally on my desktop and mobile Chrome browsers.

I updated the code above. Here is the new code I added:
```
  const handleClickOutside = (event) => {
    if (buttonRef.current && !buttonRef.current.contains(event.target)) {
      event.stopPropagation()
    }
  }
  useEffect(() => {
    document.addEventListener("mousedown", handleClickOutside)

    return () => {
      document.removeEventListener("mousedown", handleClickOutside)
    }
  })
```

**Comment by luizjr** [comment] 2021-08-12 17:35
`<Popover.Button></Popover.Button>` It works, but if I put another function to run when I click, it doesn't close anymore. I want to run a function and then have it close.

**Comment by DerekLoop** [comment] 2021-08-13 21:37
Hey Luiz, could you be more specific? You may just need to have a wrapper around your handleClick function: `() => {yourFunction(); handleClick()}`

**Comment by adamwathan** [comment] 2021-09-10 13:58
Hey! Going to close this particular one as what the OP requested is now possible by wrapping a child of the popover in a `<Popover.Button>` or by using the `close` function that is passed in to the render prop.

https://headlessui.dev/react/popover#closing-popovers-manually

If you have a use case that isn't covered by this, please open a new issue so we can discuss it there, thanks ❤️

**Closed by adamwathan** 2021-09-10 13:58 UTC
Labels: Needs more info

**Comment by andrefedev** [comment] 2022-01-26 06:09
@adamwathan The first example didn't work, at least not with the nextjs Link component, it just doesn't close.


```
function MyPopover() {
  return (
    <Popover>
      <Popover.Button>Solutions</Popover.Button>
      <Popover.Panel>
        <Popover.Button as={MyLink} href="/insights">
          Insights
        </Popover.Button>
        {/* ... */}
      </Popover.Panel>
    </Popover>
  )
}
```

```
{NavbarMenu.map((e) => (
  <Popover.Button as={Link} href={e.url}>
    <a
      className={clsx(
        "block rounded-md py-2 px-3 text-base font-medium",
        {
          "bg-green-100 text-green-900": router.route === e.url,
          "hover:bg-gray-50": router.route !== e.url,
        },
      )}>
      {e.name}
    </a>
  </Popover.Button>
))}
```

**Comment by RobinMalfait** [comment] 2022-01-26 08:24
@andrefedev make sure to create your own Link component. E.g.: https://headlessui.dev/react/menu#integrating-with-next-js

**Comment by heggemsnes** [comment] 2022-02-13 16:16
@RobinMalfait Thank you for this! Just spent an hour pulling my hair out why the Next.js Link component didn't work here. 

Would be great with a little "gotcha" regarding Next.js on the Popover docs, similar to the Menu docs are you are referring to here.

**Comment by thecyrilcril** [comment] 2023-09-11 03:15
> So I'm bumping into the same use case and I have two things:
> 
> 1. One workaround would be to manually click the `Popover.Button` through `ref` (have to assume that popover is open), eg in React:
> 
> ```tsx
> const buttonRef = useRef();
> 
> <Popover>
>   <Popover.Button ref={buttonRef}>Click me</Popover.Button>
>   <Popover.Panel>
>     <button onClick={() => buttonRef.current?.click()}>Content</button>
>   </Popover.Panel>
> </Popover>
> ```

In vue 3 the above would be like so
```vue
<script setup>
import { ref } from 'vue'
import { Popover, PopoverButton, PopoverPanel } from '@headlessui/vue'
...

const popoverButton = ref(null)

// on some reactive condition
if (condition) {
    popoverButton.value.el.click()
}
...
</script>
<template>
    <PopoverButton ref="popoverButton">
    <PopoverPanel>
        <button @click="popoverButton.value.el.click()">close</button>
    </PopoverPanel>
</template>
```

**Comment by aqordeon** [comment] 2023-09-22 05:45
for someone who still struggling with how to open and close Popover using a state (not using click to a button), I made a simple code in Vue 3

```
<script setup>
    const popoverValue = ref(false)
    ...
</script>

<template>
    <Popover>
        <transition enter-active-class="transition duration-200 ease-out" enter-from-class="translate-y-1 opacity-0"
            enter-to-class="translate-y-0 opacity-100" leave-active-class="transition duration-150 ease-in"
            leave-from-class="translate-y-0 opacity-100" leave-to-class="translate-y-1 opacity-0">
            <div v-if="popoverValue">
                <PopoverPanel static>
                    <!-- Popover content here -->
                </PopoverPanel>
            </div>
        </transition>
    </Popover>
</template>
```
