### ISSUE TITLE
[Bug]: Modal focus trap is set to body if you click on a non-interactable element on the page

### ISSUE THREAD

**Issue by whaleprophet** [tailwindlabs/headlessui#632] opened 2021-06-22 03:14 UTC
### What package within Headless UI are you using?

@headlessui/react

### What version of that package are you using?

1.2.0

### What browser are you using?

Chrome

### Reproduction repository

https://headlessui.dev/react/dialog

### Describe your issue

You can repro the issue on the headless ui Modal example
When you open the Modal, you can hit 'esc' to escape the modal.
However, if you select the text (or click on the white part of the modal)
you will no longer be able to hit esc to escape the Modal.

<img width="524" alt="Screen Shot 2021-06-21 at 8 13 49 PM" src="https://user-images.githubusercontent.com/3210756/122857392-42749f80-d2cd-11eb-83b5-2631087f7cf8.png">

**Comment by sazzadsazib** [comment] 2021-06-23 09:53
I did a little digging. I am not sure if this is a correct solution.
I think dialog need a `useWindowEvent` for `keydown` in dialog.
It looks like 
```tsx
useWindowEvent('keydown', event => {
    if (event.key !== Keys.Escape) return
    if (dialogState !== DialogStates.Open) return
    if (hasNestedDialogs) return
    event.preventDefault()
    event.stopPropagation()
    close();
  })
  ```
  Checked in playground works fine
  Please let me know if I am correct I will create a PR :)

**Comment by cubecleveland** [comment] 2021-06-24 11:23
HI, i was wondering if its related to the issue i am having with my modal throwing an exception when someone tries to hot key and reload a different page when modal is open.
It completely crashes the app...

Where is useWindowEvent coming from ?

**Comment by sazzadsazib** [comment] 2021-06-24 11:57
> Where is `useWindowEvent` coming from ?

`Dialog` component of headlessUI need this as event listener of `keydown` to solve the problem above, its not a prop ! 

@cubecleveland  can you produce this in codesandbox and reproduce that bug ! I can try to help you out :)

**Comment by cubecleveland** [comment] 2021-06-24 12:03
Thanks for your response!!

Its hard to reproduce but ill try to explain my best.
If the page has any type of forwarding, redirect or hot key navigation while modal is open. it Throws an exception of Focus Trap not found.

So.... lets say you have a hotkey of Ctrl+N that navigates the page to a url, if this is pressed while the dialog is open i get the exception....

Does that make sense ?

**Comment by patrikholcak** [comment] 2021-06-25 08:57
Probably a duplicate of #524

**Comment by RobinMalfait** [comment] 2021-07-04 19:42
Hey! Thank you for your bug report!
Much appreciated! 🙏

Going to close this as a duplicate of #524

**Closed by RobinMalfait** 2021-07-04 19:42 UTC
