### ISSUE TITLE
input in Dialog will not autofocus when add Transition to Dialog on mobile browser

### ISSUE THREAD

**Issue by TXWSLYF** [tailwindlabs/headlessui#2529] opened 2023-06-09 06:54 UTC
**What package within Headless UI are you using?**

@headlessui/react

**What version of that package are you using?**

v1.7.15

**What browser are you using?**

macOS Chrome, Safari
iOS Safari, iOS Chrome

**Reproduction URL**
https://codesandbox.io/s/jolly-hawking-g5cndt?file=/src/App.tsx

**Describe your issue**
If the Dialog component is wrapped by a Transition component, when the Dialog component is opened  the input element inside it will not autofocused on mobile browser, but on pc browser everything works fine.

**Comment by thecrypticace** [comment] 2023-06-13 20:27
I believe this is an iOS Safari limitation regarding programmatic focus of an element when not directly caused by a click (it is caused by one but because there's a transition there's a delay). I don't believe there is a reliable workaround for this at the moment other than manually focusing the input. Weirdly enough iOS does give the input focus styles but doesn't actually trigger it to accept keyboard input *unless* you're using a connected hardware keyboard.

Good news is that it appears, at least from my limited testing, that this issue may no longer be present in iOS 17 once it's released. I don't see a specific WebKit bug report for this though.

The reason you see this in iOS Chrome is because it's not actually running Chrome proper. It still uses WebKit/Safari for rendering web pages because of iOS / App Store limitations. Only the UI / chrome (heh) is different.

Because there's not a workaround I'm gonna close this (sorry!) — wish I had better news. But it should hopefully be fixed in a 3–4 months once iOS 17 is out.

**Closed by thecrypticace** 2023-06-13 20:27 UTC

**Comment by TXWSLYF** [comment] 2023-06-14 02:12
thank you for your reply, but i found a same example however it works fine even in ios

https://pixiv.github.io/charcoal/iframe.html?id=modal--full-bottom-sheet&args=&viewMode=story

**Comment by thecrypticace** [comment] 2023-06-14 02:17
That example doesn't use a Transition — therefore no delay — which is why it works. The no Transition version also works in Headless UI on iOS.

Here's a pure React example. No Headless UI at all which doesn't focus in iOS: https://codesandbox.io/s/focused-snow-7mcppm

**Comment by TXWSLYF** [comment] 2023-06-14 06:35
Thank you for your reply. In fact, the example I posted does use a transition, but only on the mobile browser. If you visit it with a mobile phone, I think you will see the transition.

**Comment by mirko-kienle** [comment] 2023-09-20 13:15
For anyone running across this same issue, I can confirm a couple of things now that iOS17 is out:

- focusing in either the [reproduction codepen](https://codesandbox.io/s/jolly-hawking-g5cndt?file=/src/App.tsx) or the [pure react example](https://codesandbox.io/s/focused-snow-7mcppm) unfortunately still doesn't work
- the working example above looks to be using the adobe's react-spectrum [Dialog](https://react-spectrum.adobe.com/react-spectrum/Dialog.html#examples) component
- this works flawlessly on iOS (try the third example down from the link above)

my conclusion is that there is a possible workaround and adobe has managed to find it 🙂 
i'll try to do some digging into adobe's [repo](https://github.com/adobe/react-spectrum) on how they did it
