### ISSUE TITLE
Focusing input on nested Dialog

### ISSUE THREAD

**Issue by asivaneswaran** [tailwindlabs/headlessui#3137] opened 2024-04-25 14:52 UTC
**What package within Headless UI are you using?**

For example: @headlessui/vue

**What version of that package are you using?**

For example: v1.7.20

**What browser are you using?**

For example: Chrome

**Describe your issue**

If you open a Dialog nested in another Dialog, you can't click on input directly and it doesn't receive focus. You have to click on the second Dialog to then be able to click on the input.

There is also a description for this: https://github.com/tailwindlabs/headlessui/discussions/2355

**Comment by RobinMalfait** [comment] 2024-05-29 17:18
Hey!

Right now we don't support sibling `<Dialog />` components in `@headlessui/vue`. If you want to open multiple `<Dialog />` components then you have to nest them from a Vue tree perspective.

Here is an example on how you can use this and seems to work as expected: https://codesandbox.io/p/devbox/compassionate-babycat-hq3tsk?file=%2Fsrc%2FApp.vue%3A11%2C31

If you are still running into this issue, please create a new issue with a minimal reproduction repo attached.

Going to close this for now since the CodeSandbox seems to work as expected.

**Closed by RobinMalfait** 2024-05-29 17:18 UTC
