### ISSUE TITLE
[Bug]: Interacting with third-party components that use portals inside a Dialog closes the Dialog

### ISSUE THREAD

**Issue by bakerkretzmar** [tailwindlabs/headlessui#432] opened 2021-04-22 19:52 UTC
### What package within Headless UI are you using?

@headlessui/vue

### What version of that package are you using?

1.0.0

### What browser are you using?

Firefox

### Reproduction repository

https://codesandbox.io/s/pensive-fast-yxokp?file=/src/App.vue

### Describe your issue

When any component inside a Dialog renders itself elsewhere in the DOM using a Portal/Teleport, clicking in it closes the entire Dialog. The example above uses `vue-flatpickr-component` to create a date picker inside a modal, but because it renders the actual flatpickr instance somewhere else in the DOM, clicking any date closes the entire modal.

The [docs on this](https://headlessui.dev/vue/dialog#mouse-interaction) say:

> When a Dialog is rendered, clicking the `DialogOverlay` will close the Dialog.

But that isn't exactly the case—it's not clicking the `DialogOverlay` specifically that closes the Dialog, but clicking **anything that is not a child of the Dialog** in the DOM.

I believe the relevant part of the code is here: https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-vue/src/components/dialog/dialog.ts#L174-L184

What do you think about adding a way to disable that global `mousedown` handler, or adding an option to actually only close the Dialog based on clicks directly on the `DialogOverlay` component?

**Comment by RomainLanz** [comment] 2021-04-30 13:58
I have the same issue as described, clicking on the calendar provided by `flatpickr` closes the Dialog.

**Comment by ThatOneAwkwardGuy** [comment] 2021-05-01 14:01
I Also have the same issue with showing a loading indicator above the Modal, any accidental clicks on the loading indicator will then close the modal.

**Comment by michgeek** [comment] 2021-05-04 06:12
I can confirm the issue.  I use dialog with scrollable content that contains a selectbox. The selectbox options list is rendered at body level in a teleport and positioned with popper. Clicking on the options list will close the dialog.

**Comment by narciero** [comment] 2021-05-18 20:07
is there a workaround for this?

**Comment by bakerkretzmar** [comment] 2021-05-19 13:55
I was able to get it working on my project for now by also setting `static: true` in the Flatpickr config, but this issue is still there by default and might not be avoidable with other libraries.

**Comment by agorin** [comment] 2021-05-27 15:41
I have the same issue as described, clicking on the calendar provided by devextreme closes the Dialog.
is there a workaround for this?

**Comment by nasa8x** [comment] 2021-06-08 13:39
I am using CKeditor BalloonEditor the Modal also close after clicking editor toolbar.
Plz fix soon. Thank you.

**Comment by chinanderm** [comment] 2021-06-29 03:56
What is the fix/solution or status of this? I would really like to use headless UI for dialogs and other things but cannot if it breaks my existing usage of third party libraries such as flatpickr.

**Comment by loktarjugg** [comment] 2021-08-07 04:12
i have the same issue. when i use some element over the dialog and click the element, dialog will be close

**Comment by Aleksion** [comment] 2021-08-12 15:24
What about changing the 

```
 useWindowEvent('mousedown', function (event) {
    var _internalDialogRef$cu;

    var target = event.target;
    if (dialogState !== DialogStates.Open) return;
    if (hasNestedDialogs) return;
    if ((_internalDialogRef$cu = internalDialogRef.current) == null ? void 0 : _internalDialogRef$cu.contains(target)) return;
    close();
  }); // Scroll lock
```

to a click handler on the overlay instead?

**Comment by RomainLanz** [comment] 2021-12-08 09:18
Hey there! 👋🏻 

Small bump of the issue.

**Comment by dcastil** [comment] 2021-12-14 14:19
I opened a PR to fix the issue for the React-specific version in https://github.com/tailwindlabs/headlessui/pull/989. Not sure though whether this fix is also applicable in Vue since it relies on the event delegation system of React.

**Comment by RodolfoSilva** [comment] 2021-12-25 17:43
I'm using react. And this comment solve my issue.

> Hey! Thank you for your bug report!
> Much appreciated! 🙏
> 
> You can import the `Portal` component from Headless UI, and wrap the Toast/notification into a Portal component. When a `Portal` component is used inside a `Dialog` then we will render the contents in the root of the `Dialog` instead of the root of the document.

https://github.com/tailwindlabs/headlessui/issues/780#issuecomment-917663939

Thanks @RobinMalfait

**Comment by nasa8x** [comment] 2021-12-27 02:28
With React just add this it worked for me:
`Dialog as="div" static onClose={() => null} ...`

**Comment by agorin** [comment] 2021-12-27 07:56
With Vue, it does not work...

**Comment by RomainLanz** [comment] 2022-01-06 09:31
> With React just add this it worked for me: `<Dialog as="div" static onClose={() => null} className="fixed z-50 inset-0 overflow-y-auto modal">`

This could work.
The issue is now with other way to close the dialog.

The quick solution would be to remove the `@close` handler on the `Dialog` component and adding `@click` handler on the `DialogOverlay` to emit the `close` event.

You still need to handle other way of closing the dialog, like pressing the Escape key.

**Comment by RomainLanz** [comment] 2022-01-12 07:49
After testing the solution I have proposed, there are still issues with `flatpickr`.
Somehow, the `year` input is not focusable when it is inside the `Dialog` component.

**Comment by eskiesirius** [comment] 2022-03-23 19:32
any workaround in vue?

**Comment by sgehrman** [comment] 2022-03-24 00:43
same bug.  What's taking so long?

**Closed** 2022-03-24 19:02 UTC

**Comment by RobinMalfait** [comment] 2022-03-24 19:09
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #1268, and will be available in the next release.

You can already try it using `npm install @headlessui/react@insiders` or `yarn add @headlessui/react@insiders`.

---

I've updated your CodeSandbox with the latest insiders build: https://codesandbox.io/s/sweet-tree-egth6u

**Comment by bakerkretzmar** [comment] 2022-03-24 19:27
Thanks! That demo works for me, I have a few questions though that I'll leave as comments on the PR.

**Comment by sgehrman** [comment] 2022-03-25 01:09
steve@5950x:~/Documents/GitHub/mavrik/nftcompany-frontend$ npm install @headlessui/react@insiders
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steve/.npm/_logs/2022-03-25T01_09_21_535Z-debug-0.log

**Comment by eskiesirius** [comment] 2022-03-25 03:53
It worked but there is a bug with @vuepic/vue-datepicker

https://codesandbox.io/s/exciting-fog-cefyoh?file=/src/App.vue

**Comment by RobinMalfait** [comment] 2022-03-25 13:54
@eskiesirius do you mind telling me what the bug is? 😅 

<img width="552" alt="image" src="https://user-images.githubusercontent.com/1834413/160134052-223049a8-563d-4df6-82dd-1844fb7f60c2.png">

**Comment by eskiesirius** [comment] 2022-03-25 14:00
> @eskiesirius do you mind telling me what the bug is? 😅
> 
> <img alt="image" width="552" src="https://user-images.githubusercontent.com/1834413/160134052-223049a8-563d-4df6-82dd-1844fb7f60c2.png">

sorry but it opens automatically

**Comment by eskiesirius** [comment] 2022-03-25 14:14
okay.. thank you so much!!!

**Comment by vinnygambiny** [comment] 2023-02-04 19:28
I still have an issue related to the portal and the `Popover` with `Combobox`.

I use `headlessui-float` with the portal, and when the focus goes to the `ComboboxInput`, the `Popover` close. If I remove the `ComboboxInput`, then it's when I click on an `ComboboxOption`.

Here is an exemple https://codesandbox.io/s/billowing-thunder-0s724d

**Comment by sbc640964** [comment] 2023-02-28 08:43
I have the opposite problem.
I render a listbox in a portal from a dialog, and cannot create a focus in it... (because it is outside the portal of the dialog)
