### ISSUE TITLE
React Menu dropdown animation bug over other components

### ISSUE THREAD

**Issue by fergusmeiklejohn** [tailwindlabs/headlessui#275] opened 2021-03-10 03:08 UTC
If I set `z-0` the dropdown menu doesn't animate properly over components lower in the page (see first screen grab video)
If set `z-10` the animation works but lower versions of the component are not obscured (seems like I can't set `z-10` for the whole component and `z-20` for the `Menu.Items`) (see second screen grab video)

animation bug if z-0:
https://user-images.githubusercontent.com/11864025/110570370-bcef3880-8190-11eb-8d84-a738982c1733.mov

animation bug if z-10
https://user-images.githubusercontent.com/11864025/110570395-c4164680-8190-11eb-9682-664cd343d8dc.mov

**Comment by RobinMalfait** [comment] 2021-04-22 15:30
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a minimal reproduction case and share it?
This is likely not a bug with Headless UI itself because we don't render anything, however I know transitions can act weird because of stacking context. If you provide a minimal reproduction case, then I can see if I can improve it for you.

**Comment by RobinMalfait** [comment] 2022-02-21 15:19
Hey!

Going to close this issue since a reproduction was not provided.

If this is still an issue for you, please open a new issue but include a proper reproduction via a GitHub repository where you already have everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Closed by RobinMalfait** 2022-02-21 15:19 UTC
Labels: Needs more info
